using System;
using RimMandrake.MessyConduit.Core;

namespace RimMandrake.MessyConduit.Hose
{
    /// <summary>
    /// GENERATED by src/RimMandrake/Utils/mockups/messy_conduit/reel_intake_geometry.py from the reel art (all four looks,
    /// stored Reel_PumpHookup and laid Reel_Deployed, drawSize 2.8). Do not hand-edit: re-run the script.
    /// Owner, station 42 (2026-10-04): "pipe does NOT hook up properly to the next reel station". Where a relay hose's
    /// coupling face meets the drawn reel, per approach side, in cells from the 2x2 footprint centre:
    ///   row = { westInletDz, westInletDepth, E0 perp, E0 depth, E1 perp, E1 depth, N0.., N1.., S0.., S1.. }
    /// perp = offset along the edge from the footprint centre (x for N/S, z for E); depth = outline minus the footprint edge
    /// along the outward normal (+ = outside). West: the art's one brass inlet (both west cells couple to it).
    /// </summary>
    public static class ReelIntakeGeometry
    {
        public static readonly string[] Looks = { "Scrapper", "Industrial", "Modern", "Futuristic" };

        private static readonly double[,] table =
        {
            { -0.060, 0.269, -0.795, 0.127, 0.708, 0.028, -0.773, -0.005, 0.073, -0.300, -0.423, -0.114, 0.741, -0.016 },   // Scrapper Reel_PumpHookup
            { -0.060, 0.269, -0.500, 0.148, 0.708, 0.028, -0.773, -0.005, 0.062, -0.300, -0.412, -0.114, 0.500, -0.245 },   // Scrapper Reel_Deployed
            { -0.093, 0.236, -0.412, 0.203, 0.708, 0.094, -0.762, -0.005, 0.084, -0.278, -0.500, -0.158, 0.686, 0.006 },   // Industrial Reel_PumpHookup
            { -0.104, 0.280, -0.445, 0.225, 0.708, 0.116, -0.795, 0.006, 0.073, -0.278, -0.500, -0.125, 0.609, -0.256 },   // Industrial Reel_Deployed
            { -0.060, 0.291, -0.456, 0.247, 0.708, 0.127, -0.106, -0.005, 0.095, -0.267, -0.500, -0.103, 0.762, -0.005 },   // Modern Reel_PumpHookup
            { -0.066, 0.302, -0.347, 0.236, 0.708, 0.105, -0.106, -0.005, 0.084, -0.267, -0.500, -0.092, 0.500, -0.234 },   // Modern Reel_Deployed
            { -0.071, 0.291, -0.292, 0.236, 0.697, 0.137, -0.128, -0.005, 0.073, -0.278, -0.500, -0.081, 0.752, 0.006 },   // Futuristic Reel_PumpHookup
            { -0.071, 0.291, -0.467, 0.247, 0.697, 0.137, -0.128, -0.005, 0.073, -0.278, -0.500, -0.081, 0.500, -0.223 },   // Futuristic Reel_Deployed
        };

        public static int LookIndex(string look)
        {
            int i = Array.IndexOf(Looks, look);
            return i < 0 ? 0 : i;
        }

        private static int Row(string look, bool deployed) => LookIndex(look) * 2 + (deployed ? 1 : 0);

        /// <summary>The west inlet: (dz from the footprint centre, depth beyond the west edge).</summary>
        public static void WestInlet(string look, bool deployed, out double dz, out double depth)
        {
            int r = Row(look, deployed);
            dz = table[r, 0];
            depth = table[r, 1];
        }

        /// <summary>side 0 = E, 1 = N, 2 = S; cell 0 = the lower-coordinate edge cell, 1 = the higher.</summary>
        public static void Edge(string look, bool deployed, int side, int cell, out double perp, out double depth)
        {
            int r = Row(look, deployed), c = 2 + (side * 2 + cell) * 2;
            perp = table[r, c];
            depth = table[r, c + 1];
        }

        public const int RowCount = 8;
    }
}
