#!/usr/bin/env python3
"""STILLSAND_DEAD_GATE_SWEEP_1: find gates naming a packageId that is not loaded at runtime.
Classes: ORPHAN_OURS / ORPHAN_EXTERNAL (no About.xml under src defines it),
COMPOSED (defined by a source About.xml but folded into the unified biomes mod, never loaded standalone),
INERT (MayRequire on a top-level <Operation>, ignored by engine; listed separately)."""
import re, json, pathlib
from collections import Counter
import xml.etree.ElementTree as ET

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"


def pid_of(path):
    try:
        return (ET.parse(path).getroot().findtext("packageId") or "").strip().lower()
    except Exception:
        return ""


defined = {}
for a in SRC.rglob("About.xml"):
    if a.parent.name != "About":
        continue
    p = pid_of(a)
    if p:
        defined[p] = a.relative_to(ROOT).as_posix()

comp = json.load(open(SRC / "RimMandrake/Biomes.compose.json"))
SHIP = comp["about"]["packageId"].lower()
composed = {}
composed_about = set()
for e in comp["entries"]:
    if e["wave"] <= comp["compose_wave"]:
        ab = SRC / "RimMandrake" / e["source"] / "About/About.xml"
        if ab.exists():
            composed[pid_of(ab)] = e["key"]
            composed_about.add(ab.relative_to(ROOT).as_posix())

defined[SHIP] = "generated by deploy_custom_mods.py --compose biomes (Biomes.compose.json)"
for _d in ("ludeon.rimworld", "ludeon.rimworld.royalty", "ludeon.rimworld.ideology", "ludeon.rimworld.biotech", "ludeon.rimworld.anomaly", "ludeon.rimworld.odyssey"):
    defined[_d] = "DLC"

PID = re.compile(r"[A-Za-z0-9_\-]+(?:\.[A-Za-z0-9_\-]+)+")
refs = []  # (file, line, kind, pid, inert)


def add(f, line, kind, pids, inert=False):
    for p in re.split(r"\s*,\s*", pids):
        p = p.strip()
        if PID.fullmatch(p):
            refs.append((f, line, kind, p, inert))


for f in SRC.rglob("*.xml"):
    rel = f.relative_to(ROOT).as_posix()
    if "/obj/" in rel:
        continue
    try:
        txt = f.read_text(encoding="utf-8-sig", errors="replace")
    except Exception:
        continue
    isabout = rel.endswith("About/About.xml")
    for i, ln in enumerate(txt.split("\n"), 1):
        for m in re.finditer(r'MayRequire(?:ByAnyOf)?\s*=\s*"([^"]*)"', ln):
            add(rel, i, "MayRequire", m.group(1), bool(re.match(r"\s*<Operation\b", ln)))
    for m in re.finditer(r'<Operation[^>]*Class="PatchOperationFindMod"[^>]*>.*?<mods>(.*?)</mods>', txt, re.S):
        ln = txt[: m.start(1)].count("\n") + 1
        for li in re.finditer(r"<li>\s*([^<]+?)\s*</li>", m.group(1)):
            add(rel, ln, "FindMod", li.group(1))
    if isabout:
        for tag in ("loadAfter", "loadBefore", "forceLoadAfter", "forceLoadBefore"):
            for m in re.finditer(rf"<{tag}>(.*?)</{tag}>", txt, re.S):
                ln = txt[: m.start()].count("\n") + 1
                for li in re.finditer(r"<li>\s*([^<\s]+)\s*</li>", m.group(1)):
                    add(rel, ln, tag, li.group(1))
        for m in re.finditer(r"<modDependencies(?:ByVersion)?>(.*?)</modDependencies(?:ByVersion)?>", txt, re.S):
            ln = txt[: m.start()].count("\n") + 1
            for p in re.finditer(r"<packageId>\s*([^<\s]+)\s*</packageId>", m.group(1)):
                add(rel, ln, "dependency", p.group(1))

n_ship = sum(1 for r in refs if r[3].lower() == SHIP)
probe_ok = n_ship > 0 and SHIP in defined
out = [
    f"SANITY PROBE: {len(defined)} About ids defined; {len(refs)} refs; refs naming {SHIP}: {n_ship}; "
    f"{SHIP} defined: {SHIP in defined}; probe {'OK' if probe_ok else 'FAILED'}",
    f"composed ids ({len(composed)}): " + ", ".join(sorted(composed)),
]
cls = {"COMPOSED": [], "ORPHAN_OURS": [], "ORPHAN_EXTERNAL": [], "INERT": []}
for f, ln, k, p, inert in refs:
    pl = p.lower()
    dead = pl in composed or pl not in defined
    if not dead:
        continue
    if inert:
        cls["INERT"].append((f, ln, k, p))
    elif f in composed_about:
        continue  # a composed mod's own About is never loaded
    elif pl in composed:
        cls["COMPOSED"].append((f, ln, k, p))
    elif pl.startswith("mandrake."):
        cls["ORPHAN_OURS"].append((f, ln, k, p))
    else:
        cls["ORPHAN_EXTERNAL"].append((f, ln, k, p))
for c, rows in cls.items():
    out.append(f"\n## {c}: {len(set(rows))}")
    if c == "ORPHAN_EXTERNAL":
        for p, n in Counter(r[3] for r in set(rows)).most_common():
            out.append(f"  {p}  x{n}")
    else:
        for r in sorted(set(rows)):
            out.append(f"  {r[0]}:{r[1]} [{r[2]}] {r[3]}")
text = "\n".join(out)
print(text)
(ROOT / "Transient/stillsand_dead_gate_sweep_results.txt").write_text(text + "\n")
