using System.Collections.Generic;
using RimMandrake.FlowWorks.LiquidTypes;
using RimWorld;
using UnityEngine;
using Verse;

namespace RimMandrake.FlowWorks
{
	/// <summary>FLOWWORKS_VISUAL_PRINCIPLES_1 — one liquid's surface look, DATA on its LiquidDef row (generated by
	/// Tools/generate_liquid_suite.py) or on a FluidDef with no row (oil, poison). Every field is PROVISIONAL and is
	/// judged by looking (review sheet art_source/visual_principles_2026-10-05).</summary>
	public class RM_LiquidSurfaceLook
	{
		/// <summary>Colour of the moving highlights (glints on water, gloss on tar).</summary>
		public Color highlight = new Color(0.84f, 0.91f, 0.96f);

		/// <summary>Highlight brightness, 0..1.</summary>
		public float strength = 0.35f;

		/// <summary>Cells per repeat of the ripple pattern: small = fine ripples, large = broad slow swells.</summary>
		public float scale = 2f;

		/// <summary>Drift speed, cells per second. Water ~0.45; tar, viscous, ~0.05.</summary>
		public float speed = 0.45f;

		/// <summary>Highlight sharpness: high = thin bright glints, low = soft broad gloss.</summary>
		public float sharpness = 4f;

		/// <summary>&gt; 1 elongates the ripples east-west into streaks (slicks); 1 = round.</summary>
		public float stretch = 1f;

		/// <summary>0..1 rainbow film over the gloss (oil).</summary>
		public float sheen;

		/// <summary>0..1 strength of the V-shaped wake behind anything moving through it. 0 = none (vanilla's own
		/// wading splash, <see cref="splashes"/>, is the water family's wading effect).</summary>
		public float wake;

		/// <summary>Draw the procedural glint/sheen overlay above (fields above). Off by default: the engine shader
		/// below carries the look (owner, 2026-10-05, of the overlay's drifting white specks on water:
		/// <i>"Can't we make the water just look like Shallow water?"</i>).</summary>
		public bool overlay;

		// ── engine look (RM_LiquidLooks applies these to the liquid's own terrains) ──

		/// <summary>"Water" (default): the terrain's own vanilla water shader. "Flow": the base game's slow
		/// distorting lava-flow shader, for thick liquids.</summary>
		public string shader;

		/// <summary>Surface texture (any game texture path); null = the terrain's own (vanilla's depth ramps).</summary>
		public string texture;

		/// <summary>Flow only: mask texture, white = flows. Null = all flows.</summary>
		public string mask;

		/// <summary>Surface colour multiplier. White = keep the terrain def's own &lt;color&gt;.</summary>
		public Color tint = Color.white;

		/// <summary>0..1 darkening per fill tier (trace 0, half 1, brim/deep 2): deeper reads darker.</summary>
		public float depthDarken;

		/// <summary>Flow shader parameters; negative = the shader's own default.</summary>
		public float flowSpeed = -1f, flowAmplitude = -1f, flowFrequency = -1f, brightness = -1f,
			spotScale = -1f, spotSpeed = -1f, spotMin = -1f, spotMax = -1f;

		/// <summary>Water shader ripple pass (_WaterRippleDensity / _WaterDepthIntensity, vanilla 1/1); negative = vanilla.</summary>
		public float rippleDensity = -1f, rippleIntensity = -1f;

		/// <summary>A vanilla FleckDef the surface throws now and then (vanilla's per-terrain emitter, as hot springs
		/// steam): e.g. AirPuff. Null = none.</summary>
		public string fleck;

		/// <summary>Per-cell chance per steady-effects pass of throwing <see cref="fleck"/> (hot spring 0.25).</summary>
		public float fleckChance;

		/// <summary>Vanilla's wading splash (takeSplashes). Thick liquids do not splash.</summary>
		public bool splashes = true;

		/// <summary>FLOWWORKS_REVIEW_LOOKS_ROUND_1 item 7 (owner, 2026-10-06: <i>"acid should be an eerie yellow-green and
		/// bubbling. slimes should lightly bubble too. Boiling liquid should bubble quite a bit."</i>): bubbles rising
		/// and popping, per cell per second, on cells in view. 0 = none. Slime ~0.08, acid ~0.25, boiling ~0.9.</summary>
		public float bubbles;

		/// <summary>Bubble colour (alpha kept from the fleck).</summary>
		public Color bubbleColor = new Color(0.9f, 0.95f, 1f);

		/// <summary>Item 10 (owner: <i>"show the pit walls/floor beneath the translucent water"</i>): 0..1, how much of a
		/// cut's own floor and drowned walls show through this liquid. 0 = opaque (tar, oil, slime).</summary>
		public float seeThrough;
	}

	/// <summary>
	/// FLOWWORKS_VISUAL_PRINCIPLES_1, principles 3 and 4 (owner, 2026-10-05): <i>"When filled with water it should
	/// move and act like water (ripples, V waves, etc.) not just be solid coloration."</i> and <i>"Tar should not
	/// simply be solid black … It should look like black liquid."</i>
	///
	/// The fill terrains stay vanilla water terrains (their own ramp + water-depth shader, so the filled-depth tiers
	/// keep their distinct depth reads). Over them this draws, for every visible cell whose terrain has a look, two
	/// layers of a procedural ripple texture drifting against each other in additive light — glints where they crest
	/// together — plus an optional rainbow film; and it throws a V of ripples behind anything wading through. One
	/// mesh per look, rebuilt only when the view moves or every half second; the motion itself is a material offset,
	/// so it costs one draw call per layer per frame.
	///
	/// No flow direction: the canal engine keeps no per-cell flow vector, so the drift is a standing shimmer, not a
	/// current (assumption A4). The face band of a cut is left uncovered (liquid only shows below it).
	/// Mod Settings: liquidSurfaceMotionEnabled (off: the flat vanilla-tinted look), liquidWakesEnabled.
	///
	/// FLOWWORKS_LIQUID_LOOKS_1: the overlay now draws only for a look that asks for it (<c>overlay</c>); the
	/// surface itself is an engine shader applied by RM_LiquidLooks. Wakes only where <c>wake</c> &gt; 0.
	/// </summary>
	public class RM_LiquidSurface : MapComponent
	{
		private static Dictionary<TerrainDef, RM_LiquidSurfaceLook> lookOf;
		private static readonly Dictionary<RM_LiquidSurfaceLook, Material[]> mats = new Dictionary<RM_LiquidSurfaceLook, Material[]>();

		private readonly Dictionary<RM_LiquidSurfaceLook, Mesh> meshes = new Dictionary<RM_LiquidSurfaceLook, Mesh>();
		private readonly Dictionary<RM_LiquidSurfaceLook, List<Vector3>> vbuf = new Dictionary<RM_LiquidSurfaceLook, List<Vector3>>();
		private CellRect lastView;
		private int lastBuildFrame = -999;

		public RM_LiquidSurface(Map map) : base(map)
		{
		}

		// ── which terrain wears which look ──────────────────────────────────

		public static RM_LiquidSurfaceLook LookFor(TerrainDef t)
		{
			if (t == null)
			{
				return null;
			}
			if (lookOf == null)
			{
				BuildLookTable();
			}
			return lookOf.TryGetValue(t, out RM_LiquidSurfaceLook l) ? l : null;
		}

		private static void BuildLookTable()
		{
			lookOf = new Dictionary<TerrainDef, RM_LiquidSurfaceLook>();
			foreach (FluidDef f in DefDatabase<FluidDef>.AllDefsListForReading)
			{
				if (f.surfaceLook != null)
				{
					AddFluid(f, f.surfaceLook);
				}
			}
			foreach (LiquidDef l in DefDatabase<LiquidDef>.AllDefsListForReading)
			{
				if (l.surfaceLook == null)
				{
					continue;
				}
				if (l.canalFluid != null && l.canalFluid.surfaceLook == null)
				{
					AddFluid(l.canalFluid, l.surfaceLook);
				}
				if (l.terrainSuite != null)
				{
					// never a base-game terrain: vanilla lakes and seas already animate, and a row may ADOPT them
					AddOwned(l.terrainSuite.shallow, l.surfaceLook);
					AddOwned(l.terrainSuite.chestDeep, l.surfaceLook);
					AddOwned(l.terrainSuite.deep, l.surfaceLook);
				}
			}
		}

		private static void AddFluid(FluidDef f, RM_LiquidSurfaceLook look)
		{
			Add(f.floodTerrain, look);
			Add(f.fillTerrainHalf, look);
			Add(f.fillTerrainBrim, look);
			Add(f.fillTerrainSuperdeep, look);
		}

		private static void AddOwned(TerrainDef t, RM_LiquidSurfaceLook look)
		{
			if (t != null && (t.modContentPack == null || !t.modContentPack.IsOfficialMod))
			{
				Add(t, look);
			}
		}

		private static void Add(TerrainDef t, RM_LiquidSurfaceLook look)
		{
			if (t != null && !lookOf.ContainsKey(t))
			{
				lookOf[t] = look;
			}
		}

		// ── drawing ─────────────────────────────────────────────────────────

		public override void MapComponentUpdate()
		{
			if (!RimMandrakeFlowWorksSettings.liquidSurfaceMotionEnabled || Find.CurrentMap != map || RimWorld.Planet.WorldRendererUtility.WorldRendered)
			{
				return;
			}
			CellRect view = Find.CameraDriver.CurrentViewRect.ExpandedBy(1).ClipInsideMap(map);
			if (view != lastView || Time.frameCount - lastBuildFrame > 30)
			{
				Rebuild(view);
				lastView = view;
				lastBuildFrame = Time.frameCount;
			}
			if (meshes.Count == 0)
			{
				return;
			}
			float t = Time.realtimeSinceStartup;
			float y = AltitudeLayer.TerrainScatter.AltitudeFor() + 0.01f;
			Matrix4x4 m = Matrix4x4.TRS(new Vector3(0f, y, 0f), Quaternion.identity, Vector3.one);
			foreach (KeyValuePair<RM_LiquidSurfaceLook, Mesh> kv in meshes)
			{
				RM_LiquidSurfaceLook look = kv.Key;
				Material[] lm = MatsFor(look);
				float s = look.speed / Mathf.Max(0.1f, look.scale);
				lm[0].mainTextureOffset = new Vector2(t * s * 0.5f, t * s);
				lm[1].mainTextureOffset = new Vector2(-t * s, -t * s * 0.5f);
				if (look.strength > 0f)
				{
					Graphics.DrawMesh(kv.Value, m, lm[0], 0);
					Graphics.DrawMesh(kv.Value, m, lm[1], 0);
				}
				if (lm[2] != null)
				{
					lm[2].mainTextureOffset = new Vector2(t * s * 0.3f, -t * s * 0.2f);
					Graphics.DrawMesh(kv.Value, m, lm[2], 0);
				}
			}
		}

		private void Rebuild(CellRect view)
		{
			foreach (List<Vector3> l in vbuf.Values)
			{
				l.Clear();
			}
			RM_MapComponent_Excavation eng = map.GetComponent<RM_MapComponent_Excavation>();
			TerrainGrid tg = map.terrainGrid;
			foreach (IntVec3 c in view)
			{
				RM_LiquidSurfaceLook look = LookFor(tg.TerrainAt(c));
				if (look == null || !look.overlay)
				{
					continue;
				}
				float top = 1f;
				if (eng != null && RimMandrakeFlowWorksSettings.excavationWallFacesEnabled)
				{
					int d = eng.ExcavatedDepthAt(c);
					if (d > 0)
					{
						IntVec3 n = c + IntVec3.North;
						int nd = n.InBounds(map) && !eng.IsSourceCell(n) ? eng.ExcavatedDepthAt(n) : d;
						top -= RM_WallFaceMath.NorthFaceHeight(RM_WallFaceMath.ExposedDrop(d, nd, eng.FillAt(c)));
					}
				}
				if (!vbuf.TryGetValue(look, out List<Vector3> v))
				{
					v = new List<Vector3>();
					vbuf[look] = v;
				}
				v.Add(new Vector3(c.x, 0f, c.z));
				v.Add(new Vector3(c.x, 0f, c.z + top));
				v.Add(new Vector3(c.x + 1f, 0f, c.z + top));
				v.Add(new Vector3(c.x + 1f, 0f, c.z));
			}
			meshes.Clear();
			foreach (KeyValuePair<RM_LiquidSurfaceLook, List<Vector3>> kv in vbuf)
			{
				if (kv.Value.Count == 0)
				{
					continue;
				}
				meshes[kv.Key] = BuildMesh(kv.Key, kv.Value);
			}
		}

		private readonly Dictionary<RM_LiquidSurfaceLook, Mesh> meshPool = new Dictionary<RM_LiquidSurfaceLook, Mesh>();

		private Mesh BuildMesh(RM_LiquidSurfaceLook look, List<Vector3> verts)
		{
			if (!meshPool.TryGetValue(look, out Mesh mesh) || mesh == null)
			{
				mesh = new Mesh { name = "RM_LiquidSurface" };
				meshPool[look] = mesh;
			}
			mesh.Clear();
			int n = verts.Count;
			Vector2[] uv = new Vector2[n];
			int[] tris = new int[n / 4 * 6];
			for (int i = 0; i < n; i++)
			{
				uv[i] = new Vector2(verts[i].x, verts[i].z);
			}
			for (int q = 0, k = 0; q < n; q += 4, k += 6)
			{
				tris[k] = q;
				tris[k + 1] = q + 1;
				tris[k + 2] = q + 2;
				tris[k + 3] = q;
				tris[k + 4] = q + 2;
				tris[k + 5] = q + 3;
			}
			if (n > 65000)
			{
				mesh.indexFormat = UnityEngine.Rendering.IndexFormat.UInt32;
			}
			mesh.SetVertices(verts);
			mesh.uv = uv;
			mesh.triangles = tris;
			mesh.RecalculateBounds();
			return mesh;
		}

		/// <summary>Two ripple layers (different scales so they never line up) and an optional rainbow film.</summary>
		private static Material[] MatsFor(RM_LiquidSurfaceLook look)
		{
			if (mats.TryGetValue(look, out Material[] m) && m[0] != null)
			{
				return m;
			}
			Texture2D tex = RippleTexture(look);
			Color c = look.highlight * Mathf.Clamp01(look.strength);
			c.a = 1f;
			m = new Material[3];
			for (int i = 0; i < 2; i++)
			{
				m[i] = new Material(MaterialPool.MatFrom(new MaterialRequest(tex, ShaderDatabase.MoteGlow)))
				{
					mainTexture = tex,
					color = c,
					mainTextureScale = Vector2.one / Mathf.Max(0.25f, look.scale * (i == 0 ? 1f : 0.73f))
				};
			}
			if (look.sheen > 0f)
			{
				Texture2D rb = RainbowTexture(look);
				m[2] = new Material(MaterialPool.MatFrom(new MaterialRequest(rb, ShaderDatabase.MoteGlow)))
				{
					mainTexture = rb,
					color = new Color(1f, 1f, 1f, 1f) * Mathf.Clamp01(look.sheen * 0.35f),
					mainTextureScale = Vector2.one / Mathf.Max(0.25f, look.scale * 1.3f)
				};
			}
			mats[look] = m;
			return m;
		}

		/// <summary>Tileable smooth value noise in 0..1 on a gx × gy lattice, sampled at (u, v) in lattice units.</summary>
		private static float Noise(float[,] g, int gx, int gy, float u, float v)
		{
			int x0 = Mathf.FloorToInt(u), y0 = Mathf.FloorToInt(v);
			float fx = u - x0, fy = v - y0;
			fx = fx * fx * (3f - 2f * fx);
			fy = fy * fy * (3f - 2f * fy);
			int xa = ((x0 % gx) + gx) % gx, xb = (xa + 1) % gx;
			int ya = ((y0 % gy) + gy) % gy, yb = (ya + 1) % gy;
			float a = Mathf.Lerp(g[xa, ya], g[xb, ya], fx);
			float b = Mathf.Lerp(g[xa, yb], g[xb, yb], fx);
			return Mathf.Lerp(a, b, fy);
		}

		private static float[,] Lattice(int gx, int gy, int seed)
		{
			System.Random r = new System.Random(seed);
			float[,] g = new float[gx, gy];
			for (int x = 0; x < gx; x++)
			{
				for (int y = 0; y < gy; y++)
				{
					g[x, y] = (float)r.NextDouble();
				}
			}
			return g;
		}

		private static Texture2D RippleTexture(RM_LiquidSurfaceLook look)
		{
			const int N = 128;
			int gx = 8;
			int gy = Mathf.Clamp(Mathf.RoundToInt(8f * look.stretch), 2, 32);
			float[,] g1 = Lattice(gx, gy, 11);
			float[,] g2 = Lattice(gx * 2, gy * 2, 23);
			Texture2D t = new Texture2D(N, N, TextureFormat.RGBA32, true) { wrapMode = TextureWrapMode.Repeat, filterMode = FilterMode.Bilinear };
			for (int y = 0; y < N; y++)
			{
				for (int x = 0; x < N; x++)
				{
					float n = 0.7f * Noise(g1, gx, gy, x * gx / (float)N, y * gy / (float)N)
						+ 0.3f * Noise(g2, gx * 2, gy * 2, x * gx * 2 / (float)N, y * gy * 2 / (float)N);
					float h = Mathf.Pow(Mathf.Clamp01((n - 0.5f) * 2.2f), Mathf.Max(0.5f, look.sharpness));
					t.SetPixel(x, y, new Color(h, h, h, h));
				}
			}
			t.Apply(true, true);
			return t;
		}

		private static Texture2D RainbowTexture(RM_LiquidSurfaceLook look)
		{
			const int N = 64;
			float[,] g = Lattice(6, 6, 37);
			Texture2D t = new Texture2D(N, N, TextureFormat.RGBA32, true) { wrapMode = TextureWrapMode.Repeat, filterMode = FilterMode.Bilinear };
			for (int y = 0; y < N; y++)
			{
				for (int x = 0; x < N; x++)
				{
					float hue = Noise(g, 6, 6, x * 6f / N, y * 6f / N) * 2.5f % 1f;
					Color c = Color.HSVToRGB(hue, 0.65f, 0.9f);
					t.SetPixel(x, y, c);
				}
			}
			t.Apply(true, true);
			return t;
		}

		// ── V wakes ─────────────────────────────────────────────────────────

		public override void MapComponentTick()
		{
			if (Find.CurrentMap != map)
			{
				return;
			}
			if (RimMandrakeFlowWorksSettings.liquidBubblesEnabled)
			{
				Bubbles();
			}
			if (!RimMandrakeFlowWorksSettings.liquidWakesEnabled || Find.TickManager.TicksGame % 12 != 0)
			{
				return;
			}
			foreach (Pawn p in map.mapPawns.AllPawnsSpawned)
			{
				if (p.Flying || p.pather == null || !p.pather.Moving)
				{
					continue;
				}
				RM_LiquidSurfaceLook look = LookFor(map.terrainGrid.TerrainAt(p.Position));
				if (look == null || look.wake <= 0f)
				{
					continue;
				}
				IntVec3 to = p.pather.nextCell;
				if (!to.IsValid)
				{
					continue;
				}
				float dx = to.x - p.Position.x, dz = to.z - p.Position.z;
				if (dx == 0f && dz == 0f)
				{
					continue;
				}
				float heading = Mathf.Atan2(dx, dz) * Mathf.Rad2Deg;   // 0 = north, clockwise
				Vector3 at = p.DrawPos.WithY(AltitudeLayer.MoteLow.AltitudeFor());
				if (!at.ShouldSpawnMotesAt(map))
				{
					continue;
				}
				float size = Mathf.Clamp(p.BodySize, 0.5f, 2f) * 0.35f;
				for (int side = -1; side <= 1; side += 2)
				{
					map.flecks.CreateFleck(new FleckCreationData
					{
						def = FleckDefOf.WaterRipple,
						spawnPosition = at,
						scale = size,
						velocityAngle = heading + 180f + side * 38f,
						velocitySpeed = 0.55f * look.wake,
						ageTicksOverride = -1
					});
				}
			}
		}

		// ── bubbles (FLOWWORKS_REVIEW_LOOKS_ROUND_1 item 7) ─────────────────

		private const int BubbleSamples = 16;
		private static FleckDef bubbleFleck;

		/// <summary>Owner, 2026-10-06: <i>"acid should be an eerie yellow-green and bubbling. slimes should lightly bubble
		/// too. Boiling liquid should bubble quite a bit."</i> Vanilla's per-terrain emitter visits a cell about once every
		/// 28 s, far too rare to read as bubbling, so this samples cells IN VIEW each tick (cost bounded by the sample
		/// count at any zoom, density proportional to how much of the view is bubbling liquid — the same shape as
		/// EnvironmentalHazards' water agitation). A bubble is RM_Fleck_LiquidBubble (Biotech's vat bubble, tinted per
		/// liquid); a heavy boil also pops a vanilla water ripple now and then.</summary>
		private void Bubbles()
		{
			if (bubbleFleck == null)
			{
				bubbleFleck = DefDatabase<FleckDef>.GetNamedSilentFail("RM_Fleck_LiquidBubble");
				if (bubbleFleck == null)
				{
					return;
				}
			}
			CellRect view = Find.CameraDriver.CurrentViewRect.ClipInsideMap(map);
			int area = view.Area;
			if (area <= 0)
			{
				return;
			}
			int represented = Mathf.Max(1, area / BubbleSamples);
			TerrainGrid tg = map.terrainGrid;
			for (int i = 0; i < BubbleSamples; i++)
			{
				IntVec3 c = view.RandomCell;
				RM_LiquidSurfaceLook look = LookFor(tg.TerrainAt(c));
				if (look == null || look.bubbles <= 0f)
				{
					continue;
				}
				int n = RM_LiquidLookMath.BubblesThisTick(look.bubbles, RimMandrakeFlowWorksSettings.liquidBubbleDensity,
					represented, Rand.Value);
				for (int k = 0; k < n; k++)
				{
					Vector3 at = new Vector3(c.x + Rand.Range(0.15f, 0.85f), AltitudeLayer.MoteLow.AltitudeFor(), c.z + Rand.Range(0.15f, 0.85f));
					if (!at.ShouldSpawnMotesAt(map))
					{
						continue;
					}
					FleckCreationData d = FleckMaker.GetDataStatic(at, map, bubbleFleck, Rand.Range(0.8f, 1.8f));
					d.instanceColor = look.bubbleColor;
					d.velocityAngle = Rand.Range(0f, 360f);
					d.velocitySpeed = Rand.Range(0f, 0.08f);
					map.flecks.CreateFleck(d);
					if (look.bubbles >= 0.5f && Rand.Chance(0.25f))
					{
						FleckMaker.WaterRipple(at, map, Rand.Range(0.25f, 0.5f));
					}
				}
			}
		}
	}
}
