#!/usr/bin/env python3
"""Measure where a relay hose meets the 2x2 hose reel's drawn outline, per look and per art (stored / deployed), and
write src/RimMandrake/GimmeSomeSlack/Source/Hose/ReelIntakeGeometry.cs (Verse-free, selftested).

Owner, station 42 (2026-10-04): "pipe does NOT hook up properly to the next reel station". The round-6 hose ended on the
midpoint of the intake cell's shared edge, which on the west side is 0.45 cell below the art's one brass inlet and 0.29
cell inside its face, and on the north/south sides leaves bare ground between the edge and the drawn reel.

Rule measured here (alpha > 128, the reel drawn at drawSize 2.8 centred on the footprint, canvas 256):
  * WEST: the art's brass inlet (rows whose leftmost opaque pixel is u < 20): the hose's coupling face meets the inlet face,
    both west intake cells go to it.
  * EAST / NORTH / SOUTH, per edge cell: along that cell's half of the edge (cell centre +-0.45, 0.05..0.8 from the edge's middle), the line where the drawn
    outline lies closest to the footprint edge (median of a +-0.12-cell band, so a one-pixel spur cannot win); ties go to
    the cell centre. The hose's coupling face meets the outline there.
Depth = outline position minus the footprint edge along the outward normal (cells; + = outside the edge).

Run: python3 src/RimMandrake/Utils/mockups/messy_conduit/reel_intake_geometry.py   (rewrites the .cs; deterministic)
"""
import os
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", ".."))
MOD = os.path.join(REPO, "src", "RimMandrake", "MessyConduit")
TEX = os.path.join(MOD, "Textures", "RimMandrake", "MessyConduit", "Hose")
OUT = os.path.join(MOD, "Source", "Hose", "ReelIntakeGeometry.cs")
LOOKS = [("Scrapper", ""), ("Industrial", "Styles/Industrial/"), ("Modern", "Styles/Modern/"), ("Futuristic", "Styles/Futuristic/")]
ARTS = ["Reel_PumpHookup", "Reel_Deployed"]   # index 0 = stored (hose reeled in), 1 = deployed (hose laid)
DRAW = 2.8
BAND = 0.12


def outline(a, side, perp):
    """Outline coordinate (cells from the footprint centre along the outward normal) on the line at `perp`."""
    n = a.shape[0]
    px = int(round(BAND / DRAW * n))
    hits = []
    for b in range(-px, px + 1):
        if side in "EW":
            v = int(round(n / 2 - perp / DRAW * n)) + b
            idx = np.nonzero(a[v])[0]
            if not len(idx):
                continue
            hits.append(((idx[-1] + 1) - n / 2) / n * DRAW if side == "E" else (n / 2 - idx[0]) / n * DRAW)
        else:
            u = int(round(n / 2 + perp / DRAW * n)) + b
            idx = np.nonzero(a[:, u])[0]
            if not len(idx):
                continue
            hits.append((n / 2 - idx[0]) / n * DRAW if side == "N" else ((idx[-1] + 1) - n / 2) / n * DRAW)
    return float(np.median(hits)) if hits else None


def measure(path):
    a = np.array(Image.open(path).convert("RGBA"))[..., 3] > 128
    n = a.shape[0]
    rows = [v for v in range(n) if a[v].any() and np.nonzero(a[v])[0][0] < 20]
    vc = (rows[0] + rows[-1]) / 2.0
    face = float(np.median([np.nonzero(a[v])[0][0] for v in rows]))
    inlet = ((n / 2 - vc) / n * DRAW, (n / 2 - face) / n * DRAW - 1.0)   # (perp dz, depth beyond the west edge)
    out = {}
    for side in "ENS":
        for k, centre in enumerate((-0.5, 0.5)):   # edge cell 0 = lower x / z, 1 = higher
            best = None
            steps = int(round(0.45 / DRAW * n))
            for s in range(-steps, steps + 1):
                perp = centre + s / n * DRAW
                if abs(perp) > 0.8 or abs(perp) < 0.05:
                    continue   # keep the coupling (~0.5 wide) off the footprint corner and off the other cell's half
                o = outline(a, side, perp)
                if o is None:
                    continue
                d = o - 1.0
                score = abs(d) + 0.05 * abs(perp - centre)
                if best is None or score < best[0] - 1e-9:
                    best = (score, perp, d)
            out[(side, k)] = (best[1], best[2])
    return inlet, out


def main():
    lines = []
    for li, (look, folder) in enumerate(LOOKS):
        for ai, art in enumerate(ARTS):
            inlet, out = measure(os.path.join(TEX, folder + art + ".png"))
            row = [inlet[0], inlet[1]]
            for side in "ENS":
                for k in range(2):
                    row += list(out[(side, k)])
            lines.append("            { " + ", ".join("%.3f" % x for x in row) + " },   // " + look + " " + art)
    cs = '''using System;
using RimMandrake.GimmeSomeSlack.Core;

namespace RimMandrake.GimmeSomeSlack.Hose
{
    /// <summary>
    /// GENERATED by src/RimMandrake/Utils/mockups/messy_conduit/reel_intake_geometry.py from the reel art (all four looks,
    /// stored Reel_PumpHookup and laid Reel_Deployed, drawSize 2.8). Do not hand-edit: re-run the script.
    /// Owner, station 42 (2026-10-04): "pipe does NOT hook up properly to the next reel station". Where a relay hose's
    /// coupling face meets the drawn reel, per approach side, in cells from the 2x2 footprint centre:
    ///   row = { westInletDz, westInletDepth, E0 perp, E0 depth, E1 perp, E1 depth, N0.., N1.., S0.., S1.. }
    /// perp = offset along the edge from the footprint centre (x for N/S, z for E); depth = outline minus the footprint edge
    /// along the outward normal (+ = outside). West: the art's one brass inlet (both west cells couple to it).
    /// </summary>
    public static class ReelIntakeGeometry
    {
        public static readonly string[] Looks = { "Scrapper", "Industrial", "Modern", "Futuristic" };

        private static readonly double[,] table =
        {
''' + "\n".join(lines) + '''
        };

        public static int LookIndex(string look)
        {
            int i = Array.IndexOf(Looks, look);
            return i < 0 ? 0 : i;
        }

        private static int Row(string look, bool deployed) => LookIndex(look) * 2 + (deployed ? 1 : 0);

        /// <summary>The west inlet: (dz from the footprint centre, depth beyond the west edge).</summary>
        public static void WestInlet(string look, bool deployed, out double dz, out double depth)
        {
            int r = Row(look, deployed);
            dz = table[r, 0];
            depth = table[r, 1];
        }

        /// <summary>side 0 = E, 1 = N, 2 = S; cell 0 = the lower-coordinate edge cell, 1 = the higher.</summary>
        public static void Edge(string look, bool deployed, int side, int cell, out double perp, out double depth)
        {
            int r = Row(look, deployed), c = 2 + (side * 2 + cell) * 2;
            perp = table[r, c];
            depth = table[r, c + 1];
        }

        public const int RowCount = 8;
    }
}
'''
    with open(OUT, "w", newline="\n") as f:
        f.write(cs)
    print("wrote", OUT)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
