"""wire_pole_art.py -- per-look power pole art into MessyConduit (owner review 2026-10-04 B6/B16/B19).

    python3 src/RimMandrake/Utils/mockups/messy_conduit/wire_pole_art.py            # wire every landed render, regen table
    python3 src/RimMandrake/Utils/mockups/messy_conduit/wire_pole_art.py --check    # exit 1 if the table is stale

Artpipe jobs messyconduit_{mast,lampmast}_{scrapper,industrial,modern,futuristic}_v1 render a 128x512 transparent pole,
base at the bottom, drawn by the defs at drawSize (1,4) with drawOffset (0,0,1.5): pixel row r (0 = top) sits at
z = 3.5 - r/128 cells above the cell centre. For each landed render this
  * copies it to Textures/RimMandrake/MessyConduit/Aerial/Styles/<Look>/<AerialMast|AerialLampMast>.png,
  * CROPS its top 128 rows into <...>Top.png (the overlay drawn above pawns; same pixels, so alignment is exact),
    which the code draws as a 1x1 plane centred at topOffsetZ = 3.5 - 64/128 = 3.0,
  * MEASURES the crossarm: the widest opaque row in the top 30% of the canvas -> attachZ = 3.5 - row/128,
  * regenerates Source/Aerial/PoleGeometryTable.cs (AerialMaterials.PoleGeometry) with those numbers.
A render is refused (left unwired) unless it is 128x512 with real alpha (>= 5% and <= 70% opaque). The judging by
eye happens before this runs; this is the mechanical wiring only.
"""
import glob
import json
import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", "..", ".."))
MOD = os.path.join(REPO, "src", "RimMandrake", "MessyConduit")
STY = os.path.join(MOD, "Textures", "RimMandrake", "MessyConduit", "Aerial", "Styles")
TABLE = os.path.join(MOD, "Source", "Aerial", "PoleGeometryTable.cs")
ARTPIPE = "/mnt/d/Luke/dev/_artpipe"
LOOKS = {"scrapper": "Scrapper", "industrial": "Industrial", "modern": "Modern", "futuristic": "Futuristic"}
KINDS = {"mast": ("AerialMast", "RM_AerialMast"), "lampmast": ("AerialLampMast", "RM_AerialLampMast")}
W, H = 128, 512


def find_render(job):
    """The PNG of a done job (done/<job>.manifest.json present): _artsrc/<job>/<job>.png, the daemon's output."""
    for p in (os.path.join(ARTPIPE, "done", job + ".json"),):
        if os.path.exists(p):
            try:
                d = json.load(open(p, encoding="utf-8"))
            except Exception:
                d = {}
            for k in ("output", "out", "png", "result", "final", "path"):
                v = d.get(k)
                if isinstance(v, str) and v.lower().endswith(".png"):
                    v = v.replace("D:\\", "/mnt/d/").replace("\\", "/")
                    if os.path.exists(v):
                        return v
    if not os.path.exists(os.path.join(ARTPIPE, "done", job + ".manifest.json")):
        return None                       # not finished (pending/ or running): never wire a half-written file
    hits = sorted(glob.glob(os.path.join(ARTPIPE, "_artsrc", job, job + ".png")) + glob.glob(os.path.join(ARTPIPE, "_artsrc", job + "*.png")))
    return hits[-1] if hits else None


def measure(im):
    a = im.getchannel("A")
    best, row = -1, None
    for r in range(int(H * 0.30)):
        n = sum(1 for x in range(W) if a.getpixel((x, r)) > 128)
        if n > best:
            best, row = n, r
    return row, best


def sane(im):
    if im.size != (W, H):
        return "size %s, want %dx%d" % (im.size, W, H)
    a = list(im.getchannel("A").getdata())
    frac = sum(1 for v in a if v > 128) / float(len(a))
    if not 0.05 <= frac <= 0.70:
        return "opaque fraction %.2f outside 0.05-0.70 (no real alpha?)" % frac
    return None


def table_src(rows):
    body = "\n".join('            d["%s/%s"] = new Vector2(%.3ff, %.3ff);   // crossarm row %d of 512' % r for r in rows)
    return '''// GENERATED by src/RimMandrake/Utils/mockups/messy_conduit/wire_pole_art.py -- do not edit by hand.
// Per-look pole geometry measured from each look's own 128x512 render (attachZ, topOffsetZ; cells above the cell centre).
using System.Collections.Generic;
using UnityEngine;

namespace RimMandrake.MessyConduit.Aerial
{
    public static class PoleGeometryTable
    {
        public static Dictionary<string, Vector2> Build()
        {
            var d = new Dictionary<string, Vector2>();
%s
            return d;
        }
    }
}
''' % body


def main(argv):
    check = "--check" in argv
    rows, notes = [], []
    for look_k, look in LOOKS.items():
        for kind_k, (base, defn) in KINDS.items():
            dst = os.path.join(STY, look, base + ".png")
            src = None if check else find_render("messyconduit_%s_%s_v1" % (kind_k, look_k))
            if src:
                im = Image.open(src).convert("RGBA")
                why = sane(im)
                if why:
                    notes.append("REFUSED %s/%s: %s (%s)" % (look, base, why, src))
                    src = None
                else:
                    os.makedirs(os.path.dirname(dst), exist_ok=True)
                    im.save(dst)
                    im.crop((0, 0, W, 128)).save(os.path.join(STY, look, base + "Top.png"))
            if os.path.exists(dst):
                im = Image.open(dst).convert("RGBA")
                row, width = measure(im)
                rows.append((look, defn, 3.5 - row / 128.0, 3.0, row))
                notes.append("%s/%s: crossarm row %d (%d px wide) -> attachZ %.2f%s" % (look, base, row, width, 3.5 - row / 128.0, "" if src or check else " (already wired)"))
            else:
                notes.append("%s/%s: no render yet (stand-in tint stays)" % (look, base))
    src = table_src(rows)
    if check:
        cur = open(TABLE, encoding="utf-8").read() if os.path.exists(TABLE) else ""
        print("\n".join(notes))
        print("pole geometry table %s" % ("current" if cur == src else "STALE"))
        return 0 if cur == src else 1
    with open(TABLE, "w", encoding="utf-8", newline="\n") as f:
        f.write(src)
    print("\n".join(notes))
    print("wrote %s (%d looks/defs measured)" % (TABLE, len(rows)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
