using System.Collections.Generic;
using RimWorld;
using UnityEngine;
using Verse;

namespace RimMandrake.TerminalBiomes
{
    // TWILIGHT_LIGHT_ECONOMY_1 §1. The one clock this whole layer runs on.
    // "the ledger is the clock; the gardener is the hand that moves it" —
    // AdvanceWell(...) is the single code path every drift trigger calls
    // (base aging inside MapComponentTick, a gardener-pass beat via
    // NotifyGardenerPassAdvance(), and lid-dark's forced dawn check via
    // NotifyLidDarkEnded()). RM_GardenerOverhead/RM_PassingShadow and the
    // lid-dark WeatherDef itself are NOT built here — the content/danger
    // passes own them (§5, §7 table) — this class only exposes the hooks
    // they call once they exist.
    //
    // A plain MapComponent (not CustomMapComponent), so it auto-attaches to
    // EVERY map per Verse.Map.FillComponents, including the Twilight Sea
    // floor pocket map generated by mandrake.rm.divinginteraction's
    // RM_SeaDiveGenerator_TwilightSea (biome RM_TwilightSea, same defName as
    // the surface tile) — without editing that mod's MapGeneratorDef, which
    // is out of this build's scope (TerminalBiomes only). IsActiveHere()
    // gates every real method to that one biome + Mod Settings, so the
    // component is a harmless no-op everywhere else.
    //
    // 🔴 THE ENGINE TRAP (spec §1.4): every visual effect below is a
    // GLOW-GRID change (CompGlower radius/color on the RM_Skylight thing),
    // never a sky-darkening GameCondition — cached plant growth rates assume
    // surface sunlight and would leave kelp/mat-roof growing in the black.
    public class RM_MapComponent_WellLedger : MapComponent
    {
        private const int TickInterval = 250; // rare-tick cadence; nothing here needs finer.
        private const int TicksPerDay = 60000;
        private const int OpeningTicks = TicksPerDay / 2; // ~half a day
        private const int WaningTicks = (int)(TicksPerDay * 1.5f); // the last ~1.5 days
        private const float WaningStepFraction = 0.2f; // radius steps down ~20% per half-day
        private const int WaningStepTicks = TicksPerDay / 2;

        private static readonly ColorInt GoldGlow = new ColorInt(255, 210, 120, 0);
        private static readonly ColorInt CoolDeadGlow = new ColorInt(120, 140, 150, 0);

        public enum WellStage
        {
            Opening,
            Standing,
            Waning,
            Closed,
        }

        // IExposable rather than a struct: Scribe_Collections needs a
        // reference type to round-trip a List<WellRecord> cleanly.
        public class WellRecord : IExposable
        {
            public int id;
            public IntVec3 position;
            public WellStage stage = WellStage.Opening;
            public int ageTicks;
            public int lifespanTicks;
            public bool warningLetterFired;
            public int noiseSeed;
            public Thing skylightThing; // the RM_Skylight thing, Scribe_References'd

            public void ExposeData()
            {
                Scribe_Values.Look(ref id, "id");
                Scribe_Values.Look(ref position, "position");
                Scribe_Values.Look(ref stage, "stage", WellStage.Standing);
                Scribe_Values.Look(ref ageTicks, "ageTicks");
                Scribe_Values.Look(ref lifespanTicks, "lifespanTicks");
                Scribe_Values.Look(ref warningLetterFired, "warningLetterFired");
                Scribe_Values.Look(ref noiseSeed, "noiseSeed");
                Scribe_References.Look(ref skylightThing, "skylightThing");
            }

            public int TicksRemaining => System.Math.Max(0, lifespanTicks - ageTicks);
        }

        private List<WellRecord> wells = new List<WellRecord>();
        private int nextWellId = 1;
        private bool initialized;

        // A day scheduled to open a fresh well after one closes (§1.1: "a
        // well closing schedules a well opening elsewhere within ~a day").
        private List<int> pendingOpenTicks = new List<int>();

        public RM_MapComponent_WellLedger(Map map) : base(map)
        {
        }

        public static RM_MapComponent_WellLedger GetFor(Map map)
        {
            return map?.GetComponent<RM_MapComponent_WellLedger>();
        }

        private bool IsActiveHere()
        {
            return RM_TerminalBiomesSettings.TwilightWellDriftActive
                && map.Biome != null
                && map.Biome.defName == "RM_TwilightSea";
        }

        public override void ExposeData()
        {
            base.ExposeData();
            Scribe_Collections.Look(ref wells, "wells", LookMode.Deep);
            Scribe_Values.Look(ref nextWellId, "nextWellId", 1);
            Scribe_Values.Look(ref initialized, "initialized");
            Scribe_Collections.Look(ref pendingOpenTicks, "pendingOpenTicks", LookMode.Value);
            if (wells == null) wells = new List<WellRecord>();
            if (pendingOpenTicks == null) pendingOpenTicks = new List<int>();
        }

        public override void MapComponentTick()
        {
            if (!IsActiveHere())
            {
                return;
            }
            if (!map.IsHashIntervalTick(TickInterval))
            {
                return;
            }

            if (!initialized)
            {
                InitializeWells();
                initialized = true;
                return;
            }

            ProcessPendingOpens();

            if (RM_TerminalBiomesSettings.twilightDriftCadence == 0)
            {
                return; // Frozen — sandbox, wells never age.
            }

            // Iterate a snapshot: AdvanceWell can remove/replace records.
            List<WellRecord> snapshot = new List<WellRecord>(wells);
            foreach (WellRecord well in snapshot)
            {
                AgeAndCheck(well, TickInterval);
            }
        }

        // ── Sizing & init ───────────────────────────────────────────────

        private int TargetWellCount()
        {
            // Heuristic (no ruling gives an exact formula): bigger maps
            // support more standing wells at once. 3-6, per spec §1.1.
            int bySize = 3 + map.Size.x / 125;
            return Mathf.Clamp(bySize, 3, 6);
        }

        private void InitializeWells()
        {
            int target = TargetWellCount();
            for (int i = 0; i < target; i++)
            {
                IntVec3 cell = FindWellSiteCell();
                if (!cell.IsValid)
                {
                    continue;
                }
                WellRecord well = OpenNewWell(cell);
                // Stagger initial wells across their lifespan so they don't
                // all wane in lockstep on a fresh map.
                well.ageTicks = Rand.Range(0, well.lifespanTicks - WaningTicks);
                RecomputeStage(well);
                ApplyVisualState(well);
            }
        }

        private WellRecord OpenNewWell(IntVec3 cell)
        {
            // twilightDriftCadence: 0 = frozen (aging itself is gated off in
            // MapComponentTick, not here), 1 = week (shipped, the base
            // 5-9 day roll), 2 = slow — roughly double the week.
            int cadenceMultiplier = RM_TerminalBiomesSettings.twilightDriftCadence == 2 ? 2 : 1;
            WellRecord well = new WellRecord
            {
                id = nextWellId++,
                position = cell,
                stage = WellStage.Opening,
                ageTicks = 0,
                lifespanTicks = Rand.RangeInclusive(5, 9) * TicksPerDay * cadenceMultiplier,
                noiseSeed = Rand.Range(0, 1000000),
            };
            well.skylightThing = SpawnSkylight(cell);
            wells.Add(well);
            return well;
        }

        private Thing SpawnSkylight(IntVec3 cell)
        {
            ThingDef def = DefDatabase<ThingDef>.GetNamedSilentFail("RM_Skylight");
            if (def == null || !cell.IsValid)
            {
                return null; // def missing (mod list mismatch) — ledger degrades to invisible bookkeeping, never crashes.
            }
            Thing thing = ThingMaker.MakeThing(def);
            GenSpawn.Spawn(thing, cell, map);
            return thing;
        }

        // ── Siting ──────────────────────────────────────────────────────

        private IntVec3 FindWellSiteCell()
        {
            // "on high dry ground, never on a channel bed" — this floor map
            // (GenStep_SeaFloorTerrain) is currently one uniform sediment
            // terrain with no elevation or channel-bed distinction yet, so
            // "high dry ground" has nothing to select against today. The
            // RM_ChannelBed tag check below is forward-compatible: it costs
            // nothing now and honours the siting rule the day a channel
            // terrain exists (the bank-works/current work, §2.3, out of
            // this item's scope).
            for (int attempt = 0; attempt < 60; attempt++)
            {
                IntVec3 candidate = CellFinderLoose.RandomCellWith(
                    c => c.InBounds(map) && c.Standable(map) && !IsChannelBed(c) && FarFromOtherWells(c, 8),
                    map,
                    200);
                if (candidate.IsValid)
                {
                    return candidate;
                }
            }
            return IntVec3.Invalid;
        }

        private bool IsChannelBed(IntVec3 c)
        {
            TerrainDef terrain = c.GetTerrain(map);
            return terrain != null && terrain.tags != null && terrain.tags.Contains("RM_ChannelBed");
        }

        private bool FarFromOtherWells(IntVec3 c, int minDist)
        {
            foreach (WellRecord w in wells)
            {
                if (w.stage != WellStage.Closed && c.DistanceTo(w.position) < minDist)
                {
                    return false;
                }
            }
            return true;
        }

        // ── Aging & stage transitions ───────────────────────────────────

        private void AgeAndCheck(WellRecord well, int deltaTicks)
        {
            if (well.stage == WellStage.Closed)
            {
                return;
            }
            well.ageTicks += deltaTicks;
            WellStage before = well.stage;
            RecomputeStage(well);

            if (before != WellStage.Waning && well.stage == WellStage.Waning)
            {
                well.warningLetterFired = false;
                MaybeFireWarningLetter(well);
            }
            // Opening ramps the radius UP (factor = ageTicks/OpeningTicks)
            // and Waning steps it DOWN — both need a continuous update, not
            // just Waning, or an opening well sits at whatever its very
            // first (or last-authored) radius happened to be for days.
            if (well.stage == WellStage.Opening || well.stage == WellStage.Waning)
            {
                ApplyVisualState(well);
            }
            else if (before == WellStage.Opening && well.stage == WellStage.Standing)
            {
                ApplyVisualState(well); // snap the ramp to exactly full (factor 1) on entry, once.
            }
            if (before != WellStage.Closed && well.stage == WellStage.Closed)
            {
                CloseWell(well);
                wells.Remove(well); // dead history — nothing keys off a closed WellRecord past this point.
            }
        }

        private void RecomputeStage(WellRecord well)
        {
            int remaining = well.lifespanTicks - well.ageTicks;
            if (well.ageTicks < OpeningTicks)
            {
                well.stage = WellStage.Opening;
            }
            else if (remaining <= 0)
            {
                well.stage = WellStage.Closed;
            }
            else if (remaining <= WaningTicks)
            {
                well.stage = WellStage.Waning;
            }
            else
            {
                well.stage = WellStage.Standing;
            }
        }

        private void CloseWell(WellRecord well)
        {
            if (well.skylightThing != null && well.skylightThing.Spawned)
            {
                well.skylightThing.Destroy(DestroyMode.Vanish);
            }
            well.skylightThing = null;

            // Schedule a replacement opening elsewhere "within ~a day".
            pendingOpenTicks.Add(Find.TickManager.TicksGame + Rand.Range(0, TicksPerDay));
        }

        private void ProcessPendingOpens()
        {
            if (pendingOpenTicks.Count == 0)
            {
                return;
            }
            int now = Find.TickManager.TicksGame;
            for (int i = pendingOpenTicks.Count - 1; i >= 0; i--)
            {
                if (now < pendingOpenTicks[i])
                {
                    continue;
                }
                IntVec3 cell = FindWellSiteCell();
                if (cell.IsValid)
                {
                    OpenNewWell(cell);
                }
                pendingOpenTicks.RemoveAt(i);
            }
        }

        // ── Visuals: the one place §1.4's engine trap is honoured ───────

        private void ApplyVisualState(WellRecord well)
        {
            if (well.skylightThing == null || !well.skylightThing.Spawned)
            {
                return;
            }
            CompGlower glower = well.skylightThing.TryGetComp<CompGlower>();
            if (glower == null)
            {
                return;
            }

            float factor;
            ColorInt color;
            switch (well.stage)
            {
                case WellStage.Opening:
                    factor = Mathf.Clamp01((float)well.ageTicks / OpeningTicks);
                    color = GoldGlow;
                    break;
                case WellStage.Waning:
                    int ticksIntoWaning = WaningTicks - (well.lifespanTicks - well.ageTicks);
                    int stepIndex = Mathf.Clamp(ticksIntoWaning / WaningStepTicks, 0, 3);
                    factor = Mathf.Max(0.2f, 1f - WaningStepFraction * stepIndex);
                    color = ColorIntLerp(GoldGlow, CoolDeadGlow, stepIndex / 3f);
                    break;
                case WellStage.Standing:
                default:
                    factor = 1f;
                    color = GoldGlow;
                    break;
            }

            float baseRadius = 6f; // §3.1's sun-sphere uses ~6 as its ceiling; a full well matches it.
            float newRadius = Mathf.Max(0.5f, baseRadius * factor);
            glower.GlowColor = color;
            if (!Mathf.Approximately(newRadius, glower.GlowRadius))
            {
                glower.GlowRadius = newRadius;
                glower.ForceRegister(map);
            }
        }

        private static ColorInt ColorIntLerp(ColorInt a, ColorInt b, float t)
        {
            Color ca = a.ToColor;
            Color cb = b.ToColor;
            return new ColorInt(Color.Lerp(ca, cb, Mathf.Clamp01(t)));
        }

        // ── Warning letters (spec §1.2.2: positional, ownership-gated) ──

        private void MaybeFireWarningLetter(WellRecord well)
        {
            if (well.warningLetterFired)
            {
                return;
            }
            if (!AnyPlayerOwnedThingNear(well.position, 6))
            {
                return; // "No spam for wells the player never touched."
            }
            well.warningLetterFired = true;
            Find.LetterStack.ReceiveLetter(
                "RM_TwilightWellClosingLabel".Translate(),
                "RM_TwilightWellClosingText".Translate(),
                LetterDefOf.NeutralEvent,
                new TargetInfo(well.position, map));
        }

        private bool AnyPlayerOwnedThingNear(IntVec3 pos, int radius)
        {
            List<Thing> things = map.listerThings.AllThings;
            for (int i = 0; i < things.Count; i++)
            {
                Thing t = things[i];
                if (t.Faction == Faction.OfPlayer && t.Position.DistanceTo(pos) <= radius)
                {
                    return true;
                }
            }
            return false;
        }

        // ── Gardener/lid-dark hooks (called by RM_GardenerOverhead / the
        // lid-dark WeatherDef once those ship — content/danger pass scope,
        // §5/§7. Safe to call today: they simply have no caller yet.) ────

        // "on a fraction of passes the sequence's beat 2-4 window ADVANCES
        // one well: a waning well closes now, or a scheduled opening
        // happens now" (§1.3).
        public void NotifyGardenerPassAdvance()
        {
            if (!IsActiveHere() || wells.Count == 0)
            {
                return;
            }
            WellRecord candidate = null;
            foreach (WellRecord w in wells)
            {
                if (w.stage == WellStage.Waning && (candidate == null || w.TicksRemaining < candidate.TicksRemaining))
                {
                    candidate = w;
                }
            }
            if (candidate != null)
            {
                candidate.ageTicks = candidate.lifespanTicks; // force closed now
                AgeAndCheck(candidate, 0);
                return;
            }
            // No waning well to close early — land a scheduled opening now instead.
            if (pendingOpenTicks.Count > 0)
            {
                pendingOpenTicks[0] = Find.TickManager.TicksGame;
                ProcessPendingOpens();
            }
        }

        // "the ledger runs one forced drift check: the lid healed
        // differently than it was" (§1.3, §5 grade 3).
        public void NotifyLidDarkEnded()
        {
            if (!IsActiveHere())
            {
                return;
            }
            List<WellRecord> snapshot = new List<WellRecord>(wells);
            foreach (WellRecord w in snapshot)
            {
                AgeAndCheck(w, Rand.Range(0, TicksPerDay / 4)); // "healed differently" — a little extra, uneven aging.
            }
        }

        // A lid-dark day drives every open well's glower toward ~0 for its
        // duration and restores it afterward — glow-grid only, never a sky
        // GameCondition (§1.4). The WeatherDef/timing that decides WHEN a
        // lid-dark day happens belongs to the danger pass; this is only the
        // mechanism that dims the wells while it runs.
        public void SetLidDarkDimming(bool dark)
        {
            if (!IsActiveHere())
            {
                return;
            }
            foreach (WellRecord w in wells)
            {
                if (w.skylightThing == null || !w.skylightThing.Spawned) continue;
                CompGlower glower = w.skylightThing.TryGetComp<CompGlower>();
                if (glower == null) continue;
                if (dark)
                {
                    glower.GlowRadius = 0.1f;
                }
                else
                {
                    ApplyVisualState(w);
                    continue;
                }
                glower.ForceRegister(map);
            }
        }

        // §2.2-2: "the suulk incident's frequency reads the count of
        // player-owned mobile glowers" — the suulk incident worker itself
        // is TWILIGHT_DANGER_LIGHTWEB_1's scope; this is the one query it
        // calls once it exists.
        public int PlayerMobileGlowerCount()
        {
            int count = 0;
            List<Thing> things = map.listerThings.AllThings;
            for (int i = 0; i < things.Count; i++)
            {
                Thing t = things[i];
                if (t.Faction == Faction.OfPlayer && t.TryGetComp<RM_Comp_GlowerMobile>() != null)
                {
                    count++;
                }
                else if (t.Faction == Faction.OfPlayer && t.def.defName == "RM_ConstellationCageSphere")
                {
                    count++;
                }
                else if (t.Faction == Faction.OfPlayer && (t.def.defName == "RM_NoothelmLampClipped" || t.def.defName == "RM_HoolimbreLampClipped"))
                {
                    count++;
                }
            }
            return count;
        }
    }
}
