using System.Collections.Generic;
using RimWorld;
using UnityEngine;
using Verse;
using RimMandrake.Shared;

namespace RimMandrake.TerminalBiomes
{
    // TWILIGHT_LIGHT_ECONOMY_1 §1. The one clock this whole layer runs on.
    // "the ledger is the clock; the gardener is the hand that moves it" —
    // AdvanceWell(...) is the single code path every drift trigger calls
    // (base aging inside MapComponentTick, a gardener-pass beat via
    // NotifyGardenerPassAdvance(), and lid-dark's forced dawn check via
    // NotifyLidDarkEnded()). RM_GardenerOverhead/RM_PassingShadow and the
    // lid-dark WeatherDef itself are NOT built here — the content/danger
    // passes own them (§5, §7 table) — this class only exposes the hooks
    // they call once they exist.
    //
    // A plain MapComponent (not CustomMapComponent), so it auto-attaches to
    // EVERY map per Verse.Map.FillComponents, including the Twilight Sea
    // floor pocket map generated by mandrake.rm.divinginteraction's
    // RM_SeaDiveGenerator_TwilightSea (biome RM_TwilightSea, same defName as
    // the surface tile) — without editing that mod's MapGeneratorDef, which
    // is out of this build's scope (TerminalBiomes only). IsActiveHere()
    // gates every real method to that one biome + Mod Settings, so the
    // component is a harmless no-op everywhere else.
    //
    // 🔴 THE ENGINE TRAP (spec §1.4): every visual effect below is a
    // GLOW-GRID change (CompGlower radius/color on the RM_Skylight thing),
    // never a sky-darkening GameCondition — cached plant growth rates assume
    // surface sunlight and would leave kelp/mat-roof growing in the black.
    public class RM_MapComponent_WellLedger : MapComponent
    {
        private static readonly ColorInt GoldGlow = new ColorInt(255, 210, 120, 0);
        private static readonly ColorInt CoolDeadGlow = new ColorInt(120, 140, 150, 0);

        // The lifecycle (stages, aging, the delayed re-opening, the gardener advance, lid-dark aging) is the Verse-free kernel
        // Kernel/RM_WellKernel.cs; this component supplies the engine half through the book's delegates.
        // IExposable rather than a struct: Scribe_Collections needs a reference type to round-trip a List<WellRecord> cleanly.
        public class WellRecord : WellRec, IExposable
        {
            public int noiseSeed;
            public Thing skylightThing; // the RM_Skylight thing, Scribe_References'd

            public IntVec3 position
            {
                get { return new IntVec3(x, 0, z); }
                set { x = value.x; z = value.z; }
            }

            public void ExposeData()
            {
                Scribe_Values.Look(ref id, "id");
                IntVec3 pos = position;
                Scribe_Values.Look(ref pos, "position");
                position = pos;
                Scribe_Values.Look(ref stage, "stage", WellStage.Standing);
                Scribe_Values.Look(ref ageTicks, "ageTicks");
                Scribe_Values.Look(ref lifespanTicks, "lifespanTicks");
                Scribe_Values.Look(ref warningLetterFired, "warningLetterFired");
                Scribe_Values.Look(ref noiseSeed, "noiseSeed");
                Scribe_References.Look(ref skylightThing, "skylightThing");
            }
        }

        private List<WellRecord> wells = new List<WellRecord>();
        // A lid-dark day in progress (§1.4): every open well held near dark. Scribed.
        private bool lidDark;
        private const string LidDarkOwner = "tb.liddark";
        private const float LidDarkRadius = 0.1f;
        private int nextWellId = 1;
        private bool initialized;

        // Absolute game ticks at which a closed well's replacement is due to open.
        private List<int> pendingOpenTicks = new List<int>();

        private WellBook<WellRecord> book;

        public RM_MapComponent_WellLedger(Map map) : base(map)
        {
        }

        private WellBook<WellRecord> Book
        {
            get
            {
                if (book == null)
                {
                    book = new WellBook<WellRecord>(FindSite, Opened, ApplyVisualState, MaybeFireWarningLetter, Closed,
                        n => Rand.Range(0, n), () => RM_TerminalBiomesSettings.twilightDriftCadence);
                }
                book.Wells = wells;
                book.Pending = pendingOpenTicks;
                book.NextId = nextWellId;
                return book;
            }
        }

        private void EndOp() { nextWellId = book.NextId; }

        public static RM_MapComponent_WellLedger GetFor(Map map)
        {
            return map?.GetComponent<RM_MapComponent_WellLedger>();
        }

        private bool IsActiveHere()
        {
            return RM_TerminalBiomesSettings.TwilightWellDriftActive
                && map.Biome != null
                && map.Biome.defName == "RM_TwilightSea";
        }

        public override void ExposeData()
        {
            base.ExposeData();
            Scribe_Collections.Look(ref wells, "wells", LookMode.Deep);
            Scribe_Values.Look(ref nextWellId, "nextWellId", 1);
            Scribe_Values.Look(ref initialized, "initialized");
            Scribe_Collections.Look(ref pendingOpenTicks, "pendingOpenTicks", LookMode.Value);
            Scribe_Values.Look(ref lidDark, "rmLidDark");
            if (wells == null) wells = new List<WellRecord>();
            if (pendingOpenTicks == null) pendingOpenTicks = new List<int>();
        }

        // The light ledger is not saved (nor is vanilla's GlowRadius): put every open well's light back.
        public override void FinalizeInit()
        {
            base.FinalizeInit();
            foreach (WellRecord w in wells)
            {
                ApplyVisualState(w);
            }
        }

        public override void MapComponentTick()
        {
            if (!IsActiveHere())
            {
                return;
            }
            if (!map.IsHashIntervalTick(RM_WellKernel.TickInterval))
            {
                return;
            }

            if (!initialized)
            {
                Book.Initialize(map.Size.x);
                EndOp();
                initialized = true;
                return;
            }

            if (RM_TerminalBiomesSettings.twilightDriftCadence == 0)
            {
                // Frozen -- sandbox, wells never age (but a closed well's replacement still opens when due).
                Book.ProcessPending(Find.TickManager.TicksGame);
                EndOp();
                return;
            }

            Book.Tick(Find.TickManager.TicksGame);
            EndOp();
        }

        private bool FindSite(out int x, out int z)
        {
            IntVec3 cell = FindWellSiteCell();
            x = cell.x; z = cell.z;
            return cell.IsValid;
        }

        private void Opened(WellRecord well)
        {
            well.noiseSeed = Rand.Range(0, 1000000);
            well.skylightThing = SpawnSkylight(well.position);
        }

        private void Closed(WellRecord well)
        {
            if (well.skylightThing != null && well.skylightThing.Spawned)
            {
                well.skylightThing.Destroy(DestroyMode.Vanish);
            }
            well.skylightThing = null;
        }

        private Thing SpawnSkylight(IntVec3 cell)
        {
            ThingDef def = DefDatabase<ThingDef>.GetNamedSilentFail("RM_Skylight");
            if (def == null || !cell.IsValid)
            {
                return null; // def missing (mod list mismatch) — ledger degrades to invisible bookkeeping, never crashes.
            }
            Thing thing = ThingMaker.MakeThing(def);
            GenSpawn.Spawn(thing, cell, map);
            return thing;
        }

        private IntVec3 FindWellSiteCell()
        {
            // "on high dry ground, never on a channel bed" — this floor map
            // (GenStep_SeaFloorTerrain) is currently one uniform sediment
            // terrain with no elevation or channel-bed distinction yet, so
            // "high dry ground" has nothing to select against today. The
            // RM_ChannelBed tag check below is forward-compatible: it costs
            // nothing now and honours the siting rule the day a channel
            // terrain exists (the bank-works/current work, §2.3, out of
            // this item's scope).
            for (int attempt = 0; attempt < 60; attempt++)
            {
                IntVec3 candidate = CellFinderLoose.RandomCellWith(
                    c => c.InBounds(map) && c.Standable(map) && !IsChannelBed(c) && FarFromOtherWells(c, 8),
                    map,
                    200);
                if (candidate.IsValid)
                {
                    return candidate;
                }
            }
            return IntVec3.Invalid;
        }

        private bool IsChannelBed(IntVec3 c)
        {
            TerrainDef terrain = c.GetTerrain(map);
            return terrain != null && terrain.tags != null && terrain.tags.Contains("RM_ChannelBed");
        }

        private bool FarFromOtherWells(IntVec3 c, int minDist)
        {
            foreach (WellRecord w in wells)
            {
                if (w.stage != WellStage.Closed && c.DistanceTo(w.position) < minDist)
                {
                    return false;
                }
            }
            return true;
        }

        private void ApplyVisualState(WellRecord well)
        {
            if (well.skylightThing == null || !well.skylightThing.Spawned)
            {
                return;
            }
            CompGlower glower = well.skylightThing.TryGetComp<CompGlower>();
            if (glower == null)
            {
                return;
            }

            float factor = RM_WellKernel.GlowFactor(well.stage, well.ageTicks, well.lifespanTicks);
            ColorInt color = well.stage == WellStage.Waning
                ? ColorIntLerp(GoldGlow, CoolDeadGlow, RM_WellKernel.ColourT(well.stage, well.ageTicks, well.lifespanTicks))
                : GoldGlow;
            glower.GlowColor = color;
            // LIGHT_LEDGER_ONE_1 / TWILIGHT_WELL_LIGHT_STATE_1: the waning radius is the light's BASE and
            // lid-dark is a separate cap, so a waning step no longer erases lid-dark (and vice versa), a
            // well that opens during lid-dark opens dark, and FinalizeInit re-asserts both after a load.
            LightLedger.SetBase(glower, RM_WellKernel.Radius(factor));
            if (lidDark) LightLedger.SetCap(glower, LidDarkOwner, LidDarkRadius);
            else LightLedger.ClearCap(glower, LidDarkOwner);
        }

        private static ColorInt ColorIntLerp(ColorInt a, ColorInt b, float t)
        {
            Color ca = a.ToColor;
            Color cb = b.ToColor;
            return new ColorInt(Color.Lerp(ca, cb, Mathf.Clamp01(t)));
        }

        // "No spam for wells the player never touched": true when the warning letter went out.
        private bool MaybeFireWarningLetter(WellRecord well)
        {
            if (!AnyPlayerOwnedThingNear(well.position, 6))
            {
                return false;
            }
            Find.LetterStack.ReceiveLetter(
                "RM_TwilightWellClosingLabel".Translate(),
                "RM_TwilightWellClosingText".Translate(),
                LetterDefOf.NeutralEvent,
                new TargetInfo(well.position, map));
            return true;
        }

        private bool AnyPlayerOwnedThingNear(IntVec3 pos, int radius)
        {
            List<Thing> things = map.listerThings.AllThings;
            for (int i = 0; i < things.Count; i++)
            {
                Thing t = things[i];
                if (t.Faction == Faction.OfPlayer && t.Position.DistanceTo(pos) <= radius)
                {
                    return true;
                }
            }
            return false;
        }

        // The gardener's pass: close the well nearest its end, else bring the next pending opening forward.
        public void NotifyGardenerPassAdvance()
        {
            if (!IsActiveHere())
            {
                return;
            }
            Book.GardenerAdvance(Find.TickManager.TicksGame);
            EndOp();
        }

        // Lid-dark's forced dawn check: a little extra, uneven aging.
        public void NotifyLidDarkEnded()
        {
            if (!IsActiveHere())
            {
                return;
            }
            Book.LidDarkEnded(Find.TickManager.TicksGame);
            EndOp();
        }

        // A lid-dark day drives every open well's glower toward ~0 for its
        // duration and restores it afterward — glow-grid only, never a sky
        // GameCondition (§1.4). The WeatherDef/timing that decides WHEN a
        // lid-dark day happens belongs to the danger pass; this is only the
        // mechanism that dims the wells while it runs.
        public void SetLidDarkDimming(bool dark)
        {
            if (!IsActiveHere())
            {
                return;
            }
            lidDark = dark;
            foreach (WellRecord w in wells)
            {
                ApplyVisualState(w);
            }
        }

        // §2.2-2: "the suulk incident's frequency reads the count of
        // player-owned mobile glowers" — the suulk incident worker itself
        // is TWILIGHT_DANGER_LIGHTWEB_1's scope; this is the one query it
        // calls once it exists.
        public int PlayerMobileGlowerCount()
        {
            int count = 0;
            List<Thing> things = map.listerThings.AllThings;
            for (int i = 0; i < things.Count; i++)
            {
                Thing t = things[i];
                if (t.Faction == Faction.OfPlayer && t.TryGetComp<RM_Comp_GlowerMobile>() != null)
                {
                    count++;
                }
                else if (t.Faction == Faction.OfPlayer && t.def.defName == "RM_ConstellationCageSphere")
                {
                    count++;
                }
                else if (t.Faction == Faction.OfPlayer && (t.def.defName == "RM_NoothelmLampClipped" || t.def.defName == "RM_HoolimbreLampClipped"))
                {
                    count++;
                }
            }
            return count;
        }
    }
}
