#!/usr/bin/env python3
"""artpiped.py — the art-pipeline daemon (ART_PIPELINE_DAEMON_1).

A dumb local orchestrator, no LLM of its own: scans
`infrastructure/artpipe/pending/` for job JSON files, atomic-claims them by
`os.rename` into `active/`, and runs up to N concurrent one-shot workers —
each a `codex_image.py generate|edit` subprocess pointed at its own
`--codex-home` (openai/codex #11435: parallel `exec` under one shared
CODEX_HOME interferes via shared session restore, so isolation is mandatory,
not an optimisation). Every returned file is re-validated with
`validate_sprite.py` — a worker's own manifest is NEVER trusted (design
addendum §B, AGENTS.md's own closing note). Enforces the six
grumpiness-detector rows from
`design/RimMandrake/codex_receiving_agent_design.md`'s Addendum.

    python3 artpiped.py                       # run until SIGTERM/SIGINT
    python3 artpiped.py --once                # drain what's pending, then exit
    python3 artpiped.py --dry-run              # report what's pending, touch nothing
    python3 artpiped.py --reconcile-only       # crash recovery only, then exit
    python3 artpiped.py --worker-script .../mock_codex_worker.py --once   # tests

Crash safety: on start, any job left in `active/` with no manifest in
`done/` or `failed/` is rename-reconciled straight back to `pending/` — a
killed daemon loses no job.

No image is ever generated by this file directly; it only ever shells out to
`--worker-script` (real `codex_image.py`, or a mock for testing).
"""
from __future__ import annotations

import argparse
import json
import os
import queue
import signal
import subprocess
import sys
import threading
import time
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402

# The rollout-reading path (find the newest rollout-*.jsonl under a
# CODEX_HOME, pull its last rate_limits) already exists and is already
# selftested — skills/generating-images/scripts/codex_grumpiness.py — so it
# is imported here rather than re-implemented. Its `after_mtime` parameter is
# also what fixes a real bug this review caught: without it, `meter_after`
# for a job whose worker died before writing its own rollout would silently
# read the PREVIOUS job's leftover rollout on a reused --codex-home slot.
# codex_grumpiness's own GRUMPY_PRIMARY_PCT/GRUMPY_SECONDARY_PCT and its
# `grumpy` flag are NOT used — those are that file's own stated placeholder
# assumption (its docstring says so), whereas this item's spec gives the real
# six-row thresholds below, so only the READ path is shared, not the
# threshold judgment.
sys.path.insert(0, str(common.REPO_ROOT / "skills" / "generating-images" / "scripts"))
import codex_grumpiness  # noqa: E402

# Month-long measured median for a cold `generate` (design addendum §A) —
# the baseline row 4's wall-clock guard compares against.
BASELINE_WALL_CLOCK_S = 62.0
WALL_CLOCK_MULTIPLIER = 2.0
WALL_CLOCK_STREAK = 3

WEEKLY_WARN, WEEKLY_REFUSE, WEEKLY_STOP = 80.0, 90.0, 97.0
FIVE_H_DROP_N1, FIVE_H_SLEEP = 70.0, 90.0

DEFAULT_TIMEOUT_GENERATE_S = 150
DEFAULT_TIMEOUT_EDIT_S = 220
WORKER_SUBPROCESS_GRACE_S = 30  # on top of --timeout, so our own kill never
                                 # races the worker's own harvest-with-grace.


# --------------------------------------------------------------------------
# grumpiness detector — design addendum §B, the six rows, verbatim
# --------------------------------------------------------------------------

class Detector:
    """All shared admission-control state. Touched ONLY from the main
    thread, after a job's future has completed — never from a worker
    thread — so it needs no lock of its own."""

    def __init__(self):
        self.hard_stop = False       # row 1: TooManyRequests
        self.refuse_new = False      # row 2 @ weekly >= 90
        self.stop_all = False        # row 2 @ weekly >= 97
        self.warn_logged = False     # row 2 @ weekly >= 80
        self.n_override = None       # row 3 @ 5h >= 70 -> N=1
        self.sleep_until = None      # row 3 @ 5h >= 90 -> sleep to resets_at
        self.wall_clock_history: list[float] = []
        self.effective_n = None      # row 4: halved on a sustained slowdown

    def note_rate_limited(self) -> None:
        self.hard_stop = True

    def note_meters(self, meters: dict | None) -> None:
        """`meters` is codex_grumpiness.read_meters()'s own return shape —
        `{"ok": bool, "secondary_used_percent":.., "primary_used_percent":..,
        "primary_resets_at":..}` — not a raw rate_limits object. `ok: False`
        (no rollout yet, or none new enough) is ignorance, not 0%, and is a
        no-op here exactly like `meters` being None."""
        if not meters or not meters.get("ok"):
            return
        weekly = meters.get("secondary_used_percent")
        five_h = meters.get("primary_used_percent")
        resets_at = meters.get("primary_resets_at")

        if weekly is not None:
            if weekly >= WEEKLY_STOP:
                self.stop_all = True
            elif weekly >= WEEKLY_REFUSE:
                self.refuse_new = True
            elif weekly >= WEEKLY_WARN and not self.warn_logged:
                print(f"artpiped: WARNING weekly Codex usage at {weekly:.0f}% "
                      f"(row 2, warn threshold {WEEKLY_WARN:.0f})",
                      file=sys.stderr)
                self.warn_logged = True

        if five_h is not None:
            if five_h >= FIVE_H_SLEEP:
                self.sleep_until = resets_at or (time.time() + 300)
            elif five_h >= FIVE_H_DROP_N1:
                self.n_override = 1

    def note_wall_clock(self, seconds: float, configured_n: int) -> None:
        # Timeouts DO reach this method, correctly: a timed-out request is
        # definitionally the slowest possible one, and this row's job is to
        # notice a sustained slowdown, timeouts included. What must NEVER
        # reach note_rate_limited (row 1) is a plain timeout — only an
        # explicit TooManyRequests/rate-limited text match does that (see
        # _looks_rate_limited and its call site in process_job) — so a
        # slow-but-real request cannot masquerade as a throttle refusal, even
        # though it is exactly the kind of thing that SHOULD slow this row down.
        self.wall_clock_history.append(seconds)
        self.wall_clock_history = self.wall_clock_history[-5:]
        if len(self.wall_clock_history) >= WALL_CLOCK_STREAK:
            last = self.wall_clock_history[-WALL_CLOCK_STREAK:]
            if all(s > BASELINE_WALL_CLOCK_S * WALL_CLOCK_MULTIPLIER for s in last):
                base = self.effective_n if self.effective_n is not None else configured_n
                self.effective_n = max(1, base // 2)
                self.wall_clock_history.clear()  # don't re-trigger every tick

    def admission_blocked(self) -> bool:
        if self.hard_stop or self.stop_all or self.refuse_new:
            return True
        if self.sleep_until and time.time() < self.sleep_until:
            return True
        return False

    def current_n(self, configured_n: int) -> int:
        n = configured_n
        if self.n_override is not None:
            n = min(n, self.n_override)
        if self.effective_n is not None:
            n = min(n, self.effective_n)
        return max(1, n)


# Specific throttle phrasing, not a bare "rate limited" substring — that
# loose a match collides with ordinary art-prompt vocabulary (a "rusted
# rate-limited valve" reskin prompt would trip it). "toomanyrequests" is
# camelCase and effectively never appears in natural English by accident.
RATE_LIMIT_MARKERS = ("toomanyrequests", "rate limit exceeded",
                      "was rate limited", "request was rate limited")


def _looks_rate_limited(text: str, prompt: str | None = None) -> bool:
    """Detect an explicit throttle refusal in the worker's captured stdout+
    stderr. Not a fully structured signal — codex_image.py has no field for
    "the account got throttled" distinct from its own raw output blob
    (do_image() dumps up to 2000 chars of it to stderr on ANY failure,
    --verbose or not), so this is a best-effort text match, not the clean
    field lookup the ideal fix would use. Two mitigations against a false
    hard-stop: this job's own `prompt` — which that same dump routinely
    echoes back verbatim — is stripped out of the haystack first, and the
    remaining markers are specific throttle phrasing (see RATE_LIMIT_MARKERS)
    rather than anything a benign prompt could contain.
    """
    hay = text or ""
    if prompt:
        hay = hay.replace(prompt, "")
    hay = hay.lower()
    return any(marker in hay for marker in RATE_LIMIT_MARKERS)


# --------------------------------------------------------------------------
# queue mechanics
# --------------------------------------------------------------------------

def _priority_of(path: Path) -> int:
    try:
        return int(json.loads(path.read_text()).get("priority", 100))
    except (OSError, ValueError, TypeError):
        return 100


def claim_next(pending_dir: Path, active_dir: Path) -> Path | None:
    """Atomic claim = rename pending/<id>.json -> active/<id>.json.

    `os.rename` removing the SOURCE is the atomic event: if another daemon
    renamed it away between our glob() and our rename(), the source is gone
    and rename raises FileNotFoundError — that daemon lost the race, moves on
    to the next candidate, and never touches the file the winner claimed.

    Two things happen right after a successful rename, both load-bearing:

    1. `os.utime(dest)` stamps a FRESH mtime. `os.rename` preserves the
       inode's existing mtime, so without this a job that sat in pending/
       for 20 minutes before being claimed would carry that 20-minute-old
       timestamp straight into active/ — and reconcile()'s age gate, which
       exists specifically to tell a crashed orphan from a live claim by
       age, would misread a job claimed one second ago as one stale enough
       to steal back. This is exactly the bug the concurrent-daemons
       selftest caught (see reconcile()'s own docstring).
    2. A re-stat of `dest` immediately after the rename, because production
       runs on /mnt/d (DrvFs/9p), which this repo has already measured
       serving minutes-stale reads to a second process — see
       `common.py`'s module docstring. `os.rename`'s atomicity is a POSIX
       filesystem promise; whether DrvFs's OWN consistency under two WSL
       processes racing the same rename honors it as cleanly is NOT
       independently verified here (the selftests run on real tmpfs/ext4
       under WSL2, not on the DrvFs mount). Treating a stat that can't see
       what we just renamed as a lost race — the same as a FileNotFoundError
       on the rename itself — is the best mitigation available from user
       space; it is a mitigation, not a proof.
    """
    try:
        candidates = sorted(pending_dir.glob("*.json"), key=lambda p: (_priority_of(p), p.name))
    except OSError:
        return None
    for src in candidates:
        dest = active_dir / src.name
        if dest.exists():
            continue  # a stray same-named file already claimed — never clobber it
        try:
            os.rename(src, dest)
        except FileNotFoundError:
            continue  # lost the race to another daemon
        try:
            os.utime(dest, None)
            dest.stat()
        except FileNotFoundError:
            continue  # a stale-read filesystem's rename that a stat can't see: lost race
        return dest
    return None


def _queue_empty(pending_dir: Path) -> bool:
    try:
        next(pending_dir.glob("*.json"))
        return False
    except StopIteration:
        return True


def reconcile(active_dir: Path, pending_dir: Path, done_dir: Path,
              failed_dir: Path, min_age_s: float = 600.0) -> list[tuple[str, str]]:
    """Crash recovery: an active/ job with no manifest anywhere MIGHT be an
    orphan from a killed daemon — or it might just be another live daemon's
    in-flight claim, which looks IDENTICAL (no manifest yet either) until it
    finishes. The only honest signal that distinguishes them is age: no
    single job can legitimately still be running past its own worst-case
    ceiling (an edit's --timeout-edit + the subprocess grace + the
    validator's own timeout), so `min_age_s` defaults comfortably above that
    (600s vs. a ~310s worst case). A job younger than this is left alone even
    with no manifest — reconciling it anyway is exactly the bug the
    concurrent-daemons selftest caught: daemon B's startup reconcile stole
    daemon A's still-in-flight claim, and A's later os.replace() crashed on a
    file that had already moved out from under it.
    """
    moved = []
    try:
        actives = sorted(active_dir.glob("*.json"))
    except OSError:
        return moved
    now = time.time()
    for p in actives:
        job_id = p.stem
        if (done_dir / f"{job_id}.manifest.json").is_file() or \
           (failed_dir / f"{job_id}.manifest.json").is_file():
            # Already terminally processed without being moved — leave it for
            # a human; guessing which copy is authoritative is worse than
            # asking.
            continue
        try:
            age = now - p.stat().st_mtime
        except OSError:
            continue
        if age < min_age_s:
            continue  # too young to be confidently orphaned — may be live
        dest = pending_dir / p.name
        if dest.exists():
            continue
        try:
            os.rename(p, dest)
        except FileNotFoundError:
            continue
        try:
            dest.stat()
        except FileNotFoundError:
            continue  # see claim_next()'s docstring: a stale-read mount can
                      # report a rename a stat then can't see — lost race, not a move.
        moved.append((job_id, "no manifest in done/ or failed/"))
        stray = active_dir / f"{job_id}.worker_last_message.json"
        if stray.is_file():
            try:
                stray.unlink()
            except OSError:
                pass
    return moved


# --------------------------------------------------------------------------
# running one job
# --------------------------------------------------------------------------

class RunCtx:
    """Immutable-for-the-run configuration handed to every worker thread."""

    def __init__(self, worker_script, validator_script, manifest_schema,
                 artsrc_dir, active_dir, codex_home_root, timeout_generate,
                 timeout_edit, reasoning_effort, verbose, slots):
        self.worker_script = worker_script
        self.validator_script = validator_script
        self.manifest_schema = manifest_schema
        self.artsrc_dir = artsrc_dir
        self.active_dir = active_dir
        self.codex_home_root = codex_home_root
        self.timeout_generate = timeout_generate
        self.timeout_edit = timeout_edit
        self.reasoning_effort = reasoning_effort
        self.verbose = verbose
        self.slots = slots  # queue.Queue of free worker-slot ints
        # No `dry_run` field: --dry-run is handled entirely in main()'s
        # run_dry_run(), before a RunCtx is ever built, so it never claims a
        # real job or reaches process_job at all (finding: dry-run used to
        # consume the real queue — see run_dry_run's docstring).


def build_job_prompt(job: dict) -> str:
    canvas = job["canvas"]
    parts = [f"[artpipe job {job['id']}] {job['prompt']}",
             f"Canvas: exactly {canvas['width']}x{canvas['height']} pixels."]
    bg = job.get("background") or "transparent"
    if bg == "transparent":
        parts.append("Background: a genuinely transparent alpha channel — "
                      "no backdrop, floor, shadow or gradient.")
    else:
        parts.append(f"Background: one perfectly flat solid field of {bg}, "
                      f"used nowhere in the subject.")
    if job.get("style_notes"):
        parts.append(f"Style: {job['style_notes']}")
    if job.get("facing"):
        parts.append(f"Facing: {job['facing']}.")
    return " ".join(parts)


def run_worker(worker_script: Path, subcmd: str, prompt: str, out_png: Path,
                codex_home: Path, timeout: int, schema_path: Path,
                last_msg_path: Path, reference, model, reasoning_effort,
                verbose: bool) -> tuple[int, str, str, float, bool]:
    cmd = [sys.executable, str(worker_script), subcmd,
           "--prompt", prompt, "--out", str(out_png),
           "--codex-home", str(codex_home), "--timeout", str(timeout),
           "--force", "--reasoning-effort", reasoning_effort,
           "--output-schema", str(schema_path),
           "--output-last-message", str(last_msg_path)]
    if model:
        cmd += ["--model", model]
    if reference:
        cmd += ["--image", str(reference)]
    if verbose:
        cmd.append("--verbose")

    started = time.monotonic()
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                               timeout=timeout + WORKER_SUBPROCESS_GRACE_S)
        return proc.returncode, proc.stdout, proc.stderr, time.monotonic() - started, False
    except subprocess.TimeoutExpired as exc:
        out = exc.stdout.decode() if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        err = exc.stderr.decode() if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return 124, out, err, time.monotonic() - started, True


def run_validator(validator_script: Path, reference, candidate: Path):
    """Returns (verdict, findings). verdict is one of:
      None              — skipped, no reference on this job (never a silent pass)
      "pass"             — validate_sprite.py exit 0
      "reject"           — exit 1: the IMAGE is not shippable
      "cannot_validate"  — exit 2 (or anything else): the INPUT was unusable
                            (e.g. a missing/unreadable reference path) — a
                            data problem on the job, never the same thing as
                            the worker having produced a bad image, and must
                            never be reported to the owner as an art-quality
                            rejection.
    """
    if not reference:
        return None, ["no reference on this job — validator skipped, not a pass"]
    proc = subprocess.run(
        [sys.executable, str(validator_script), "--reference", str(reference),
         "--candidate", str(candidate)],
        capture_output=True, text=True, timeout=60)
    findings = (proc.stdout + proc.stderr).strip().splitlines()
    if proc.returncode == 0:
        return "pass", findings
    if proc.returncode == 1:
        return "reject", findings
    return "cannot_validate", findings


def process_job(job_path: Path, ctx: RunCtx) -> dict:
    """Runs in a worker thread. Returns a result dict; touches no shared
    detector/file-move state — the caller does that after collecting the
    future, so nothing here needs a lock."""
    try:
        job = common.load_job(job_path)
    except common.JobError as exc:
        return {"id": job_path.stem, "status": "failed", "note": str(exc),
                "worker_status": "bad_job_file", "validator": "not_run"}

    job_id = job["id"]
    reference = job.get("reference")
    is_edit = bool(reference)
    subcmd = "edit" if is_edit else "generate"
    timeout = ctx.timeout_edit if is_edit else ctx.timeout_generate
    out_png = ctx.artsrc_dir / f"{job_id}.png"
    last_msg_path = ctx.active_dir / f"{job_id}.worker_last_message.json"

    slot = ctx.slots.get()
    try:
        # w<slot>-<pid>: unique per PROCESS, not just per in-process slot
        # index. Slot integers are only unique WITHIN one daemon; two daemons
        # sharing --codex-home-root would otherwise both compute "w0" and
        # collide under one CODEX_HOME — exactly the openai/codex #11435
        # interference this file's own module docstring calls mandatory to
        # avoid, and slot numbers alone do not avoid it across processes.
        codex_home = ctx.codex_home_root / f"w{slot}-{os.getpid()}"
        codex_home.mkdir(parents=True, exist_ok=True)
        meter_before = codex_grumpiness.read_meters(codex_home)

        prompt = build_job_prompt(job)

        # A stale PNG/manifest at these exact paths, left by a PREVIOUS
        # attempt at this same job id (a requeue after a fix, or a leftover
        # from a killed run), must never be mistaken for THIS run's output.
        # Delete both before spawning, so anything found afterward genuinely
        # came from this invocation.
        for stale in (out_png, last_msg_path):
            try:
                stale.unlink()
            except FileNotFoundError:
                pass

        job_started_at = time.time()
        code, out, err, elapsed, timed_out = run_worker(
            ctx.worker_script, subcmd, prompt, out_png, codex_home, timeout,
            ctx.manifest_schema, last_msg_path, reference, job.get("model"),
            ctx.reasoning_effort, ctx.verbose)
    finally:
        # Acquisition-to-release is now ALL inside this try — a mkdir
        # failure, a malformed job reaching build_job_prompt (load_job now
        # validates shapes, not just key presence, but this stays as
        # defence in depth), or any other exception in between still
        # returns the slot. Before this fix, an exception here leaked the
        # slot permanently; with -N 1 that deadlocks the daemon, and since
        # queue.Queue.get() has no timeout, SIGTERM cannot unblock it either
        # — the drain-in-flight shutdown would simply hang forever.
        ctx.slots.put(slot)

    # `after_mtime=job_started_at` is the fix for a real bug: without a
    # floor, a worker that died before writing its own rollout (a crash, a
    # refusal before the first token) would leave read_meters() reading
    # whatever rollout this codex_home's slot last wrote for a PREVIOUS job
    # — misattributing that job's meters to this one in throughput.jsonl and
    # to the detector.
    meter_after = codex_grumpiness.read_meters(codex_home, after_mtime=job_started_at)
    # `prompt` is stripped from the searched text before matching — see
    # _looks_rate_limited's own docstring for why an unstripped haystack is
    # a false-hard-stop risk.
    text = (out or "") + (err or "")
    result = {"id": job_id, "elapsed_s": elapsed, "timed_out": timed_out,
              "meter_before": meter_before, "meter_after": meter_after}

    # Row 1 first: an explicit throttle refusal, checked before anything
    # else about exit code or files.
    if _looks_rate_limited(text, prompt):
        result.update(status="failed", worker_status="rate_limited",
                       validator="not_run", detector_row=1,
                       note="TooManyRequests / rate limited — hard stop, "
                            "drain queue (row 1)")
        return result

    manifest_present = last_msg_path.is_file()
    image_present = out_png.is_file()

    # A nonzero exit or a timeout is NEVER trustworthy evidence, however
    # tempting a leftover file looks — checked before image_present, so a
    # killed subprocess's partial write (or, pre-fix, a genuinely stale file
    # from a previous attempt) can never be filed as "ok". Row 6: a timeout
    # is still never treated as throttle evidence here — it falls through to
    # the same plain "worker_error" as any other nonzero exit, never to
    # detector_row=1.
    if code != 0 or timed_out:
        result.update(status="failed", worker_status="worker_error",
                       validator="not_run",
                       note=(f"worker exited {code}, image_present={image_present} — "
                             f"a failed/timed-out run is never trusted regardless"
                             + (" (timed out)" if timed_out else "")))
        return result

    if not image_present:
        if manifest_present:
            result.update(status="failed", worker_status="worker_reported_fail",
                           validator="not_run",
                           note="exit 0, a manifest exists, but no image — "
                                "the worker reported failure/refusal honestly")
        else:
            # Row 5: exit 0 with no manifest and no image is the `--`-trap
            # no-op — fail THIS request, never the account.
            result.update(status="failed", worker_status="no_manifest",
                           validator="not_run", detector_row=5,
                           note="exit 0, no manifest, no image — the `--` "
                                "no-op (row 5): fails the request, not the account")
        return result

    verdict, findings = run_validator(ctx.validator_script, reference, out_png)
    result["validator_findings"] = findings
    if verdict == "reject":
        result.update(status="failed", worker_status="worker_reported_ok_but_invalid",
                       validator="REJECT",
                       note="validate_sprite.py rejected the returned file — "
                            "the worker's own manifest is never trusted")
        return result
    if verdict == "cannot_validate":
        # exit 2: the INPUT was unusable (e.g. a missing/unreadable
        # reference path) — a data problem on the JOB, not the same failure
        # as the worker having produced a bad image, and reported as its own
        # kind rather than folded into REJECT.
        result.update(status="failed", worker_status="bad_reference_path",
                       validator="CANNOT_VALIDATE",
                       note="validate_sprite.py could not judge this at all "
                            "(exit 2, unusable input) — most likely a bad or "
                            "missing reference path on the job, not an image defect")
        return result

    result.update(status="ok", worker_status="ok",
                   validator=("PASS" if verdict == "pass" else "skipped"),
                   note="validated" if verdict == "pass" else "no reference to validate against")
    return result


def finalize_job(job_path: Path, result: dict, done_dir: Path, failed_dir: Path,
                  active_dir: Path, throughput_log: Path, detector: Detector,
                  configured_n: int) -> None:
    job_id = result.get("id", job_path.stem)
    # "dry_run" is not a real status here any more — --dry-run never reaches
    # finalize_job at all (see run_dry_run) — so "ok" is the only passing
    # status a real run can produce.
    ok = result.get("status") == "ok"
    target_dir = done_dir if ok else failed_dir

    dest_job = target_dir / f"{job_id}.json"
    manifest_path = target_dir / f"{job_id}.manifest.json"
    common.atomic_write_json(manifest_path, result)
    try:
        os.replace(job_path, dest_job)
    except FileNotFoundError:
        # job_path vanished from under us — reconcile() stealing a live
        # claim was the one way this used to happen (fixed by its own
        # min_age_s gate); never let one job's bookkeeping surprise crash
        # the whole daemon and abandon everything else it was running.
        print(f"artpiped: WARNING {job_id}'s active/ file disappeared before "
              f"it could be filed to {target_dir.name}/ — manifest written, "
              f"job file itself is now unaccounted for", file=sys.stderr)

    stray = active_dir / f"{job_id}.worker_last_message.json"
    if stray.is_file():
        try:
            stray.unlink()
        except OSError:
            pass

    common.append_jsonl(throughput_log, {
        "ts": time.time(), "id": job_id, "status": result.get("status"),
        "worker_status": result.get("worker_status"),
        "elapsed_s": result.get("elapsed_s"),
        "validator": result.get("validator"),
        "meter_before": result.get("meter_before"),
        "meter_after": result.get("meter_after"),
    })

    if result.get("detector_row") == 1:
        detector.note_rate_limited()
    detector.note_meters(result.get("meter_after"))
    if result.get("elapsed_s") is not None:
        detector.note_wall_clock(result["elapsed_s"], configured_n)


# --------------------------------------------------------------------------
# main loop
# --------------------------------------------------------------------------

def parse_args(argv=None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--pending-dir", type=Path, default=common.DEFAULT_PENDING)
    ap.add_argument("--active-dir", type=Path, default=common.DEFAULT_ACTIVE)
    ap.add_argument("--done-dir", type=Path, default=common.DEFAULT_DONE)
    ap.add_argument("--failed-dir", type=Path, default=common.DEFAULT_FAILED)
    ap.add_argument("--artsrc-dir", type=Path, default=common.DEFAULT_ARTSRC)
    ap.add_argument("--throughput-log", type=Path, default=common.DEFAULT_THROUGHPUT_LOG)
    ap.add_argument("--codex-home-root", type=Path, default=common.DEFAULT_CODEX_HOME_ROOT)
    ap.add_argument("--worker-script", type=Path,
                     default=Path(os.environ.get("ARTPIPE_WORKER_SCRIPT",
                                                   str(common.DEFAULT_WORKER_SCRIPT))))
    ap.add_argument("--validator-script", type=Path, default=common.DEFAULT_VALIDATOR)
    ap.add_argument("--manifest-schema", type=Path, default=common.MANIFEST_SCHEMA)
    ap.add_argument("-N", "--workers", type=int, default=3)
    ap.add_argument("--timeout-generate", type=int, default=DEFAULT_TIMEOUT_GENERATE_S)
    ap.add_argument("--timeout-edit", type=int, default=DEFAULT_TIMEOUT_EDIT_S)
    ap.add_argument("--reasoning-effort", default="low")
    ap.add_argument("--poll-interval", type=float, default=2.0)
    ap.add_argument("--once", action="store_true",
                     help="drain what's claimable now, then exit — for scripts/tests")
    ap.add_argument("--dry-run", action="store_true",
                     help="report what pending/ would run and exit — reads "
                          "only, never claims, reconciles, or moves anything")
    ap.add_argument("--reconcile-only", action="store_true",
                     help="run crash reconciliation and exit — a human's recovery tool")
    ap.add_argument("--reconcile-min-age", type=float, default=600.0,
                     help="seconds an active/ job with no manifest must sit "
                          "untouched before reconcile() treats it as an orphan "
                          "rather than another live daemon's in-flight claim "
                          "(default comfortably above --timeout-edit's worst case)")
    ap.add_argument("--verbose", action="store_true")
    return ap.parse_args(argv)


def run_dry_run(args: argparse.Namespace) -> int:
    """Report what WOULD run, touching nothing.

    Previously, --dry-run's "do everything except spawn a worker" ran
    THROUGH the real claim_next()/finalize_job() path with a synthetic
    "dry_run" status — which still renamed real jobs out of pending/ into
    active/ and then into done/, permanently consuming the real queue and
    blocking a later real re-file as a duplicate id. This is a pure read:
    it lists what claim_next() would pick, in the order it would pick them,
    and moves or writes nothing — pending/ is byte-for-byte what it was
    before this ran. It does not call reconcile() either, for the same
    reason: reconcile can move a file, and --dry-run promises it never does.
    """
    try:
        candidates = sorted(args.pending_dir.glob("*.json"),
                            key=lambda p: (_priority_of(p), p.name))
    except OSError:
        candidates = []

    if not candidates:
        print("artpiped: --dry-run, nothing pending")
        return 0

    for p in candidates:
        try:
            job = common.load_job(p)
        except common.JobError as exc:
            print(f"would FAIL to claim {p.name}: {exc}")
            continue
        is_edit = bool(job.get("reference"))
        subcmd = "edit" if is_edit else "generate"
        out_png = args.artsrc_dir / f"{job['id']}.png"
        print(f"would claim {p.name}: {subcmd} -> {out_png}")
        if args.verbose:
            print(f"    prompt: {build_job_prompt(job)}")

    print(f"\nartpiped: --dry-run, {len(candidates)} job(s) would be claimed — "
          f"pending/ left untouched, no worker spawned")
    return 0


def main(argv=None) -> int:
    args = parse_args(argv)
    common.ensure_queue_dirs(args.pending_dir, args.active_dir, args.done_dir,
                              args.failed_dir, args.artsrc_dir)

    if args.dry_run:
        return run_dry_run(args)

    moved = reconcile(args.active_dir, args.pending_dir, args.done_dir,
                       args.failed_dir, args.reconcile_min_age)
    for job_id, why in moved:
        print(f"artpiped: reconciled {job_id} — {why} — returned to pending/")

    if args.reconcile_only:
        print(f"artpiped: reconcile-only, {len(moved)} job(s) recovered")
        return 0

    slots: "queue.Queue[int]" = queue.Queue()
    for i in range(args.workers):
        slots.put(i)

    ctx = RunCtx(args.worker_script, args.validator_script, args.manifest_schema,
                 args.artsrc_dir, args.active_dir, args.codex_home_root,
                 args.timeout_generate, args.timeout_edit, args.reasoning_effort,
                 args.verbose, slots)
    detector = Detector()
    stop_event = threading.Event()

    def _handle_signal(signum, _frame):
        print(f"artpiped: signal {signum} received, draining in-flight work then exiting",
              file=sys.stderr)
        stop_event.set()

    signal.signal(signal.SIGTERM, _handle_signal)
    signal.signal(signal.SIGINT, _handle_signal)

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        futures: dict = {}
        while True:
            if not stop_event.is_set() and not detector.admission_blocked():
                current_n = detector.current_n(args.workers)
                while len(futures) < current_n:
                    job_path = claim_next(args.pending_dir, args.active_dir)
                    if job_path is None:
                        break
                    futures[pool.submit(process_job, job_path, ctx)] = job_path

            if not futures:
                exhausted = _queue_empty(args.pending_dir) or detector.admission_blocked()
                if stop_event.is_set() or (args.once and exhausted):
                    break
                time.sleep(args.poll_interval)
                continue

            done, _ = wait(futures, timeout=args.poll_interval, return_when=FIRST_COMPLETED)
            for fut in done:
                job_path = futures.pop(fut)
                try:
                    result = fut.result()
                except Exception as exc:  # never let a worker-thread crash kill the daemon
                    result = {"id": job_path.stem, "status": "failed",
                              "note": f"process_job raised: {type(exc).__name__}: {exc}"}
                finalize_job(job_path, result, args.done_dir, args.failed_dir,
                             args.active_dir, args.throughput_log, detector, args.workers)

            if stop_event.is_set() and not futures:
                break
            if args.once and not futures and _queue_empty(args.pending_dir):
                break

    print(f"artpiped: stopped. hard_stop={detector.hard_stop} "
          f"refuse_new={detector.refuse_new} stop_all={detector.stop_all}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
