#!/usr/bin/env python3
"""artpiped.py — the art-pipeline daemon (ART_PIPELINE_DAEMON_1).

A dumb local orchestrator, no LLM of its own: scans
`infrastructure/artpipe/pending/` for job JSON files, atomic-claims them by
`os.rename` into `active/`, and runs up to N concurrent one-shot workers.
Two channels, routed per job by its `"channel"` field:

  - **codex** (default) — a `codex_image.py generate|edit` subprocess per
    job, pointed at a small POOL of leased `--codex-home` directories
    (openai/codex #11435: parallel `exec` under one shared CODEX_HOME
    interferes via shared session restore, so isolation is mandatory).
    Gated by the six-row grumpiness `Detector` below.
  - **gemini** — a `gemini_image.py generate --ref` subprocess per job. NOT
    gated by the codex Detector at all — gated instead by `GeminiBudget`, a
    dollar cap read from `throughput.jsonl` (durable across restarts) and
    hard-stopped once spend reaches `--gemini-budget-usd`.

Every returned file is re-validated independently — real dimensions read
and checked against the job's own `canvas` (the image tool is KNOWN to
ignore requested size; this is the normal case, not an edge case), then
`validate_sprite.py` if a reference exists. A worker's own self-report is
NEVER trusted for the pass/fail verdict, on either channel.

    python3 artpiped.py                       # run until SIGTERM/SIGINT
    python3 artpiped.py --once                # drain what's pending, then exit
    python3 artpiped.py --dry-run              # report what's pending, touch nothing
    python3 artpiped.py --reconcile-only       # crash recovery (+ --repair), then exit
    python3 artpiped.py --repair               # just the crash-state completion, then exit
    python3 artpiped.py --worker-script .../mock_codex_worker.py --once   # tests

Crash safety: on start, any job left in `active/` with no manifest in
`done/` or `failed/` is rename-reconciled straight back to `pending/` — a
killed daemon loses no job. A DIFFERENT crash state — the manifest got
written but the daemon died before moving the job file out of `active/` —
is deliberately left alone by `reconcile()` (guessing which of two possible
manifests is authoritative would be worse than asking); `repair()` completes
that specific, unambiguous case.

No image is ever generated by this file directly; it only ever shells out to
`--worker-script`/`--gemini-worker-script` (real tools, or mocks for testing).
"""
from __future__ import annotations

import argparse
import json
import os
import queue
import re
import signal
import statistics
import subprocess
import sys
import threading
import time
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import common  # noqa: E402

# The rollout-reading path (find the newest rollout-*.jsonl under a
# CODEX_HOME, pull its last rate_limits) and the PNG-header reader both
# already exist and are already selftested —
# skills/generating-images/scripts/codex_grumpiness.py and codex_image.py's
# own png_info() — so they are imported here rather than re-implemented.
# codex_grumpiness's `after_mtime` parameter is also what fixes a real bug:
# without it, `meter_after` for a job whose worker died before writing its
# own rollout would silently read the PREVIOUS job's leftover rollout on a
# reused codex_home. codex_grumpiness's own GRUMPY_PRIMARY_PCT/
# GRUMPY_SECONDARY_PCT and its `grumpy` flag are NOT used — those are that
# file's own stated placeholder assumption, whereas this item's spec gives
# the real six-row thresholds below, so only the READ paths are shared, not
# the threshold judgment.
sys.path.insert(0, str(common.REPO_ROOT / "skills" / "generating-images" / "scripts"))
import codex_grumpiness  # noqa: E402
import codex_image  # noqa: E402

# Month-long measured median for a cold `generate` (design addendum §A) —
# the baseline row 4's wall-clock guard compares against.
BASELINE_WALL_CLOCK_S = 62.0
WALL_CLOCK_MULTIPLIER = 2.0
WALL_CLOCK_STREAK = 3

WEEKLY_WARN, WEEKLY_REFUSE, WEEKLY_STOP = 80.0, 90.0, 97.0
FIVE_H_DROP_N1, FIVE_H_SLEEP = 70.0, 90.0

DEFAULT_TIMEOUT_GENERATE_S = 150
DEFAULT_TIMEOUT_EDIT_S = 220
WORKER_SUBPROCESS_GRACE_S = 30  # on top of --timeout, so our own kill never
                                 # races the worker's own harvest-with-grace.

# Row 1 spec: one retry max on a failed request — never for an explicit
# throttle refusal, which goes straight to the hard stop instead.
MAX_CODEX_ATTEMPTS = 2

# gemini_image.py's own docstring: "Nano Banana Pro (gemini-3-pro-image) —
# best identity-across-angles". $/image from the owner's contrast-batch
# pricing (GEMINI_WORKER_BACKEND_1). An unrecognised model falls back to
# this same figure — the only price point actually known — logged loudly
# rather than silently treated as free.
GEMINI_MODEL_COST_USD = {"gemini-3-pro-image": 0.134}
DEFAULT_GEMINI_MODEL = "gemini-3-pro-image"
DEFAULT_GEMINI_BUDGET_USD = 20.0
DEFAULT_GEMINI_TIMEOUT_S = 200  # gemini_image.py's own urllib call times out at 180s.


# --------------------------------------------------------------------------
# grumpiness detector — design addendum §B, the six rows (codex channel only)
# --------------------------------------------------------------------------

def _coerce_epoch(value) -> float | None:
    """`primary_resets_at` must be a numeric unix epoch. Anything else (an
    ISO string, a seconds-remaining delta, None) is coerced to "unknown"
    rather than trusted: an ISO string would TypeError the main thread
    comparing `time.time() < sleep_until`, and a seconds-remaining value
    would compare as a tiny past epoch and silently never sleep at all —
    both worse than falling back to a value we know is safe."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    return None


class Detector:
    """All shared admission-control state for the CODEX channel only — the
    gemini channel is gated by GeminiBudget instead (spec: "the codex
    grumpiness detector does NOT gate gemini jobs"). Touched ONLY from the
    main thread, after a job's future has completed — never from a worker
    thread — so it needs no lock of its own.

    De-escalating by design, except row 1: every threshold here is
    RECOMPUTED from the CURRENT reading on each note_meters() call, so a
    weekly usage that climbed to 93% and then reset to 1% (a new week, or a
    stale one-off bad reading) clears refuse_new/n_override/sleep_until on
    the very next healthy reading. Only `hard_stop` (row 1, an explicit
    TooManyRequests) stays latched for the rest of this run — a real
    throttle refusal is not something a later healthy meter reading should
    be allowed to paper over.
    """

    def __init__(self):
        self.hard_stop = False       # row 1: TooManyRequests — LATCHED, never clears
        self.refuse_new = False      # row 2 @ weekly >= 90 — recomputed each reading
        self.stop_all = False        # row 2 @ weekly >= 97 — recomputed each reading
        self.warn_logged = False     # row 2 @ weekly >= 80 — clears below 80 so it can re-fire
        self.n_override = None       # row 3 @ 5h >= 70 -> N=1 — recomputed each reading
        self.sleep_until = None      # row 3 @ 5h >= 90 -> sleep to resets_at — recomputed
        self.wall_clock_history: list[float] = []
        self._slow_streak = 0
        self.effective_n = None      # row 4: halved on a sustained slowdown (one-way ratchet)

    def note_rate_limited(self) -> None:
        self.hard_stop = True

    def note_meters(self, meters: dict | None) -> None:
        """`meters` is codex_grumpiness.read_meters()'s own return shape —
        `{"ok": bool, "secondary_used_percent":.., "primary_used_percent":..,
        "primary_resets_at":..}` — not a raw rate_limits object. `ok: False`
        (no rollout yet, or none new enough) is ignorance: state is left
        UNCHANGED, neither reset to healthy nor held at whatever it was."""
        if not meters or not meters.get("ok"):
            return
        weekly = meters.get("secondary_used_percent")
        five_h = meters.get("primary_used_percent")
        resets_raw = meters.get("primary_resets_at")

        if weekly is not None:
            self.stop_all = weekly >= WEEKLY_STOP
            self.refuse_new = (not self.stop_all) and weekly >= WEEKLY_REFUSE
            if weekly >= WEEKLY_WARN:
                if not self.warn_logged:
                    print(f"artpiped: WARNING weekly Codex usage at {weekly:.0f}% "
                          f"(row 2, warn threshold {WEEKLY_WARN:.0f})", file=sys.stderr)
                    self.warn_logged = True
            else:
                self.warn_logged = False  # de-escalate: a fresh low reading can warn again later

        if five_h is not None:
            if five_h >= FIVE_H_SLEEP:
                coerced = _coerce_epoch(resets_raw)
                if coerced is not None:
                    self.sleep_until = coerced
                    self.n_override = None
                else:
                    print(f"artpiped: WARNING primary_resets_at is not a usable epoch "
                          f"({resets_raw!r}) — five-hour usage is >= {FIVE_H_SLEEP:.0f}% "
                          f"but falling back to N=1 instead of a sleep gate I cannot trust",
                          file=sys.stderr)
                    self.sleep_until = None
                    self.n_override = 1
            elif five_h >= FIVE_H_DROP_N1:
                self.n_override = 1
                self.sleep_until = None
            else:
                self.n_override = None
                self.sleep_until = None

    def note_wall_clock(self, seconds: float, configured_n: int) -> None:
        """Row 4 spec, literally: the ROLLING MEDIAN of the last 5 wall-clock
        readings, checked against 2x baseline, for 3 CONSECUTIVE calls —
        not "the last 3 readings were each individually slow". A single
        outlier (one very slow request among four fast ones) moves the
        median far less than it would move a naive "all of the last 3"
        check, which is the point of using a median here at all.

        Timeouts DO reach this method, correctly: a timed-out request is
        definitionally the slowest possible one, and this row's job is to
        notice a sustained slowdown, timeouts included. What must NEVER
        reach note_rate_limited (row 1) is a plain timeout — only an
        explicit TooManyRequests/rate-limited text match does that (see
        _looks_rate_limited and its call site) — so a slow-but-real request
        cannot masquerade as a throttle refusal, even though it is exactly
        the kind of thing that SHOULD slow this row down.
        """
        self.wall_clock_history.append(seconds)
        self.wall_clock_history = self.wall_clock_history[-5:]
        median = statistics.median(self.wall_clock_history)
        if median > BASELINE_WALL_CLOCK_S * WALL_CLOCK_MULTIPLIER:
            self._slow_streak += 1
        else:
            self._slow_streak = 0
        if self._slow_streak >= WALL_CLOCK_STREAK:
            base = self.effective_n if self.effective_n is not None else configured_n
            self.effective_n = max(1, base // 2)
            self._slow_streak = 0  # don't re-trigger every single tick thereafter

    def admission_blocked(self) -> bool:
        if self.hard_stop or self.stop_all or self.refuse_new:
            return True
        if self.sleep_until and time.time() < self.sleep_until:
            return True
        return False

    def current_n(self, configured_n: int) -> int:
        n = configured_n
        if self.n_override is not None:
            n = min(n, self.n_override)
        if self.effective_n is not None:
            n = min(n, self.effective_n)
        return max(1, n)


# --------------------------------------------------------------------------
# gemini budget — an independent, non-de-escalating dollar cap
# --------------------------------------------------------------------------

def _gemini_model_cost(model: str) -> float:
    return GEMINI_MODEL_COST_USD.get(model, GEMINI_MODEL_COST_USD[DEFAULT_GEMINI_MODEL])


def read_gemini_spend(throughput_log: Path) -> float:
    """Sum of every past gemini job's recorded `cost_usd` in
    throughput.jsonl — the budget is DURABLE across restarts, not an
    in-memory counter that forgets everything the moment the daemon
    restarts."""
    if not throughput_log.is_file():
        return 0.0
    try:
        text = throughput_log.read_text(errors="replace")
    except OSError:
        return 0.0
    total = 0.0
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except ValueError:
            continue
        if obj.get("channel") == "gemini":
            cost = obj.get("cost_usd")
            if isinstance(cost, (int, float)) and not isinstance(cost, bool):
                total += cost
    return total


class GeminiBudget:
    """Independent of the codex Detector on purpose (spec: the codex
    grumpiness detector does not gate gemini jobs). Latched, not
    de-escalating — a dollar cap does not reset itself the way a percentage
    meter resets on a rolling time window; once a run's spend reaches the
    cap it stays hit for the rest of that run."""

    def __init__(self, cap_usd: float, spent_so_far: float = 0.0):
        self.cap_usd = cap_usd
        self.spent_usd = spent_so_far
        self.hard_stop = spent_so_far >= cap_usd

    def note_spend(self, cost_usd: float) -> None:
        if cost_usd:
            self.spent_usd += cost_usd
        if self.spent_usd >= self.cap_usd:
            self.hard_stop = True

    def admission_blocked(self) -> bool:
        return self.hard_stop


# Specific throttle phrasing, not a bare "rate limited" substring — that
# loose a match collides with ordinary art-prompt vocabulary (a "rusted
# rate-limited valve" reskin prompt would trip it). "toomanyrequests" is
# camelCase and effectively never appears in natural English by accident.
RATE_LIMIT_MARKERS = ("toomanyrequests", "rate limit exceeded",
                      "was rate limited", "request was rate limited")


def _looks_rate_limited(text: str, prompt: str | None = None) -> bool:
    """Detect an explicit throttle refusal in the worker's captured stdout+
    stderr (and, at the call site, the worker's own -o last-message note —
    the spec names "-o last message" as a detection source, not just the
    raw transcript). Not a fully structured signal — codex_image.py has no
    field for "the account got throttled" distinct from its own raw output
    blob (do_image() dumps up to 2000 chars of it to stderr on ANY failure,
    --verbose or not) — so this is a best-effort text match, not the clean
    field lookup the ideal fix would use. Two mitigations against a false
    hard-stop: this job's own `prompt` — which that same dump routinely
    echoes back verbatim — is stripped out of the haystack first, and the
    remaining markers are specific throttle phrasing (see RATE_LIMIT_MARKERS)
    rather than anything a benign prompt could contain.
    """
    hay = text or ""
    if prompt:
        hay = hay.replace(prompt, "")
    hay = hay.lower()
    return any(marker in hay for marker in RATE_LIMIT_MARKERS)


# --------------------------------------------------------------------------
# queue mechanics
# --------------------------------------------------------------------------

def _priority_of(path: Path) -> int:
    try:
        return int(json.loads(path.read_text()).get("priority", 100))
    except (OSError, ValueError, TypeError):
        return 100


def _channel_of(path: Path) -> str:
    try:
        ch = json.loads(path.read_text()).get("channel") or "codex"
        return ch if isinstance(ch, str) else "codex"
    except (OSError, ValueError, TypeError):
        return "codex"


def claim_next(pending_dir: Path, active_dir: Path, channel_blocked=None) -> Path | None:
    """Atomic claim = rename pending/<id>.json -> active/<id>.json.

    `os.rename` removing the SOURCE is the atomic event: if another daemon
    renamed it away between our glob() and our rename(), the source is gone
    and rename raises FileNotFoundError — that daemon lost the race, moves on
    to the next candidate, and never touches the file the winner claimed.

    `channel_blocked(channel_str) -> bool`, if given, skips a candidate
    whose channel is currently gated (codex admission-blocked, or the
    gemini budget hard-stopped) WITHOUT skipping other candidates of the
    other channel — so a wedged codex account never stalls gemini jobs
    still sitting in the same queue, and vice versa.

    Two things happen right after a successful rename, both load-bearing:

    1. `os.utime(dest)` stamps a FRESH mtime. `os.rename` preserves the
       inode's existing mtime, so without this a job that sat in pending/
       for 20 minutes before being claimed would carry that 20-minute-old
       timestamp straight into active/ — and reconcile()'s age gate, which
       exists specifically to tell a crashed orphan from a live claim by
       age, would misread a job claimed one second ago as one stale enough
       to steal back.
    2. A re-stat of `dest` immediately after the rename, because production
       runs on /mnt/d (DrvFs/9p) — see `common.py`'s module docstring.
       Treating a stat that can't see what we just renamed as a lost race —
       the same as a FileNotFoundError on the rename itself — is the best
       mitigation available from user space; it is a mitigation, not a proof.
    """
    try:
        candidates = sorted(pending_dir.glob("*.json"), key=lambda p: (_priority_of(p), p.name))
    except OSError:
        return None
    for src in candidates:
        if channel_blocked is not None and channel_blocked(_channel_of(src)):
            continue
        dest = active_dir / src.name
        if dest.exists():
            continue  # a stray same-named file already claimed — never clobber it
        try:
            os.rename(src, dest)
        except FileNotFoundError:
            continue  # lost the race to another daemon
        try:
            os.utime(dest, None)
            dest.stat()
        except FileNotFoundError:
            continue  # a stale-read filesystem's rename that a stat can't see: lost race
        return dest
    return None


def _queue_empty(pending_dir: Path) -> bool:
    try:
        next(pending_dir.glob("*.json"))
        return False
    except StopIteration:
        return True


def _any_claimable(pending_dir: Path, channel_blocked) -> bool:
    """True if pending/ holds at least one job whose channel is not
    currently blocked — used to tell "genuinely nothing left to do" apart
    from "something's left, but every channel that could claim it is
    blocked right now", which used to hang --once forever whenever codex
    was wedged but unrelated gemini jobs (not blocked at all) were still
    sitting in the same queue: the old exhaustion check only looked at
    whether the (single) Detector was blocked, so a healthy gemini channel
    could never end the loop on its own."""
    try:
        for p in pending_dir.glob("*.json"):
            if not channel_blocked(_channel_of(p)):
                return True
    except OSError:
        pass
    return False


def reconcile(active_dir: Path, pending_dir: Path, done_dir: Path,
              failed_dir: Path, min_age_s: float = 600.0) -> list[tuple[str, str]]:
    """Crash recovery: an active/ job with no manifest anywhere MIGHT be an
    orphan from a killed daemon — or it might just be another live daemon's
    in-flight claim, which looks IDENTICAL (no manifest yet either) until it
    finishes. The only honest signal that distinguishes them is age: no
    single job can legitimately still be running past its own worst-case
    ceiling (an edit's --timeout-edit + the subprocess grace + the
    validator's own timeout + one row-1 retry), so `min_age_s` defaults
    comfortably above that. A job younger than this is left alone even with
    no manifest.

    A DIFFERENT crash state — active/<id>.json AND a matching
    done/failed/<id>.manifest.json BOTH exist, meaning the daemon wrote the
    manifest and died before moving the job file — is deliberately left
    alone here too (see the `continue` below): reconcile()'s job is telling
    a live claim from an orphan, not completing an already-decided outcome.
    `repair()` is the tool for that.
    """
    moved = []
    try:
        actives = sorted(active_dir.glob("*.json"))
    except OSError:
        return moved
    now = time.time()
    for p in actives:
        job_id = p.stem
        if (done_dir / f"{job_id}.manifest.json").is_file() or \
           (failed_dir / f"{job_id}.manifest.json").is_file():
            # Already terminally decided, just not moved — repair()'s job,
            # not reconcile()'s: guessing which of two manifests (if there
            # were ever two) is authoritative is worse than asking.
            continue
        try:
            age = now - p.stat().st_mtime
        except OSError:
            continue
        if age < min_age_s:
            continue  # too young to be confidently orphaned — may be live
        dest = pending_dir / p.name
        if dest.exists():
            continue
        try:
            os.rename(p, dest)
        except FileNotFoundError:
            continue
        try:
            dest.stat()
        except FileNotFoundError:
            continue  # see claim_next()'s docstring: a stale-read mount can
                      # report a rename a stat then can't see — lost race, not a move.
        moved.append((job_id, "no manifest in done/ or failed/"))
        stray = active_dir / f"{job_id}.worker_last_message.json"
        if stray.is_file():
            try:
                stray.unlink()
            except OSError:
                pass
    return moved


def repair(active_dir: Path, done_dir: Path, failed_dir: Path) -> list[tuple[str, str]]:
    """Complete the crash state reconcile() deliberately leaves alone: an
    active/<id>.json that's still sitting there because the daemon died
    between writing done/<id>.manifest.json (or failed/) and moving the job
    file — one, unambiguous manifest already says the outcome, so finishing
    the move is not a guess. If manifests exist on BOTH sides (should never
    happen — a job is filed to exactly one target directory — but if it
    does, that IS genuinely ambiguous) this leaves it alone for a human.
    """
    repaired = []
    try:
        actives = sorted(active_dir.glob("*.json"))
    except OSError:
        return repaired
    for p in actives:
        job_id = p.stem
        done_manifest = done_dir / f"{job_id}.manifest.json"
        failed_manifest = failed_dir / f"{job_id}.manifest.json"
        if done_manifest.is_file() and failed_manifest.is_file():
            continue  # genuinely ambiguous — leave for a human
        if done_manifest.is_file():
            target_dir = done_dir
        elif failed_manifest.is_file():
            target_dir = failed_dir
        else:
            continue  # no manifest anywhere — that's reconcile()'s job, not repair's
        dest = target_dir / p.name
        if dest.exists():
            continue
        try:
            os.rename(p, dest)
        except FileNotFoundError:
            continue
        try:
            dest.stat()
        except FileNotFoundError:
            continue
        repaired.append((job_id, f"completed the move into {target_dir.name}/ "
                                  f"(its manifest already existed there)"))
    return repaired


# --------------------------------------------------------------------------
# running one job
# --------------------------------------------------------------------------

class RunCtx:
    """Immutable-for-the-run configuration handed to every worker thread —
    except the codex_home leases, which are acquired LAZILY (see
    codex_home_for_slot below), one per slot, on that slot's FIRST codex
    job. A gemini-only run therefore never creates a single codex_home
    directory, never risks the one-time UAC-gated sandbox setup prompt for
    a brand-new one, and "a gemini job never touches codex homes" is true
    at the whole-daemon level, not just within process_gemini_job."""

    def __init__(self, worker_script, validator_script, manifest_schema,
                 artsrc_dir, active_dir, codex_home_root, workers_count,
                 timeout_generate, timeout_edit, reasoning_effort, verbose, slots,
                 gemini_worker_script, gemini_timeout):
        self.worker_script = worker_script
        self.validator_script = validator_script
        self.manifest_schema = manifest_schema
        self.artsrc_dir = artsrc_dir
        self.active_dir = active_dir
        self.codex_home_root = codex_home_root
        self.timeout_generate = timeout_generate
        self.timeout_edit = timeout_edit
        self.reasoning_effort = reasoning_effort
        self.verbose = verbose
        self.slots = slots  # queue.Queue of free worker-slot ints (codex channel only)
        self.gemini_worker_script = gemini_worker_script
        self.gemini_timeout = gemini_timeout
        # No `dry_run` field: --dry-run is handled entirely in main()'s
        # run_dry_run(), before a RunCtx is ever built.

        self._codex_homes: list[Path | None] = [None] * workers_count
        self.lease_handles: list = []  # closed by main() at shutdown
        self._lease_lock = threading.Lock()

    def codex_home_for_slot(self, slot: int) -> Path:
        """Acquire (once) and cache the leased codex_home for this slot.
        Guarded by a lock: two threads could in principle race to be the
        FIRST codex job on the same never-yet-used slot (unlikely — a slot
        is only handed to one thread at a time via ctx.slots — but this is
        the cheap, correct way to be sure rather than relying on that)."""
        with self._lease_lock:
            if self._codex_homes[slot] is None:
                home, fh = common.acquire_codex_home_lease(self.codex_home_root)
                self._codex_homes[slot] = home
                self.lease_handles.append(fh)
            return self._codex_homes[slot]


def build_job_prompt(job: dict) -> str:
    """A REAL per-job scratch directory (_artsrc/<job_id>/) is what makes
    the "your working directory is per-job scratch space" claim in
    AGENTS.md true — codex_image.py sets its subprocess's cwd to the output
    file's parent, so out_png living inside _artsrc/<job_id>/ IS that
    per-job cwd, not the shared _artsrc/ root every job used to collide in."""
    canvas = job["canvas"]
    parts = [f"[artpipe job {job['id']}] {job['prompt']}",
             f"Canvas: exactly {canvas['width']}x{canvas['height']} pixels."]
    bg = job.get("background") or "transparent"
    if bg == "transparent":
        parts.append("Background: a genuinely transparent alpha channel — "
                      "no backdrop, floor, shadow or gradient.")
    else:
        parts.append(f"Background: one perfectly flat solid field of {bg}, "
                      f"used nowhere in the subject.")
    if job.get("style_notes"):
        parts.append(f"Style: {job['style_notes']}")
    if job.get("facing"):
        parts.append(f"Facing: {job['facing']}.")
    return " ".join(parts)


def run_worker(worker_script: Path, subcmd: str, prompt: str, out_png: Path,
                codex_home: Path, timeout: int, schema_path: Path,
                last_msg_path: Path, reference, model, reasoning_effort,
                verbose: bool) -> tuple[int, str, str, float, bool]:
    cmd = [sys.executable, str(worker_script), subcmd,
           "--prompt", prompt, "--out", str(out_png),
           "--codex-home", str(codex_home), "--timeout", str(timeout),
           "--force", "--reasoning-effort", reasoning_effort,
           "--output-schema", str(schema_path),
           "--output-last-message", str(last_msg_path)]
    if model:
        cmd += ["--model", model]
    if reference:
        cmd += ["--image", str(reference)]
    if verbose:
        cmd.append("--verbose")

    started = time.monotonic()
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True,
                               timeout=timeout + WORKER_SUBPROCESS_GRACE_S)
        return proc.returncode, proc.stdout, proc.stderr, time.monotonic() - started, False
    except subprocess.TimeoutExpired as exc:
        out = exc.stdout.decode() if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        err = exc.stderr.decode() if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return 124, out, err, time.monotonic() - started, True


_GEMINI_MODEL_RE = re.compile(r"model=([^,\s]+)")


def run_gemini_worker(worker_script: Path, prompt: str, out_png: Path, reference,
                       model: str, timeout: int) -> tuple[int, str, str, float, bool]:
    """gemini_image.py's CLI is much thinner than codex_image.py's: no
    --codex-home, no --output-schema/-o, no per-job structured reply — just
    `generate --prompt --out [--ref ...] --model`, a plain success line to
    stdout, or a sys.exit() message to stderr on failure."""
    cmd = [sys.executable, str(worker_script), "generate",
           "--prompt", prompt, "--out", str(out_png), "--model", model]
    if reference:
        cmd += ["--ref", str(reference)]
    started = time.monotonic()
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return proc.returncode, proc.stdout, proc.stderr, time.monotonic() - started, False
    except subprocess.TimeoutExpired as exc:
        out = exc.stdout.decode() if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        err = exc.stderr.decode() if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        return 124, out, err, time.monotonic() - started, True


def run_validator(validator_script: Path, reference, candidate: Path):
    """Returns (verdict, findings). verdict is one of:
      None              — skipped, no reference on this job (never a silent pass)
      "pass"             — validate_sprite.py exit 0
      "reject"           — exit 1: the IMAGE is not shippable
      "cannot_validate"  — exit 2 (or anything else): the INPUT was unusable
                            (e.g. a missing/unreadable reference path) — a
                            data problem on the job, never the same thing as
                            the worker having produced a bad image, and must
                            never be reported to the owner as an art-quality
                            rejection.
    """
    if not reference:
        return None, ["no reference on this job — validator skipped, not a pass"]
    proc = subprocess.run(
        [sys.executable, str(validator_script), "--reference", str(reference),
         "--candidate", str(candidate)],
        capture_output=True, text=True, timeout=60)
    findings = (proc.stdout + proc.stderr).strip().splitlines()
    if proc.returncode == 0:
        return "pass", findings
    if proc.returncode == 1:
        return "reject", findings
    return "cannot_validate", findings


def _check_size_and_validate(result: dict, job: dict, reference, out_png: Path,
                              validator_script: Path) -> dict:
    """Common tail for BOTH channels once a real image file exists: read its
    ACTUAL dimensions — the image tool is KNOWN to ignore requested size
    (design addendum §2.3; this is the NORMAL case, not an edge case) — and
    compare against job['canvas']. A size mismatch is its own failure kind,
    checked and reported BEFORE the validator runs at all, so a
    reference-less job (which the validator skips entirely) can no longer
    accept ANY returned image as "ok" just because there was nothing to
    reject it."""
    try:
        info = codex_image.png_info(out_png)
    except (ValueError, OSError) as exc:
        result.update(status="failed", worker_status="unreadable_png", validator="not_run",
                       note=f"could not read the returned file's PNG header: {exc}")
        return result
    result["width"] = info["width"]
    result["height"] = info["height"]

    canvas = job["canvas"]
    if (info["width"], info["height"]) != (canvas["width"], canvas["height"]):
        result.update(status="failed", worker_status="size_mismatch", validator="not_run",
                       note=f"returned {info['width']}x{info['height']}, job asked for "
                            f"{canvas['width']}x{canvas['height']} — the image tool is known "
                            f"to ignore requested size; never a silent ok, reference or not")
        return result

    verdict, findings = run_validator(validator_script, reference, out_png)
    result["validator_findings"] = findings
    if verdict == "reject":
        result.update(status="failed", worker_status="worker_reported_ok_but_invalid",
                       validator="REJECT",
                       note="validate_sprite.py rejected the returned file — "
                            "the worker's own manifest is never trusted")
        return result
    if verdict == "cannot_validate":
        # exit 2: the INPUT was unusable (e.g. a missing/unreadable
        # reference path) — a data problem on the JOB, not the same failure
        # as the worker having produced a bad image.
        result.update(status="failed", worker_status="bad_reference_path",
                       validator="CANNOT_VALIDATE",
                       note="validate_sprite.py could not judge this at all "
                            "(exit 2, unusable input) — most likely a bad or "
                            "missing reference path on the job, not an image defect")
        return result

    result.update(status="ok", worker_status="ok",
                   validator=("PASS" if verdict == "pass" else "skipped"),
                   note="validated" if verdict == "pass" else "no reference to validate against")
    return result


def process_codex_job(job: dict, job_id: str, reference, out_png: Path, ctx: RunCtx) -> dict:
    """Runs in a worker thread. Returns a result dict; touches no shared
    detector/file-move state — the caller does that after collecting the
    future, so nothing here needs a lock."""
    is_edit = bool(reference)
    subcmd = "edit" if is_edit else "generate"
    timeout = ctx.timeout_edit if is_edit else ctx.timeout_generate
    last_msg_path = ctx.active_dir / f"{job_id}.worker_last_message.json"

    slot = ctx.slots.get()
    try:
        # Lazily leased on this slot's FIRST codex job (a bounded pool of
        # "w0".."w<N-1>" directories via a cross-process flock, never one
        # per pid — restarts don't accumulate homes, or UAC prompts for a
        # brand-new one, forever — and never shared with another daemon,
        # openai/codex #11435). A run with no codex jobs never acquires one.
        codex_home = ctx.codex_home_for_slot(slot)
        meter_before = codex_grumpiness.read_meters(codex_home)
        prompt = build_job_prompt(job)

        job_started_at = time.time()
        attempts = 0
        code = out = err = None
        timed_out = False
        elapsed_total = 0.0
        while True:
            attempts += 1
            # A stale PNG/manifest at these exact paths, left by a PREVIOUS
            # attempt (this retry, or a requeue after a fix), must never be
            # mistaken for THIS attempt's output.
            for stale in (out_png, last_msg_path):
                try:
                    stale.unlink()
                except FileNotFoundError:
                    pass
            code, out, err, elapsed, timed_out = run_worker(
                ctx.worker_script, subcmd, prompt, out_png, codex_home, timeout,
                ctx.manifest_schema, last_msg_path, reference, job.get("model"),
                ctx.reasoning_effort, ctx.verbose)
            elapsed_total += elapsed
            combined = (out or "") + (err or "")
            failed = (code != 0) or timed_out
            rate_limited_now = failed and _looks_rate_limited(combined, prompt)
            if not failed or rate_limited_now or attempts >= MAX_CODEX_ATTEMPTS:
                break
            # Retryable: a genuine tool error or timeout, NOT a throttle
            # refusal — row 1 spec allows exactly one retry.
    finally:
        # Acquisition-to-release is ALL inside this try — a mkdir/read
        # failure, a malformed job, or any other exception in between still
        # returns the slot. An exception here used to leak the slot
        # permanently; with -N 1 that deadlocked the daemon with no SIGTERM
        # escape (queue.Queue.get() has no timeout).
        ctx.slots.put(slot)

    # `after_mtime=job_started_at` is the fix for a real bug: without a
    # floor, a worker that died before writing its own rollout would leave
    # read_meters() reading whatever this codex_home last wrote for a
    # PREVIOUS job, misattributing its meters to this one.
    meter_after = codex_grumpiness.read_meters(codex_home, after_mtime=job_started_at)

    manifest_present = last_msg_path.is_file()
    worker_self_report = None
    if manifest_present:
        try:
            worker_self_report = json.loads(last_msg_path.read_text())
        except (OSError, ValueError):
            worker_self_report = None
    # The -o last-message file's content now participates in row 1
    # detection (the spec names it as a source), not just the raw
    # stdout/stderr transcript — a worker that wrote a schema-valid
    # "refused" manifest whose note names a throttle is caught here too.
    worker_note = str(worker_self_report.get("note") or "") if isinstance(worker_self_report, dict) else ""
    text = (out or "") + (err or "") + " " + worker_note

    result = {"id": job_id, "channel": "codex", "elapsed_s": elapsed_total,
              "timed_out": timed_out, "meter_before": meter_before,
              "meter_after": meter_after, "daemon_attempts": attempts,
              "worker_self_report": worker_self_report}

    if _looks_rate_limited(text, prompt):
        result.update(status="failed", worker_status="rate_limited",
                       validator="not_run", detector_row=1,
                       note="TooManyRequests / rate limited — hard stop, "
                            "drain queue (row 1)")
        return result

    image_present = out_png.is_file()

    if code != 0 or timed_out:
        result.update(status="failed", worker_status="worker_error",
                       validator="not_run",
                       note=(f"worker exited {code}, image_present={image_present} — "
                             f"a failed/timed-out run is never trusted regardless"
                             + (" (timed out)" if timed_out else "")
                             + (f", {attempts} attempt(s)" if attempts > 1 else "")))
        return result

    if not image_present:
        if manifest_present:
            result.update(status="failed", worker_status="worker_reported_fail",
                           validator="not_run",
                           note="exit 0, a manifest exists, but no image — "
                                "the worker reported failure/refusal honestly")
        else:
            # Row 5: exit 0 with no manifest and no image is the `--`-trap
            # no-op — fail THIS request, never the account.
            result.update(status="failed", worker_status="no_manifest",
                           validator="not_run", detector_row=5,
                           note="exit 0, no manifest, no image — the `--` "
                                "no-op (row 5): fails the request, not the account")
        return result

    return _check_size_and_validate(result, job, reference, out_png, ctx.validator_script)


def process_gemini_job(job: dict, job_id: str, reference, out_png: Path, ctx: RunCtx) -> dict:
    """Never touches ctx.slots or a codex_home — the codex grumpiness
    detector does not gate this channel at all (spec); admission is via
    GeminiBudget in the main loop instead."""
    prompt = build_job_prompt(job)
    try:
        out_png.unlink()
    except FileNotFoundError:
        pass

    model = job.get("model") or DEFAULT_GEMINI_MODEL
    code, out, err, elapsed, timed_out = run_gemini_worker(
        ctx.gemini_worker_script, prompt, out_png, reference, model, ctx.gemini_timeout)

    m = _GEMINI_MODEL_RE.search(out or "")
    actual_model = m.group(1) if m else model
    # Only a genuinely successful call is billable — a nonzero exit means
    # gemini_image.py's own sys.exit fired before an image was written,
    # which is the one case this does NOT charge for.
    cost_usd = _gemini_model_cost(actual_model) if code == 0 else 0.0

    result = {"id": job_id, "channel": "gemini", "elapsed_s": elapsed,
              "timed_out": timed_out, "model": actual_model, "cost_usd": cost_usd,
              "meter_before": None, "meter_after": None, "daemon_attempts": 1}

    if code != 0 or timed_out:
        result.update(status="failed", worker_status="worker_error", validator="not_run",
                       note=(f"gemini worker exited {code}"
                             + (" (timed out)" if timed_out else "")
                             + (f": {err.strip()[-200:]}" if err else "")))
        return result

    if not out_png.is_file():
        result.update(status="failed", worker_status="no_manifest", validator="not_run",
                       note="exit 0 but no image was written")
        return result

    return _check_size_and_validate(result, job, reference, out_png, ctx.validator_script)


def process_job(job_path: Path, ctx: RunCtx) -> dict:
    try:
        job = common.load_job(job_path)
    except common.JobError as exc:
        return {"id": job_path.stem, "channel": "codex", "status": "failed", "note": str(exc),
                "worker_status": "bad_job_file", "validator": "not_run"}

    job_id = job["id"]
    channel = job.get("channel") or "codex"
    reference = job.get("reference")
    job_scratch = ctx.artsrc_dir / job_id  # a REAL per-job scratch dir — see build_job_prompt()
    out_png = job_scratch / f"{job_id}.png"

    if channel == "gemini":
        return process_gemini_job(job, job_id, reference, out_png, ctx)
    if channel != "codex":
        return {"id": job_id, "channel": channel, "status": "failed",
                "worker_status": "bad_job_file", "validator": "not_run",
                "note": f"unknown channel {channel!r} — only 'codex' or 'gemini'"}
    return process_codex_job(job, job_id, reference, out_png, ctx)


def finalize_job(job_path: Path, result: dict, done_dir: Path, failed_dir: Path,
                  active_dir: Path, throughput_log: Path, detector: Detector,
                  gemini_budget: GeminiBudget, configured_n: int) -> None:
    job_id = result.get("id", job_path.stem)
    channel = result.get("channel", "codex")
    ok = result.get("status") == "ok"
    target_dir = done_dir if ok else failed_dir

    dest_job = target_dir / f"{job_id}.json"
    manifest_path = target_dir / f"{job_id}.manifest.json"
    common.atomic_write_json(manifest_path, result)
    try:
        os.replace(job_path, dest_job)
    except FileNotFoundError:
        # job_path vanished from under us — never let one job's bookkeeping
        # surprise crash the whole daemon and abandon everything else it
        # was running. `--repair` completes this exact state afterward.
        print(f"artpiped: WARNING {job_id}'s active/ file disappeared before "
              f"it could be filed to {target_dir.name}/ — manifest written, "
              f"job file itself is now unaccounted for (run --repair)", file=sys.stderr)

    stray = active_dir / f"{job_id}.worker_last_message.json"
    if stray.is_file():
        try:
            stray.unlink()
        except OSError:
            pass

    common.append_jsonl(throughput_log, {
        "ts": time.time(), "id": job_id, "channel": channel,
        "status": result.get("status"),
        "worker_status": result.get("worker_status"),
        "elapsed_s": result.get("elapsed_s"),
        "validator": result.get("validator"),
        "meter_before": result.get("meter_before"),
        "meter_after": result.get("meter_after"),
        "cost_usd": result.get("cost_usd"),
        "model": result.get("model"),
        "daemon_attempts": result.get("daemon_attempts"),
    })

    if channel == "gemini":
        gemini_budget.note_spend(result.get("cost_usd") or 0.0)
        return  # the codex Detector never sees a gemini job's numbers at all

    if result.get("detector_row") == 1:
        detector.note_rate_limited()
    detector.note_meters(result.get("meter_after"))
    if result.get("elapsed_s") is not None:
        detector.note_wall_clock(result["elapsed_s"], configured_n)


# --------------------------------------------------------------------------
# main loop
# --------------------------------------------------------------------------

def parse_args(argv=None) -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--pending-dir", type=Path, default=common.DEFAULT_PENDING)
    ap.add_argument("--active-dir", type=Path, default=common.DEFAULT_ACTIVE)
    ap.add_argument("--done-dir", type=Path, default=common.DEFAULT_DONE)
    ap.add_argument("--failed-dir", type=Path, default=common.DEFAULT_FAILED)
    ap.add_argument("--artsrc-dir", type=Path, default=common.DEFAULT_ARTSRC)
    ap.add_argument("--throughput-log", type=Path, default=common.DEFAULT_THROUGHPUT_LOG)
    ap.add_argument("--codex-home-root", type=Path, default=common.DEFAULT_CODEX_HOME_ROOT)
    ap.add_argument("--worker-script", type=Path,
                     default=Path(os.environ.get("ARTPIPE_WORKER_SCRIPT",
                                                   str(common.DEFAULT_WORKER_SCRIPT))))
    ap.add_argument("--gemini-worker-script", type=Path,
                     default=Path(os.environ.get("ARTPIPE_GEMINI_WORKER_SCRIPT",
                                                   str(common.DEFAULT_GEMINI_WORKER_SCRIPT))))
    ap.add_argument("--gemini-budget-usd", type=float, default=DEFAULT_GEMINI_BUDGET_USD,
                     help="hard-stop the gemini channel once its cumulative cost — "
                          "read from throughput.jsonl, durable across restarts — "
                          "reaches this")
    ap.add_argument("--gemini-timeout", type=int, default=DEFAULT_GEMINI_TIMEOUT_S)
    ap.add_argument("--validator-script", type=Path, default=common.DEFAULT_VALIDATOR)
    ap.add_argument("--manifest-schema", type=Path, default=common.MANIFEST_SCHEMA)
    ap.add_argument("-N", "--workers", type=int, default=3)
    ap.add_argument("--timeout-generate", type=int, default=DEFAULT_TIMEOUT_GENERATE_S)
    ap.add_argument("--timeout-edit", type=int, default=DEFAULT_TIMEOUT_EDIT_S)
    ap.add_argument("--reasoning-effort", default="low")
    ap.add_argument("--poll-interval", type=float, default=2.0)
    ap.add_argument("--once", action="store_true",
                     help="drain what's claimable now, then exit — for scripts/tests")
    ap.add_argument("--dry-run", action="store_true",
                     help="report what pending/ would run and exit — reads "
                          "only, never claims, reconciles, or moves anything")
    ap.add_argument("--reconcile-only", action="store_true",
                     help="run crash reconciliation (and --repair) and exit")
    ap.add_argument("--repair", action="store_true",
                     help="complete a crash caught between writing a manifest and "
                          "moving the job file (active/<id>.json + a matching "
                          "done/failed manifest, no ambiguity) — folded automatically "
                          "into --reconcile-only, or run alone")
    ap.add_argument("--reconcile-min-age", type=float, default=600.0,
                     help="seconds an active/ job with no manifest must sit "
                          "untouched before reconcile() treats it as an orphan "
                          "rather than another live daemon's in-flight claim "
                          "(default comfortably above --timeout-edit's worst case)")
    ap.add_argument("--verbose", action="store_true")
    return ap.parse_args(argv)


def run_dry_run(args: argparse.Namespace) -> int:
    """Report what WOULD run, touching nothing — not even reconcile(), which
    can move a file, and --dry-run promises it never does."""
    try:
        candidates = sorted(args.pending_dir.glob("*.json"),
                            key=lambda p: (_priority_of(p), p.name))
    except OSError:
        candidates = []

    if not candidates:
        print("artpiped: --dry-run, nothing pending")
        return 0

    for p in candidates:
        try:
            job = common.load_job(p)
        except common.JobError as exc:
            print(f"would FAIL to claim {p.name}: {exc}")
            continue
        channel = job.get("channel") or "codex"
        is_edit = bool(job.get("reference"))
        subcmd = "edit" if is_edit else "generate"
        out_png = args.artsrc_dir / job["id"] / f"{job['id']}.png"
        print(f"would claim {p.name} [{channel}]: {subcmd} -> {out_png}")
        if args.verbose:
            print(f"    prompt: {build_job_prompt(job)}")

    print(f"\nartpiped: --dry-run, {len(candidates)} job(s) would be claimed — "
          f"pending/ left untouched, no worker spawned")
    return 0


def main(argv=None) -> int:
    args = parse_args(argv)
    common.ensure_queue_dirs(args.pending_dir, args.active_dir, args.done_dir,
                              args.failed_dir, args.artsrc_dir)

    if args.dry_run:
        return run_dry_run(args)

    fixed: list[tuple[str, str]] = []
    if args.repair or args.reconcile_only:
        fixed = repair(args.active_dir, args.done_dir, args.failed_dir)
        for job_id, why in fixed:
            print(f"artpiped: repaired {job_id} — {why}")
        if args.repair and not args.reconcile_only:
            print(f"artpiped: repair-only, {len(fixed)} job(s) completed")
            return 0

    moved = reconcile(args.active_dir, args.pending_dir, args.done_dir,
                       args.failed_dir, args.reconcile_min_age)
    for job_id, why in moved:
        print(f"artpiped: reconciled {job_id} — {why} — returned to pending/")

    if args.reconcile_only:
        print(f"artpiped: reconcile-only, {len(moved)} job(s) recovered, "
              f"{len(fixed)} repaired")
        return 0

    slots: "queue.Queue[int]" = queue.Queue()
    for i in range(args.workers):
        slots.put(i)

    gemini_spent = read_gemini_spend(args.throughput_log)
    gemini_budget = GeminiBudget(args.gemini_budget_usd, gemini_spent)
    if gemini_budget.hard_stop:
        print(f"artpiped: gemini channel already at/over its ${args.gemini_budget_usd:.2f} "
              f"budget (${gemini_spent:.2f} spent, per throughput.jsonl) — gemini jobs "
              f"will not be claimed this run", file=sys.stderr)

    # codex_home leases are NOT acquired here — RunCtx acquires each slot's
    # lease lazily, on that slot's first CODEX job (see codex_home_for_slot).
    # A run that only ever processes gemini jobs therefore never creates a
    # single codex_home directory.
    ctx = RunCtx(args.worker_script, args.validator_script, args.manifest_schema,
                 args.artsrc_dir, args.active_dir, args.codex_home_root, args.workers,
                 args.timeout_generate, args.timeout_edit, args.reasoning_effort,
                 args.verbose, slots, args.gemini_worker_script, args.gemini_timeout)
    detector = Detector()
    stop_event = threading.Event()

    def _handle_signal(signum, _frame):
        print(f"artpiped: signal {signum} received, draining in-flight work then exiting",
              file=sys.stderr)
        stop_event.set()

    signal.signal(signal.SIGTERM, _handle_signal)
    signal.signal(signal.SIGINT, _handle_signal)

    def _channel_permanently_blocked(ch: str) -> bool:
        if ch == "gemini":
            return gemini_budget.admission_blocked()
        return detector.admission_blocked()

    try:
        with ThreadPoolExecutor(max_workers=args.workers) as pool:
            futures: dict = {}  # future -> (job_path, channel)
            while True:
                if not stop_event.is_set():
                    while len(futures) < args.workers:
                        codex_in_flight = sum(1 for _, ch in futures.values() if ch == "codex")
                        current_codex_n = detector.current_n(args.workers)

                        def _claim_blocked(ch, _in_flight=codex_in_flight, _cap=current_codex_n):
                            if ch == "gemini":
                                return gemini_budget.admission_blocked()
                            return detector.admission_blocked() or _in_flight >= _cap

                        job_path = claim_next(args.pending_dir, args.active_dir,
                                              channel_blocked=_claim_blocked)
                        if job_path is None:
                            break
                        ch = _channel_of(job_path)
                        futures[pool.submit(process_job, job_path, ctx)] = (job_path, ch)

                if not futures:
                    exhausted = (_queue_empty(args.pending_dir) or
                                not _any_claimable(args.pending_dir, _channel_permanently_blocked))
                    if stop_event.is_set() or (args.once and exhausted):
                        break
                    time.sleep(args.poll_interval)
                    continue

                done, _ = wait(list(futures.keys()), timeout=args.poll_interval,
                               return_when=FIRST_COMPLETED)
                for fut in done:
                    job_path, _ch = futures.pop(fut)
                    try:
                        result = fut.result()
                    except Exception as exc:  # never let a worker-thread crash kill the daemon
                        result = {"id": job_path.stem, "status": "failed",
                                  "note": f"process_job raised: {type(exc).__name__}: {exc}"}
                    finalize_job(job_path, result, args.done_dir, args.failed_dir,
                                 args.active_dir, args.throughput_log, detector,
                                 gemini_budget, args.workers)

                if stop_event.is_set() and not futures:
                    break
                if args.once and not futures and _queue_empty(args.pending_dir):
                    break
    finally:
        for fh in ctx.lease_handles:
            try:
                fh.close()
            except OSError:
                pass

    # Finding 5: a hard stop / budget wedge with real work left behind is a
    # DIFFERENT outcome from a clean drain (queue empty) or a deliberate
    # SIGTERM stop with healthy, unblocked work simply not yet started —
    # the latter is not abandonment, it is exactly what was asked for.
    pending_remaining = not _queue_empty(args.pending_dir)
    wedged = detector.hard_stop or detector.stop_all or gemini_budget.hard_stop
    abandoned = wedged or (pending_remaining and
                           (detector.admission_blocked() or gemini_budget.admission_blocked()))
    exit_code = 1 if abandoned else 0
    print(f"artpiped: stopped. hard_stop={detector.hard_stop} refuse_new={detector.refuse_new} "
          f"stop_all={detector.stop_all} gemini_hard_stop={gemini_budget.hard_stop} "
          f"gemini_spent=${gemini_budget.spent_usd:.2f} pending_remaining={pending_remaining} — "
          f"{'ABANDONED WORK' if abandoned else 'CLEAN DRAIN'} (exit {exit_code})")
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
