"""validation.py -- modcheck suite for RimMandrake Planet Preset Prime
(mandrake.rm.planetpresetprime).

Dev-ergonomics-only mod, not player-facing (own About.xml's own words).
One file, `PlanetPresetPrime.cs`, read whole before writing this: a static
constructor that logs a boot line and patches Harmony into the executing
assembly, plus one `[HarmonyPatch(typeof(Page_CreateWorldParams), "Reset")]`
postfix that primes `planetCoverage=1.0f` (reflectively, the field is
private) and, if My Little Planet's `WorldGenRules.WorldGenRules.subcount`
type/field resolve, primes that too (also reflective, MLP is a private
type), then sets `PlanetLayerSettingsDefOf.Surface.settings.subdivisions=7`
unconditionally. No XML defs, no `ModSettings` class anywhere in the mod
(the two constants `Coverage`/`Subdivisions` are compile-time `const
float`/`const int`, nothing a player or a settings window could ever
touch) -- `suite.toggles = []`, every component `beyond_toggle=True`.

`oblitus.mylittleplanet` IS in the minimal list (grepped directly:
`infrastructure/state/modlists/ModsConfig.MINIMAL.xml` carries it), unlike
the third-party donors MandrakePatches/MenuShell needed and did not have --
so the walk doc's own `list: minimal+mylittleplanet` requirement is
already satisfied by a plain `modcheck run PlanetPresetPrime`, and MLP
SHOULD resolve as "found" in the boot line's own report.

A REAL, WHOLE-MECHANISM FLOOR GAP -- not found by guessing, found by
searching the actual tool surface before writing a component that assumes
one exists: this mod's ENTIRE point is a Harmony postfix on
`Page_CreateWorldParams.Reset()`, the world-creation PAGE's own reset
method. `Transient/bench_tools_dump.json` has exactly three tools whose
name contains "world" and "info"/"stats" (`jawa/world_info_get`,
`jawa/world_info_set`, `jawa/world_stats`) -- NONE of them opens, drives,
or in any way triggers `Page_CreateWorldParams`, and no debug-action route
to it was found either (the walk doc's own step 2 flags this exact
uncertainty and asks whoever runs it to "confirm the correct trigger"
first). Worse: a `modcheck` `Session` connects to an ALREADY-`Playing`
quicktest map (`rimdrive.Session`'s own boot sequence, per every other
suite in this backfill wave) -- by the time any chain function here could
call a bridge tool, a world already exists, generated by whatever path the
quicktest bootstrap actually used, which is NOT traceable from this mod's
own source to be the `Page_CreateWorldParams` UI flow at all (out of this
mod's own scope to answer; a JawaBench/quicktest-bootstrap question, not a
PlanetPresetPrime one). So the walk doc's steps 2-5 -- opening the page,
reading back the primed `planetCoverage`/`subdivisions` fields, generating
a world from the primed page and checking its tile count is 21872 -- have
NO LIVE HOOK in this suite's environment at all. This is the mod's entire
mechanism, left genuinely uncovered rather than faked with a component
that assumes a trigger this suite could not find.

WHAT IS LEFT, AND IS REAL: the static constructor's own boot line (walk
doc step 1) runs at `LoadedModManager.LoadAllActiveMods` time, unconditional
on the page ever opening -- the mod's OWN comment says exactly why this
line exists ("A mod that writes nothing at load is indistinguishable from a
mod that failed to load at all... So say so at STARTUP, not only when the
page opens"). This is the one thing this suite can actually prove: the
assembly loaded, Harmony patched clean, and (since MLP is in the minimal
list) the MLP type-probe found `WorldGenRules.WorldGenRules`.

Still not proven / likely first-live-run corrections:
  1. Whether `jawa/drain_log` still holds this boot-time line by the time a
     quicktest chain gets to read it -- same timing concern RustChrome's
     own docstring flags for its own static-ctor line, and PlanetPresetPrime's
     runs even earlier in the boot sequence (before any Harmony patch on
     `Page_CreateWorldParams` could possibly have fired, since that patch
     is applied by the SAME static constructor this line is inside of).
     Untested live.
  2. If a future bridge tool DOES open `Page_CreateWorldParams` or drive a
     world-creation flow, this suite should grow the `ready` line, the
     `planetCoverage`/`subdivisions` read-back, and the `jawa/world_stats`
     21872-tile end-to-end proof the walk doc's own step 4 calls "the
     actual end-to-end proof the priming worked" -- filed as the gap this
     validator leaves, not silently dropped.
"""
from modcheck import Suite, ExpectationFailed

suite = Suite("PlanetPresetPrime")
suite.toggles = []   # no Source/ ModSettings class, no XML defs -- every
                      # component beyond_toggle

BOOT_LOG_TAG = "[RimMandrake.PlanetPresetPrime] loaded:"


# ---- PLANETPRESETPRIME_COVERAGE_GAPS_1 (offline half, round 41) -------------------------------------------------
# The mechanism has no live hook (see the docstring), but every NAME and SIGNATURE it depends on can be checked against
# the decompiled engine (reference tree dated 2026-08-19) and My Little Planet's own source: a rename in a game update
# turns the postfix into a silent no-op or a Harmony error, and the mod only warns at runtime.
import glob as _glob
import os as _os
import re as _re

_HERE = _os.path.dirname(_os.path.abspath(__file__))
DECOMPILED = "/mnt/d/Luke/dev/reference/rimworld-decompiled"
_WORKSHOP = "/mnt/c/Program Files (x86)/Steam/steamapps/workshop/content/294100"


def mlp_source_dir():
    for about in _glob.glob(_WORKSHOP + "/*/About/About.xml"):
        try:
            if "<packageid>oblitus.mylittleplanet</packageid>" in open(about, encoding="utf-8-sig", errors="replace").read().lower():
                d = _os.path.join(_os.path.dirname(_os.path.dirname(about)), "Source")
                return d if _os.path.isdir(d) else None
        except OSError:
            continue
    return None


def _rd(*parts):
    return open(_os.path.join(*parts), encoding="utf-8", errors="replace").read()


def mod_findings(cs):
    out = []
    cov = _re.search(r"public const float Coverage\s*=\s*([0-9.]+)f;", cs)
    sub = _re.search(r"public const int\s+Subdivisions\s*=\s*(\d+);", cs)
    if not cov or float(cov.group(1)) != 1.0 or not sub or int(sub.group(1)) != 7:
        out.append("primed constants are not coverage 1.0 / subdivisions 7 (the 21,872-tile Ash'karr grid): %s / %s" % (cov and cov.group(1), sub and sub.group(1)))
    if '[HarmonyPatch(typeof(Page_CreateWorldParams), "Reset")]' not in cs or "[HarmonyPostfix]" not in cs:
        out.append("the patch is no longer a postfix on Page_CreateWorldParams.Reset")
    for need in ('AccessTools.Field(typeof(Page_CreateWorldParams), "planetCoverage")', 'AccessTools.TypeByName("WorldGenRules.WorldGenRules")',
                 'AccessTools.Field(t, "subcount")', "f.FieldType == typeof(int)", "PlanetLayerSettingsDefOf.Surface"):
        if need not in cs:
            out.append("mod source lost `%s`" % need)
    if "[StaticConstructorOnStartup]" not in cs or "loaded: will prime coverage" not in cs:
        out.append("the startup boot line / StaticConstructorOnStartup is gone (the mod would look unloaded)")
    i_mlp, i_van = cs.find("f.SetValue(null, n)"), cs.find("surface.settings.subdivisions = n")
    if not (0 < i_mlp < i_van):
        out.append("the MLP slider field must be set BEFORE the vanilla subdivisions (MLP's slider re-stamps its own value)")
    return out


def engine_findings(page_cs, layer_cs, def_cs, defof_cs, coverage, subdivisions):
    out = []
    if len(_re.findall(r"public void Reset\(\)", page_cs)) != 1 or _re.search(r"void Reset\([^)]", page_cs):
        out.append("Page_CreateWorldParams.Reset is gone, overloaded, or no longer public void Reset()")
    if not _re.search(r"private float planetCoverage;", page_cs):
        out.append("Page_CreateWorldParams.planetCoverage is no longer a private float (the reflective set would miss)")
    body = _re.search(r"public void Reset\(\)\s*\{(.*?)\n\t\}", page_cs, _re.S)
    if not body or "planetCoverage =" not in body.group(1):
        out.append("Reset() no longer assigns planetCoverage, so a Reset postfix has nothing to override")
    arr = _re.search(r"PlanetCoverages = new float\[\d+\] \{([^}]*)\}", page_cs)
    vals = [float(x.strip().rstrip("f")) for x in arr.group(1).split(",")] if arr else []
    if coverage not in vals:
        out.append("coverage %s is not one of the page's legal PlanetCoverages %s" % (coverage, vals))
    if len(_re.findall(r"\bReset\(\);", page_cs)) < 2:
        out.append("Reset() has fewer than two callers (PreOpen and the Reset button): the postfix may not fire on every open")
    if "if (!initialized)" not in page_cs:
        out.append("PreOpen's once-only `initialized` guard is gone: the postfix would be re-applied on every open")
    if not _re.search(r"public int subdivisions = \d+;", layer_cs):
        out.append("PlanetLayerSettings.subdivisions is no longer a public int")
    if not _re.search(r"public PlanetLayerSettings settings;", def_cs):
        out.append("PlanetLayerSettingsDef.settings is no longer a public PlanetLayerSettings")
    if not _re.search(r"public static PlanetLayerSettingsDef Surface;", defof_cs):
        out.append("PlanetLayerSettingsDefOf.Surface is gone")
    return out


def mlp_findings(tile_cs, subdivisions):
    out = []
    if not _re.search(r"namespace WorldGenRules", tile_cs) or not _re.search(r"\bclass WorldGenRules\b", tile_cs):
        out.append("MLP no longer has class WorldGenRules in namespace WorldGenRules")
    if not _re.search(r"public static int subcount\s*=", tile_cs):
        out.append("MLP's subcount is no longer a public static int")
    m = _re.search(r"HorizontalSlider\(rect, subcount, ([0-9.]+)f, ([0-9.]+)f", tile_cs)
    if not m or not float(m.group(1)) <= subdivisions <= float(m.group(2)):
        out.append("subdivisions %d is outside MLP's slider range %s" % (subdivisions, m and (m.group(1), m.group(2))))
    if "Surface.settings.subdivisions = subcount" not in tile_cs:
        out.append("MLP no longer copies subcount into Surface.settings.subdivisions: priming its field is no longer needed or enough")
    return out


@suite.chain("signatures_static")
def signatures_static(t):
    """Offline: every engine/MLP name the Reset postfix relies on still exists with the shape it assumes. UNMEASURED when the
    decompiled reference tree or My Little Planet's source is not reachable from this machine."""
    with t.component("reset_postfix_targets_exist_in_engine_and_mlp", beyond_toggle=True):
        mlp = mlp_source_dir()
        eng = _os.path.join(DECOMPILED, "RimWorld")
        if mlp is None or not _os.path.isfile(_os.path.join(eng, "Page_CreateWorldParams.cs")):
            t.upstream_failed = True
            t.upstream_reason = "UNMEASURED: decompiled engine tree (%s) or My Little Planet source not reachable" % DECOMPILED
            return
        cs = _rd(_HERE, "Source", "PlanetPresetPrime.cs")
        mod = mod_findings(cs)
        page = _rd(eng, "Page_CreateWorldParams.cs")
        if len(page) < 2000 or len(cs) < 2000:
            raise ExpectationFailed("blind read: engine page %d chars, mod %d chars" % (len(page), len(cs)))
        eng_f = engine_findings(page, _rd(eng, "PlanetLayerSettings.cs"), _rd(eng, "PlanetLayerSettingsDef.cs"),
                                _rd(eng, "PlanetLayerSettingsDefOf.cs"), 1.0, 7)
        mlp_f = mlp_findings(_rd(mlp, "MyLittlePlanet", "TileSize.cs"), 7)
        bad = mod + eng_f + mlp_f
        if bad:
            raise ExpectationFailed("; ".join(bad[:5]))



@suite.chain("boot_prime_values_logged")
def boot_prime_values_logged(t):
    """The only thing this suite can prove (see module docstring for why
    the mod's actual priming mechanism has no live hook here): the static
    constructor's boot line reports coverage=1, subdivisions=7, and --
    since `oblitus.mylittleplanet` is in the minimal list -- MLP type
    'found', not 'ABSENT'."""
    t.clear_area(size=8)   # no map state involved; keeps the runner's
                            # evidence/screenshot machinery uniform

    with t.component("boot_line_reports_primed_values", beyond_toggle=True):
        t.expect_log_contains(BOOT_LOG_TAG, field=None, value=None)
        r = t.bridge_call("jawa/drain_log", limit=200, contains=BOOT_LOG_TAG)
        msgs = [m.get("text", "") for m in ((r or {}).get("messages") or [])]
        joined = "\n".join(msgs)
        if t._guard():
            if "will prime coverage 1, subdivisions 7." not in joined:
                raise ExpectationFailed(
                    "no '%s will prime coverage 1, subdivisions 7.' line "
                    "found -- either the static ctor never ran, or the "
                    "primed constants changed. Recent matching lines: %r"
                    % (BOOT_LOG_TAG, msgs))
            if "MLP type found." not in joined:
                raise ExpectationFailed(
                    "boot line did not report 'MLP type found.' -- "
                    "oblitus.mylittleplanet is in the minimal list "
                    "(infrastructure/state/modlists/ModsConfig.MINIMAL.xml) "
                    "so WorldGenRules.WorldGenRules should have resolved. "
                    "Recent matching lines: %r" % msgs)
        t.screenshot()
