"""validation.py -- modcheck suite for RimMandrake Planet Preset Prime
(mandrake.rm.planetpresetprime).

Dev-ergonomics-only mod, not player-facing (own About.xml's own words).
One file, `PlanetPresetPrime.cs`, read whole before writing this: a static
constructor that logs a boot line and patches Harmony into the executing
assembly, plus one `[HarmonyPatch(typeof(Page_CreateWorldParams), "Reset")]`
postfix that primes `planetCoverage=1.0f` (reflectively, the field is
private) and, if My Little Planet's `WorldGenRules.WorldGenRules.subcount`
type/field resolve, primes that too (also reflective, MLP is a private
type), then sets `PlanetLayerSettingsDefOf.Surface.settings.subdivisions=7`
unconditionally. No XML defs, no `ModSettings` class anywhere in the mod
(the two constants `Coverage`/`Subdivisions` are compile-time `const
float`/`const int`, nothing a player or a settings window could ever
touch) -- `suite.toggles = []`, every component `beyond_toggle=True`.

`oblitus.mylittleplanet` IS in the minimal list (grepped directly:
`infrastructure/state/modlists/ModsConfig.MINIMAL.xml` carries it), unlike
the third-party donors MandrakePatches/MenuShell needed and did not have --
so the walk doc's own `list: minimal+mylittleplanet` requirement is
already satisfied by a plain `modcheck run PlanetPresetPrime`, and MLP
SHOULD resolve as "found" in the boot line's own report.

A REAL, WHOLE-MECHANISM FLOOR GAP -- not found by guessing, found by
searching the actual tool surface before writing a component that assumes
one exists: this mod's ENTIRE point is a Harmony postfix on
`Page_CreateWorldParams.Reset()`, the world-creation PAGE's own reset
method. `Transient/bench_tools_dump.json` has exactly three tools whose
name contains "world" and "info"/"stats" (`jawa/world_info_get`,
`jawa/world_info_set`, `jawa/world_stats`) -- NONE of them opens, drives,
or in any way triggers `Page_CreateWorldParams`, and no debug-action route
to it was found either (the walk doc's own step 2 flags this exact
uncertainty and asks whoever runs it to "confirm the correct trigger"
first). Worse: a `modcheck` `Session` connects to an ALREADY-`Playing`
quicktest map (`rimdrive.Session`'s own boot sequence, per every other
suite in this backfill wave) -- by the time any chain function here could
call a bridge tool, a world already exists, generated by whatever path the
quicktest bootstrap actually used, which is NOT traceable from this mod's
own source to be the `Page_CreateWorldParams` UI flow at all (out of this
mod's own scope to answer; a JawaBench/quicktest-bootstrap question, not a
PlanetPresetPrime one). So the walk doc's steps 2-5 -- opening the page,
reading back the primed `planetCoverage`/`subdivisions` fields, generating
a world from the primed page and checking its tile count is 21872 -- have
NO LIVE HOOK in this suite's environment at all. This is the mod's entire
mechanism, left genuinely uncovered rather than faked with a component
that assumes a trigger this suite could not find.

WHAT IS LEFT, AND IS REAL: the static constructor's own boot line (walk
doc step 1) runs at `LoadedModManager.LoadAllActiveMods` time, unconditional
on the page ever opening -- the mod's OWN comment says exactly why this
line exists ("A mod that writes nothing at load is indistinguishable from a
mod that failed to load at all... So say so at STARTUP, not only when the
page opens"). This is the one thing this suite can actually prove: the
assembly loaded, Harmony patched clean, and (since MLP is in the minimal
list) the MLP type-probe found `WorldGenRules.WorldGenRules`.

Still not proven / likely first-live-run corrections:
  1. Whether `jawa/drain_log` still holds this boot-time line by the time a
     quicktest chain gets to read it -- same timing concern RustChrome's
     own docstring flags for its own static-ctor line, and PlanetPresetPrime's
     runs even earlier in the boot sequence (before any Harmony patch on
     `Page_CreateWorldParams` could possibly have fired, since that patch
     is applied by the SAME static constructor this line is inside of).
     Untested live.
  2. If a future bridge tool DOES open `Page_CreateWorldParams` or drive a
     world-creation flow, this suite should grow the `ready` line, the
     `planetCoverage`/`subdivisions` read-back, and the `jawa/world_stats`
     21872-tile end-to-end proof the walk doc's own step 4 calls "the
     actual end-to-end proof the priming worked" -- filed as the gap this
     validator leaves, not silently dropped.
"""
from modcheck import Suite, ExpectationFailed

suite = Suite("PlanetPresetPrime")
suite.toggles = []   # no Source/ ModSettings class, no XML defs -- every
                      # component beyond_toggle

BOOT_LOG_TAG = "[RimMandrake.PlanetPresetPrime] loaded:"


@suite.chain("boot_prime_values_logged")
def boot_prime_values_logged(t):
    """The only thing this suite can prove (see module docstring for why
    the mod's actual priming mechanism has no live hook here): the static
    constructor's boot line reports coverage=1, subdivisions=7, and --
    since `oblitus.mylittleplanet` is in the minimal list -- MLP type
    'found', not 'ABSENT'."""
    t.clear_area(size=8)   # no map state involved; keeps the runner's
                            # evidence/screenshot machinery uniform

    with t.component("boot_line_reports_primed_values", beyond_toggle=True):
        t.expect_log_contains(BOOT_LOG_TAG, field=None, value=None)
        r = t.bridge_call("jawa/drain_log", limit=200, contains=BOOT_LOG_TAG)
        msgs = [m.get("text", "") for m in ((r or {}).get("messages") or [])]
        joined = "\n".join(msgs)
        if t._guard():
            if "will prime coverage 1, subdivisions 7." not in joined:
                raise ExpectationFailed(
                    "no '%s will prime coverage 1, subdivisions 7.' line "
                    "found -- either the static ctor never ran, or the "
                    "primed constants changed. Recent matching lines: %r"
                    % (BOOT_LOG_TAG, msgs))
            if "MLP type found." not in joined:
                raise ExpectationFailed(
                    "boot line did not report 'MLP type found.' -- "
                    "oblitus.mylittleplanet is in the minimal list "
                    "(infrastructure/state/modlists/ModsConfig.MINIMAL.xml) "
                    "so WorldGenRules.WorldGenRules should have resolved. "
                    "Recent matching lines: %r" % msgs)
        t.screenshot()
