// GENERATED by src/RimMandrake/Utils/mockups/messy_conduit/wire_bracket_art.py -- do not edit by hand.
// Wall bracket insulator offset from the graphic centre (cells; x east, z north) per Look/rotation, measured from each
// look's own per-facing art. Absent = the look has no art of its own yet (tinted stand-in, def attachZ).
using System.Collections.Generic;
using UnityEngine;

namespace RimMandrake.MessyConduit.Aerial
{
    public static class BracketGeometryTable
    {
        public static Dictionary<string, Vector2> Build()
        {
            var d = new Dictionary<string, Vector2>();
            d["Scrapper/East"] = new Vector2(-0.356f, 0.154f);
            d["Scrapper/West"] = new Vector2(0.356f, 0.154f);
            d["Scrapper/North"] = new Vector2(0.005f, -0.132f);
            d["Scrapper/South"] = new Vector2(0.004f, -0.229f);
            d["Industrial/East"] = new Vector2(-0.335f, 0.092f);
            d["Industrial/West"] = new Vector2(0.335f, 0.092f);
            d["Industrial/North"] = new Vector2(0.000f, -0.237f);
            d["Industrial/South"] = new Vector2(0.007f, 0.222f);
            d["Modern/East"] = new Vector2(-0.309f, 0.098f);
            d["Modern/West"] = new Vector2(0.309f, 0.098f);
            d["Modern/North"] = new Vector2(-0.000f, -0.218f);
            d["Modern/South"] = new Vector2(0.000f, 0.175f);
            d["Futuristic/East"] = new Vector2(-0.234f, 0.049f);
            d["Futuristic/West"] = new Vector2(0.234f, 0.049f);
            d["Futuristic/North"] = new Vector2(0.000f, -0.128f);
            d["Futuristic/South"] = new Vector2(0.000f, -0.081f);
            return d;
        }
    }
}
