// GENERATED by src/RimMandrake/Utils/mockups/messy_conduit/wire_bracket_art.py -- do not edit by hand.
// Wall bracket geometry per Look/rotation, measured from each look's own per-facing art (cells; x east, z north). Absent =
// the look has no art of its own yet (tinted stand-in, def attachZ). Verse-free: the SelfTest compiles this file.
using System.Collections.Generic;

namespace RimMandrake.MessyConduit.Aerial
{
    public static class BracketGeometryTable
    {
        /// <summary>The insulator's offset from the graphic centre.</summary>
        public static Dictionary<string, P2> Build()
        {
            var d = new Dictionary<string, P2>();
            d["Scrapper/East"] = new P2(-0.356, 0.154);
            d["Scrapper/West"] = new P2(0.356, 0.154);
            d["Scrapper/North"] = new P2(0.005, -0.132);
            d["Scrapper/South"] = new P2(0.004, 0.229);
            d["Industrial/East"] = new P2(-0.335, 0.092);
            d["Industrial/West"] = new P2(0.335, 0.092);
            d["Industrial/North"] = new P2(0.000, -0.237);
            d["Industrial/South"] = new P2(0.007, 0.222);
            d["Modern/East"] = new P2(-0.309, 0.098);
            d["Modern/West"] = new P2(0.309, 0.098);
            d["Modern/North"] = new P2(-0.000, -0.218);
            d["Modern/South"] = new P2(0.000, 0.175);
            d["Futuristic/East"] = new P2(-0.234, 0.049);
            d["Futuristic/West"] = new P2(0.234, 0.049);
            d["Futuristic/North"] = new P2(0.000, -0.128);
            d["Futuristic/South"] = new P2(0.000, 0.081);
            return d;
        }

        /// <summary>The plate's extreme toward the wall: cells from the graphic centre along the wall normal (+ = toward it).</summary>
        public static Dictionary<string, double> PlateEdge()
        {
            var d = new Dictionary<string, double>();
            d["Scrapper/East"] = 0.453;
            d["Scrapper/West"] = 0.453;
            d["Scrapper/North"] = 0.344;
            d["Scrapper/South"] = 0.375;
            d["Industrial/East"] = 0.453;
            d["Industrial/West"] = 0.453;
            d["Industrial/North"] = 0.359;
            d["Industrial/South"] = 0.320;
            d["Modern/East"] = 0.492;
            d["Modern/West"] = 0.492;
            d["Modern/North"] = 0.391;
            d["Modern/South"] = 0.359;
            d["Futuristic/East"] = 0.336;
            d["Futuristic/West"] = 0.336;
            d["Futuristic/North"] = 0.258;
            d["Futuristic/South"] = 0.227;
            return d;
        }
    }
}
