// GENERATED by src/RimMandrake/Utils/mockups/messy_conduit/wire_pole_art.py -- do not edit by hand.
// Per-look pole geometry measured from each look's own 128x512 render (attachZ, topOffsetZ; cells above the cell centre).
using System.Collections.Generic;
using UnityEngine;

namespace RimMandrake.MessyConduit.Aerial
{
    public static class PoleGeometryTable
    {
        public static Dictionary<string, Vector2> Build()
        {
            var d = new Dictionary<string, Vector2>();

            return d;
        }
    }
}
