#!/usr/bin/env python3
"""Emit the FlowWorks north-star run-sheet: per chain and component, the bars it decides, its toggle,
and the Player.log strings / state reads that decide each (item FLOWWORKS_NORTHSTAR_BASELINE_RUN_1).

    python3 src/RimMandrake/FlowWorks/northstar/runsheet.py > <out.md>

Parsed from validation.py text (no game, no modcheck import). Log strings are the ones FlowWorks
Source actually emits; a bar with no log string is decided by judge + state predicate only.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VAL = os.path.join(HERE, "..", "validation.py")

LOG_STRINGS = [
    ("[RimMandrake.FlowWorks] classified liquid body #", "a body was classified ONCE (limited/limitless); one line per body. Missing = body never touched; two lines for one id = re-argued (defect)."),
    ("[RimMandrake.FlowWorks] subsurface survey: this map yields", "map-gen survey ran (aquifer/limitless decisions); absent on a map built before the mod."),
    ("[RimMandrake.FlowWorks] rehydrated ", "a LOAD recovered bodies from the save: expected on golden-save loads, never on a fresh quicktest."),
    ("[RimMandrake.FlowWorks] conservation ledger does not balance", "FAIL (any occurrence): fluid created/destroyed outside the ledger."),
    ("[RimMandrake.FlowWorks] conservation exception", "FAIL: exception in the conservation pass."),
    ("[RimMandrake.FlowWorks] fluid(s) recorded in this save no longer exist", "WARN: save references a deleted FluidDef (stale golden)."),
    ("[RimMandrake.FlowWorks] <fluid> release cooled", "tar/lava release cooled (heat bars)."),
    ("[FlowWorks] Typed liquid shores: repainted", "typedLiquidShoresEnabled quicktests: N tiles repainted > 0 when ON, line absent when OFF."),
    ("[RMFlowWorksDebug] FILL_FLUID ", "debug fill result: 'ok' or 'REFUSED' (fluid-switch refusal bar)."),
    ("Config error", "FAIL if it names mandrake.rm.flowworks (preflight P-L2)."),
    ("Could not resolve cross-reference", "FAIL if it names an RM_ FlowWorks def (P-L2)."),
    ("Exception", "FAIL if the stack names RimMandrake.FlowWorks (P-L2)."),
]


def main():
    txt = open(VAL, encoding="utf-8").read()
    out = ["# FlowWorks north-star run-sheet (generated by runsheet.py)", "",
           "## Player.log strings that decide things", "", "| string | meaning |", "|---|---|"]
    for s, m in LOG_STRINGS:
        out.append("| `%s` | %s |" % (s, m))
    out += ["", "## Chains and components", ""]
    chain = None
    comp_re = re.compile(r't\.component\(\s*"([^"]+)"(.*?)\):\s*$', re.S)
    # walk lines; accumulate multi-line component headers
    lines = txt.splitlines()
    i = 0
    n_comp = n_bars = 0
    bars_seen = set()
    while i < len(lines):
        ln = lines[i]
        m = re.match(r'@suite\.chain\("([^"]+)"', ln)
        if m:
            chain = m.group(1)
            out += ["", "### chain `%s`" % chain, "", "| component | toggle | bars decided (judge YES for must-show, NO for never_*) |", "|---|---|---|"]
        if "t.component(" in ln:
            hdr = ln
            while not hdr.rstrip().endswith(":") and i + 1 < len(lines):
                i += 1
                hdr += " " + lines[i].strip()
            name = re.search(r't\.component\(\s*"([^"]+)"', hdr).group(1)
            tg = re.search(r'toggle="([^"]+)"', hdr)
            sh = re.search(r'shows=\[(.*?)\]', hdr, re.S)
            bars = re.findall(r'"([^"]+)"', sh.group(1)) if sh else []
            n_comp += 1
            bars_seen.update(bars)
            out.append("| `%s` | %s | %s |" % (name, ("`%s`" % tg.group(1)) if tg else "-", ", ".join("`%s`" % b for b in bars) or "state only"))
        i += 1
    if not n_comp or not bars_seen:     # a parse that matched nothing must not emit an empty-looking run sheet
        sys.stderr.write("runsheet: parsed %d components / %d bars from %s -- validation.py layout changed?\n"
                         % (n_comp, len(bars_seen), VAL))
        return 1
    out += ["", "Totals: %d components, %d distinct bars claimed." % (n_comp, len(bars_seen))]
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
