#!/usr/bin/env python3
"""Emit the FlowWorks north-star run-sheet: per chain and component, the bars it decides, its toggle,
and the Player.log strings / state reads that decide each (item FLOWWORKS_NORTHSTAR_BASELINE_RUN_1).

    python3 src/RimMandrake/FlowWorks/northstar/runsheet.py > <out.md>

Read from validation.py with modcheck's declaration probe (no game). Log strings are the ones FlowWorks
Source actually emits; a bar with no log string is decided by judge + state predicate only.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VAL = os.path.join(HERE, "..", "validation.py")

LOG_STRINGS = [
    ("[RimMandrake.FlowWorks] classified liquid body #", "a body was classified ONCE (limited/limitless); one line per body. Missing = body never touched; two lines for one id = re-argued (defect)."),
    ("[RimMandrake.FlowWorks] subsurface survey: this map yields", "map-gen survey ran (aquifer/limitless decisions); absent on a map built before the mod."),
    ("[RimMandrake.FlowWorks] rehydrated ", "a LOAD recovered bodies from the save: expected on golden-save loads, never on a fresh quicktest."),
    ("[RimMandrake.FlowWorks] conservation ledger does not balance", "FAIL (any occurrence): fluid created/destroyed outside the ledger."),
    ("[RimMandrake.FlowWorks] conservation exception", "FAIL: exception in the conservation pass."),
    ("[RimMandrake.FlowWorks] fluid(s) recorded in this save no longer exist", "WARN: save references a deleted FluidDef (stale golden)."),
    ("[RimMandrake.FlowWorks] <fluid> release cooled", "tar/lava release cooled (heat bars)."),
    ("[FlowWorks] Typed liquid shores: repainted", "typedLiquidShoresEnabled quicktests: N tiles repainted > 0 when ON, line absent when OFF."),
    ("[RMFlowWorksDebug] FILL_FLUID ", "debug fill result: 'ok' or 'REFUSED' (fluid-switch refusal bar)."),
    ("Config error", "FAIL if it names mandrake.rm.flowworks (preflight P-L2)."),
    ("Could not resolve cross-reference", "FAIL if it names an RM_ FlowWorks def (P-L2)."),
    ("Exception", "FAIL if the stack names RimMandrake.FlowWorks (P-L2)."),
]


def main():
    """Per chain (core rows + extension chains, in suite order) and component: toggle and bars, read with
    modcheck's own declaration probe from validation.py (no game). Refuses to print an empty sheet."""
    import importlib.util
    for p in (os.path.join(HERE, "..", "..", "Utils"), os.path.join(HERE, "..", "..", "Utils", "modcheck")):
        if p not in sys.path:
            sys.path.insert(0, p)
    from modcheck.suite import _DeclarationProbe
    spec = importlib.util.spec_from_file_location("fw_validation_runsheet", VAL)
    vm = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(vm)
    out = ["# FlowWorks north-star run-sheet (generated by runsheet.py)", "",
           "Core proof: `python.exe src/RimMandrake/FlowWorks/northstar/validation_v2.py --live --fresh-map` (rows "
           "below under `core_offline` / `core_live_rows`). Extension chains run only on request: "
           "`python.exe src/RimMandrake/FlowWorks/northstar/extension_proof.py --live [--chains ...]`.", "",
           "## Player.log strings that decide things", "", "| string | meaning |", "|---|---|"]
    for s_, m in LOG_STRINGS:
        out.append("| `%s` | %s |" % (s_, m))
    out += ["", "## Chains and components", ""]
    n_comp, bars_seen = 0, set()
    for chain, fn in vm.suite.chains:
        probe = _DeclarationProbe()
        fn(probe)
        tag = "core" if chain.startswith("core_") else "extension"
        out += ["", "### chain `%s` (%s)" % (chain, tag), "",
                "| component | toggle | bars decided (judge YES for must-show, NO for never_*) |", "|---|---|---|"]
        for c in probe.components:
            n_comp += 1
            bars_seen.update(c.shows)
            out.append("| `%s` | %s | %s |" % (c.name, ("`%s`" % c.toggle) if c.toggle else "-",
                                               ", ".join("`%s`" % b for b in c.shows) or "state only"))
    if not n_comp or not bars_seen:     # a parse that matched nothing must not emit an empty-looking run sheet
        sys.stderr.write("runsheet: declared %d components / %d bars from %s\n" % (n_comp, len(bars_seen), VAL))
        return 1
    out += ["", "Totals: %d components, %d distinct bars claimed; extension-only bars (no core row): %s." % (
        n_comp, len(bars_seen), ", ".join("`%s`" % b for b in vm.EXTENSION_ONLY_BARS))]
    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
