"""validation.py -- modcheck suite for RimMandrake: Gravship Landing Reveal (mandrake.rm.gravshiplanding).

First north-star script (GRAVSHIP_LANDING_FIRST_SCRIPT_1). Walk: design/validation_walks/RimMandrake/GravshipLanding.md.
One Harmony postfix (Patch_GenStep_GravshipMarker_Generate.Postfix on GenStep_GravshipMarker.Generate) that unfogs every
unroofed fogged cell of a gravship-ARRIVAL map before the landing picker shows, behind one Mod Setting
(GravshipLandingSettings.revealOutdoorsBeforeLanding). The mod ships NO defs.

CHAINS
  defs_resolve          the mod ships no defs (static) and the probe can say absent on a control name.
  settings_roundtrip    every `public static` field of GravshipLandingSettings (parsed from the C#): get, set, read back, restore.
  reveal_gate_armed     the postfix is attached to GenStep_GravshipMarker.Generate by this mod's Harmony id (a failed patch would
                        leave the mod loaded and doing nothing); a nonexistent method reads no owner.
  arrival_map_reveal    outdoor cells unfogged on an arrival map, roofed interiors still fogged, toggle off = vanilla fog:
                        UNMEASURED (needs a map generated BY a gravship arrival; the bridge cannot arrive a gravship).

STATIC: `python3 validation.py` -> `STATIC: PASS (0 findings)`; needs no game.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SETTINGS = "RimMandrake.GravshipLanding.GravshipLandingSettings"
HARMONY_ID = "mandrake.rm.gravshiplanding"
CONTROL_ABSENT = "ThingDef/RM_GravshipLandingNoSuchDef_ZZ"
_FIELD = re.compile(r"public\s+static\s+(bool|int|float)\s+(\w+)\s*=\s*([^;]+);")
PATCH_TYPE, PATCH_METHOD, PATCH_NAME = "GenStep_GravshipMarker", "Generate", "Postfix"


def _read(name):
    return open(os.path.join(HERE, "Source", name), encoding="utf-8").read()


def settings_fields():
    """{name: type} for every scalar `public static` field of GravshipLandingSettings, read from the C#."""
    body = _read("GravshipLandingMod.cs").split("class GravshipLandingSettings", 1)[1].split("ExposeData", 1)[0]
    return dict((m.group(2), m.group(1)) for m in _FIELD.finditer(re.sub(r"//[^\n]*", "", body)))


def static_checks():
    bad = []
    fields = settings_fields()
    if "revealOutdoorsBeforeLanding" not in fields:
        return ["settings probe did not find revealOutdoorsBeforeLanding (sanity probe failed)"]
    mod = _read("GravshipLandingMod.cs")
    scribed = mod.split("ExposeData", 1)[1]
    ui = scribed.split("DoWindowContents", 1)[1]
    for n in fields:
        if '"%s"' % n not in scribed:
            bad.append("settings field %s is not Scribed" % n)
        if not re.search(r"\b%s\b" % n, ui):
            bad.append("settings field %s has no control in DoWindowContents" % n)
    if 'HarmonyId = "%s"' % HARMONY_ID not in mod:
        bad.append("HarmonyId constant is not %s" % HARMONY_ID)
    if "PatchAll" not in mod:
        bad.append("the mod no longer calls PatchAll (the postfix would never attach)")
    patch = _read("Patch_GenStep_GravshipMarker.cs")
    if "typeof(%s), nameof(%s.%s)" % (PATCH_TYPE, PATCH_TYPE, PATCH_METHOD) not in patch:
        bad.append("postfix no longer targets %s.%s" % (PATCH_TYPE, PATCH_METHOD))
    if not re.search(r"static void %s\(" % PATCH_NAME, patch):
        bad.append("postfix method %s not found" % PATCH_NAME)
    if "revealOutdoorsBeforeLanding" not in patch:
        bad.append("the postfix no longer reads the toggle")
    if os.path.isdir(os.path.join(HERE, "Defs")):
        bad.append("a Defs/ folder appeared: add a defs_resolve component that reads it")
    proj = _read("RM_GravshipLanding.csproj")
    for fn in sorted(os.listdir(os.path.join(HERE, "Source"))):
        if fn.endswith(".cs") and 'Compile Include="%s"' % fn not in proj:
            bad.append("%s is not in the csproj (compiles into nothing)" % fn)
    if not os.path.isfile(os.path.join(HERE, "..", "..", "..", "design", "validation_walks", "RimMandrake", "GravshipLanding.md")):
        bad.append("walk missing")
    return bad


try:
    _UTILS = os.path.join(HERE, "..", "Utils")
    if os.path.isdir(_UTILS) and _UTILS not in sys.path:
        sys.path.insert(0, _UTILS)
    from modcheck import Suite, ExpectationFailed
except ImportError:
    Suite = None


def _build_suite():
    suite = Suite("GravshipLanding")
    suite.toggles = sorted(settings_fields())

    def _live(t):
        return t.session is not None and not t.upstream_failed

    def _unmeasured(t, why):
        t.upstream_reason = "UNMEASURED: " + why
        t.upstream_failed = True

    def _raw(t, action, field, value=None):
        if value is not None:
            r = t.session.call("jawa/mod_settings_field", typeName=SETTINGS, action=action, field=field, value=str(value))
        else:
            r = t.session.call("jawa/mod_settings_field", typeName=SETTINGS, action=action, field=field)
        return r if isinstance(r, dict) else {}

    def _same(ty, a, b):
        if ty == "bool":
            return str(a).lower() == str(b).lower()
        return a is not None and b is not None and abs(float(a) - float(b)) <= 1e-4 * max(1.0, abs(float(b)))

    @suite.chain("defs_resolve")
    def defs_resolve(t):
        with t.component("mod_ships_no_defs", beyond_toggle=True):
            if os.path.isdir(os.path.join(HERE, "Defs")):
                raise ExpectationFailed("a Defs/ folder exists but this script reads none of it")
        with t.component("control_probe_can_say_absent", beyond_toggle=True):
            r = t.bridge_call("jawa/get_defs", defs=CONTROL_ABSENT, fields="defName", limit=2)
            if _live(t):
                if not isinstance(r, dict) or r.get("success") is False:
                    raise ExpectationFailed("get_defs failed outright on the control: %r" % r)
                if int(r.get("foundCount", 0)) != 0 or not r.get("notFound"):
                    raise ExpectationFailed("control def reads as present: %r" % r)

    @suite.chain("settings_roundtrip")
    def settings_roundtrip(t):
        with t.component("settings_probe_finds_fields", beyond_toggle=True):
            if "revealOutdoorsBeforeLanding" not in settings_fields():
                raise ExpectationFailed("settings probe found no revealOutdoorsBeforeLanding (blind regex)")
        for field, ty in sorted(settings_fields().items()):
            with t.component("%s_round_trips" % field, toggle=field):
                if not _live(t):
                    continue
                old = _raw(t, "get", field).get("value")
                if old is None:
                    raise ExpectationFailed("%s: get returned no value" % field)
                if ty == "bool":
                    new = "False" if str(old).lower() == "true" else "True"
                else:
                    new = str(float(old) + 1.0)
                try:
                    if not _raw(t, "set", field, new).get("success"):
                        raise ExpectationFailed("%s: set failed" % field)
                    back = _raw(t, "get", field).get("value")
                    if not _same(ty, back, new):
                        raise ExpectationFailed("%s: wrote %s, read %r" % (field, new, back))
                finally:
                    _raw(t, "set", field, old)
                back = _raw(t, "get", field).get("value")
                if not _same(ty, back, old):
                    raise ExpectationFailed("%s did not restore to %r (read %r)" % (field, old, back))

    @suite.chain("reveal_gate_armed")
    def reveal_gate_armed(t):
        with t.component("control_nonexistent_method_has_no_owner", beyond_toggle=True):
            r = t.bridge_call("jawa/harmony_patches", typeName=PATCH_TYPE, methodName="NoSuchMethodZZ")
            if _live(t) and isinstance(r, dict) and r.get("success") is True and not r.get("harmonyError"):
                for m in (r.get("methods") or []):
                    if any(p.get("owner") == HARMONY_ID for p in (m.get("postfixes") or [])):
                        raise ExpectationFailed("a nonexistent method reads as patched by %s" % HARMONY_ID)
        with t.component("postfix_attached_to_gravship_marker_generate", toggle="revealOutdoorsBeforeLanding"):
            r = t.bridge_call("jawa/harmony_patches", typeName=PATCH_TYPE, methodName=PATCH_METHOD)
            if _live(t):
                if not isinstance(r, dict) or r.get("success") is not True or r.get("harmonyError"):
                    _unmeasured(t, "harmony_patches could not be asked: %s" % str(r)[:160])
                    return
                mine = [p for m in (r.get("methods") or []) for p in (m.get("postfixes") or [])
                        if (p.get("patchMethod") or "").endswith(PATCH_NAME) and p.get("owner") == HARMONY_ID]
                if not mine:
                    owners = sorted(set(p.get("owner") for m in (r.get("methods") or [])
                                        for p in (m.get("postfixes") or []) if p.get("owner")))
                    raise ExpectationFailed("%s.%s carries no postfix %s from %s (owners: %s)"
                                            % (PATCH_TYPE, PATCH_METHOD, PATCH_NAME, HARMONY_ID, owners[:8]))

    @suite.chain("arrival_map_reveal")
    def arrival_map_reveal(t):
        for name, why in (
            ("outdoor_cells_unfogged_on_arrival_map",
             "needs a map GENERATED by a gravship arrival (parms.gravship set) with a walled complex at the reserved spot; the "
             "bridge cannot arrive a gravship, so the fogged-cell count before/after cannot be read"),
            ("roofed_interiors_stay_fogged",
             "same arrival map: a sealed or mountain-roofed cell must still read fogged after the reveal"),
            ("toggle_off_leaves_vanilla_fog",
             "same arrival map generated with revealOutdoorsBeforeLanding off: only the flood-fill from the landing spot is unfogged"),
        ):
            with t.component(name, toggle="revealOutdoorsBeforeLanding"):
                if _live(t):
                    _unmeasured(t, why)

    return suite


suite = _build_suite() if Suite is not None else None

if __name__ == "__main__":
    problems = static_checks()
    print("STATIC: %s" % ("PASS (0 findings)" if not problems else "FAIL"))
    for p in problems:
        print("  - " + p)
    sys.exit(1 if problems else 0)
