using RimWorld;
using UnityEngine;
using Verse;

namespace RimMandrake.Utinni.LanternDeeps
{
	// CAVERNS_PARITY_BUILD_1 — our own crystal scatter, replacing the borrowed
	// BiomesCaverns.GenSteps.GenStep_ScatterCrystals that BMT_CrystalsGenerator
	// named (caverns_replacement_scoping.md §2, "crystal formations" row).
	//
	// Same Scatterer pattern the mod's other four GenSteps already use: a thin
	// GenStep_ScatterGroup subclass, discovered by RimWorld's own GenStepDef the
	// moment the XML names it in `genStep Class`. No Harmony, no registration.
	//
	// 🔑 Why a subclass at all, rather than plain GenStep_ScatterGroup like
	// RUT_LanternDeepKyberScatter? Two reasons, both of which the donor's class
	// also had:
	//
	//   1. The density must answer to Mod Settings. MOD_OPTIONS_RETROFIT_1 and
	//      the standing rule require a per-feature toggle plus a tuning number
	//      where the number IS the experience — and for a Lantern Deep, how much
	//      lanternstone is in it is exactly that. Vanilla GenStep_ScatterGroup
	//      reads countPer10kCellsRange straight off the def with no hook.
	//   2. A belt-and-braces map gate. This GenStepDef is only ever listed by
	//      RUT_LanternDeepGenerator, so list membership already confines it — but
	//      a GenStepDef is global and any other mod's generator could list it.
	//      Checking the biome keeps lanternstone out of surface maps even then.
	//
	// ⚠️ countPer10kCellsRange lives on GenStep_Scatterer (our grandparent) and is
	// a public field, so scaling it here is a plain field write before the base
	// call. It is NOT reset afterwards on purpose: GenStepDefs are singletons and
	// a map generation is a single pass, but a second Deep generated in the same
	// session must not compound the multiplier, so the ORIGINAL def-loaded range
	// is captured once on first use and every later pass scales from that.
	public class GenStep_ScatterLanternstone : GenStep_ScatterGroup
	{
		// The pocket-map biome this step belongs to. A Deep generated by
		// RUT_LanternDeepGenerator always carries it.
		private const string DeepBiomeDefName = "RUT_LanternDeeps";

		private bool baseRangeCaptured;
		private FloatRange baseCountPer10kCells;

		public override int SeedPart => 1237834911;

		public override void Generate(Map map, GenStepParams parms)
		{
			if (!baseRangeCaptured)
			{
				baseCountPer10kCells = countPer10kCellsRange;
				baseRangeCaptured = true;
			}

			if (!LanternDeepsSettings.lanternstoneFormationsEnabled)
			{
				return;
			}
			if (map.Biome == null || map.Biome.defName != DeepBiomeDefName)
			{
				return;
			}

			float mult = Mathf.Max(0f, LanternDeepsSettings.lanternstoneDensityMultiplier);
			countPer10kCellsRange = new FloatRange(
				baseCountPer10kCells.min * mult,
				baseCountPer10kCells.max * mult);

			base.Generate(map, parms);

			// Leave the def's own numbers as we found them for anything that
			// reads them later (the mod-settings screen shows the multiplier,
			// not the scaled value).
			countPer10kCellsRange = baseCountPer10kCells;
		}
	}
}
