#!/usr/bin/env python3
"""gen_flora_assignment_sheet.py — the owner's flora sheet, rebuilt to his 2026-09-09 rulings.

The flora gets the FULL fauna treatment (his explicit choice): only the plants
going IN each biome (no purge rows), true relative scale inside each group with
the SAME colonist figure as the fauna sheet (panels regenerated by
regen_flora_scale_panels.py), size bins as design intent, art verdicts
keep/improve/redo, plain-language cards, and the 118-row NEW-ART/DEF ledger —
those verdicts create the art queue.

Shares its helpers and chrome blocks with gen_fauna_assignment_sheet.py.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import gen_fauna_assignment_sheet as F  # noqa: E402  (shared helpers + chrome)

ROSTERS = HERE.parent / "biomes" / "rosters"
PLANT_REGISTER = HERE / "plant_register_rows.json"
PANELS = HERE / "flora_scale_panels.json"
PLANT_ART_DECISIONS = HERE / "plant_register.decisions.json"
SHEET = HERE / "flora_assignment_register.html"
DECISIONS = HERE / "flora_assignment_register.decisions.json"

NATIVE_DIR = F.NATIVE_DIR
CARD_GROUP = "Questions for you — the calls I could not settle"
LEDGER_PLANTS = ("New things to create — plants "
                 "(In = commission it · Out = drop it for good · Decide later = park it)")
LEDGER_OTHER = ("New things to create — creatures & mechanisms "
                "(In = commission it · Out = drop it for good · Decide later = park it)")

ART_MAP = {"keep": "keep", "regen": "redo", "rescale": "keep"}

CARDS = [
    {
        "id": "q:the_forge:earth-plant-names",
        "label": "The Forge — do 'fireweed' and 'fire lavender' survive the name purge?",
        "q": "You purged every plant nameable as an Earth species — but the "
             "Forge's own frozen sheet names 'fireweed' as its signature, and "
             "fireweed and lavender are real Earth plant names.",
        "trade": "Keeping the names honours the frozen sheet and they do sound "
                 "right for the place; purging them is consistent with the "
                 "planet-wide rule but costs the Forge its named signature until "
                 "a new name is coined.",
        "rec": "Keep the plants, rename them — the purge is about recognisable "
               "Earth species, and a coined name keeps both rules. In = keep and "
               "rename · Out = purge them too · note a better name if you have one.",
        "prefill": "in",
    },
]


def mature_cells(row: dict):
    dx, vmax = row.get("drawSizeX"), row.get("visualSizeMax")
    if dx is None or vmax is None:
        return None
    return float(dx) * float(vmax)


def plant_shape(row: dict) -> str:
    if row.get("isTree"):
        return "a tree"
    size = row.get("visualSizeMax")
    if isinstance(size, (int, float)) and size >= 0.9:
        return "a bush"
    if row.get("cavePlant"):
        return "cave growth"
    return "ground cover"


def plant_bits(row: dict, comm) -> str:
    bits = [plant_shape(row)]
    cells = mature_cells(row)
    if cells is not None:
        bits.append(f"{F.num(cells)} squares on screen when grown (a person is 1.5)")
    if row.get("growDays"):
        bits.append(f"grows in {F.num(row['growDays'])} days")
    if row.get("cavePlant"):
        bits.append("cave-only")
    if str(row.get("pollution") or "").lower() not in ("", "any", "none"):
        bits.append(f"pollution: {row['pollution']}")
    product = row.get("product")
    if isinstance(product, dict) and (product.get("label") or product.get("defName")):
        bits.append(f"yields {product.get('label') or product['defName']}")
    if comm is not None:
        bits.append(F.rarity_phrase(comm))
    return " · ".join(bits)


def art_prefills() -> dict[str, str]:
    out = {}
    try:
        doc = json.loads(PLANT_ART_DECISIONS.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return out
    for defname, rec in (doc.get("decisions") or {}).items():
        v = ART_MAP.get(rec.get("decision") or "")
        if v:
            out[defname] = v
    return out


def slugify(text: str) -> str:
    return re.sub(r"-{2,}", "-", re.sub(r"[^a-z0-9]+", "-", str(text).lower())).strip("-")[:60]


def build_items(sheets, plants, panels):
    art_pre = art_prefills()
    cards, flora_rows, ledger_p, ledger_o = [], [], [], []

    for card in CARDS:
        cards.append({
            "id": card["id"], "label": card["label"], "group": CARD_GROUP,
            "thumb": None, "effect": card["q"],
            "card": {"q": card["q"], "trade": card["trade"], "rec": card["rec"]},
            "prefill": card["prefill"], "contested": True,
            "hasSize": False, "hasArt": False,
        })

    for doc in sheets:
        key = doc["sheet"]
        tiles = doc.get("tiles")
        gname = F.pretty_sheet(key) + (f" — {tiles:,} tiles" if isinstance(tiles, int) else "")
        own_defs = set(doc.get("defNames") or [])

        for entry in doc.get("flora") or []:
            defname = entry["def"]
            row = plants.get(defname) or {}
            cells = mature_cells(row)
            mbin = F.size_bin(cells)
            law = entry.get("law") or ""
            note = entry.get("note") or ""
            sentences = []
            if law:
                sentences.append("Why it's here: " + F.plain(law))
            if note:
                sentences.append(F.plain(note))
            interim = bool(re.search(r"interim|stand-in|placeholder", f"{law} {note}", re.I))
            if interim:
                sentences.append("This one is a stand-in: the plant the biome "
                                 "really wants is on the new-art list below, and "
                                 "this is the best available body until it exists.")
            zeroed = any(b.get("biomeDef") in own_defs
                         for b in (row.get("zeroedBiomes") or []))
            if zeroed:
                sentences.append("Heads-up: an old content cut still blocks this "
                                 "plant from growing here — it gets lifted when "
                                 "this row lands as In.")
            pan = (panels.get(defname) or {})
            item = {
                "id": f"flora:{key}:{defname}",
                "label": row.get("label") or defname,
                "group": gname,
                "thumb": (row.get("art") or {}).get("detail"),
                "effect": plant_bits(row, entry.get("commonality")),
                "sentences": sentences,
                "modLine": F.mod_line(row.get("mod") or ""),
                "badge": F.mod_badge(row.get("mod") or ""),
                "prefill": "in",
                "contested": interim,
                "cells": cells,
                "sizeBinPrefill": mbin or "",
                "sizeMeans": ("keeps its current size." if mbin else
                              "I could not measure its grown size."),
                "hasSize": mbin is not None,
                "hasArt": True,
            }
            if art_pre.get(defname):
                item["artPrefill"], item["artSrc"] = art_pre[defname], (
                    "the plant register's grading")
            else:
                ppc = (row.get("art") or {}).get("pxPerCell")
                if ppc is not None and ppc < 0.7:
                    item["artPrefill"], item["artSrc"] = "improve", (
                        "the sprite is blurry at the size the game draws it")
                else:
                    item["artPrefill"], item["artSrc"] = "keep", "no visible defect"
            if pan.get("file"):
                item["panel"] = {"file": pan["file"], "w": pan["w"], "h": pan["h"],
                                 "shown": pan.get("shownPct") or 100}
            else:
                item["sentences"].append("I could not render this one to scale — "
                                         "the small picture is NOT at true size.")
            flora_rows.append(item)

        # ── the NEW ART/DEF ledger ────────────────────────────────────────────
        seen_slugs: dict[str, int] = {}
        for new in doc.get("new_defs") or []:
            kind = (new.get("kind") or "?").lower()
            name = new.get("name") or "(unnamed)"
            slug = slugify(name) or "unnamed"
            n = seen_slugs.get(slug, 0)
            seen_slugs[slug] = n + 1
            if n:
                slug = f"{slug}-{n+1}"
            load = new.get("mechanic_load") or "none"
            needs_code = load and load != "none"
            eff = (f"A new {kind} to create for {F.pretty_sheet(key)}"
                   + (" — needs new game code too: " + F.plain(load) if needs_code
                      else " — art and a definition only, no new code"))
            ledger = ledger_p if kind == "plant" else ledger_o
            ledger.append({
                "id": f"ledger:{key}:{slug}",
                "label": " ".join(str(name).split()[:12]),
                "group": LEDGER_PLANTS if kind == "plant" else LEDGER_OTHER,
                "thumb": None,
                "effect": eff,
                "sentences": [("Asked for by the biome's own design sheet. In "
                               "commissions it as a drawing/def job; Out drops it "
                               "and the biome stays thin there for good.")],
                "prefill": "in",
                "hasSize": False, "hasArt": False,
            })

    flora_rows.sort(key=lambda it: (it["group"],
                                    it["cells"] if it["cells"] is not None else 99,
                                    it["label"].lower()))
    ledger_p.sort(key=lambda it: it["group"] + it["label"].lower())
    ledger_o.sort(key=lambda it: it["group"] + it["label"].lower())
    items = cards + flora_rows + ledger_p + ledger_o
    F.scale_groups(items)

    counts = {
        "rows": len(items),
        "cards": len(cards),
        "flora": len(flora_rows),
        "ledger": len(ledger_p) + len(ledger_o),
        "biomes": len({it["group"] for it in flora_rows}),
        "contested": sum(1 for it in items if it.get("contested")),
        "panels": sum(1 for it in items if it.get("panelSrc")),
    }
    return items, counts


CRITERION = (
    "Rows are what the biome sheets ADMIT — a lawfulness test, not a worth test. "
    "Plant facts are measured from the game's own data; every spawn rate and every "
    "purge-by-name call was mine, and your overrules are the point."
)

INVENTED = [
    "Size bins are mine, same as the fauna sheet: small < 1.0 squares on screen · "
    "medium 1.0–2.2 (a person is 1.5) · large 2.2–5.0 · TITAN over 5.0 — measured "
    "at full growth. Pick a different bin and the plant gets rescaled to match.",
    "True-scale rule: every panel in a biome group shares one px-per-game-square, "
    "chosen so the group's biggest plant fits about 460px. Scale is honest WITHIN "
    "a group; different groups use different zoom levels. The colonist figure is "
    "the same one as the fauna sheet, per your ruling.",
    "'Earth-nameable' was applied by NAME — one agent's reading of each label. A "
    "plant whose label reads as a species you could point at on Earth was purged "
    "planet-wide; nothing verified that per row.",
    "Several biomes are held together by stand-in donor plants while the plant "
    "the sheet really wants sits on the new-art list — those rows say so, and "
    "they are placeholders, not designs.",
    "Every spawn rate on every row is agent-chosen.",
    "The new-things list is what the biome sheets DEMAND, not what anyone agreed "
    "to build — In on one of those rows commissions it as a real queue item.",
    "The retirement flag works as on the fauna sheet: the ⚑ badge only for mods "
    "actually named for retirement; softer wind-down states ride the mod line.",
]


def brief_html(counts):
    return (
        "<p><b>What this is:</b> every plant growing in each of Ash'karr's biomes "
        f"— <b>{counts['flora']}</b> plants across <b>{counts['biomes']}</b> "
        f"biomes — plus the <b>{counts['ledger']}</b>-row list of NEW things the "
        "biome designs demand (plants, creatures and mechanisms that do not exist "
        "yet). What was purged from where is deliberately not shown: this sheet "
        "is about what is IN.</p>"
        "<p><b>The controls:</b> <b>In</b> — it grows where the row says · "
        "<b>Move</b> — a different biome: <i>name it in the note</i> · "
        "<b>Out</b> — it stops growing here (want less of it rather than none? "
        "In, plus a note) · <b>Decide later</b> — parked, on purpose. "
        "On the new-things list at the bottom the same buttons mean: <b>In = "
        "commission it</b> (it gets drawn and built) · <b>Out = drop it for "
        "good</b> · <b>Decide later = park it</b>. "
        "Then <b>size</b>: small / medium / large / TITAN is what the plant "
        "SHOULD be at full growth (small &lt; 1 square · medium 1–2.2, a person "
        "is 1.5 · large 2.2–5 · TITAN 5+) — pick a different bin and it gets "
        "rescaled. And <b>art</b>: keep / improve / redo drives the redraw "
        "queue.</p>"
        "<p><b>The pictures are at true relative scale.</b> Inside each biome "
        "group every plant and the white colonist figure share one zoom level, "
        "smallest first — same figure as the fauna sheet, per your ruling. Click "
        "a small picture for a close-up (the close-up is NOT to scale).</p>"
        f"<p><b>Start with the question card at the top</b> and the "
        f"{counts['contested']} stand-in rows marked as the toughest calls — "
        "those are plants holding a biome together until the real one is drawn. "
        "The note beats every button.</p>"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--sheet-only", action="store_true")
    ap.add_argument("--i-know-this-overwrites-the-owners-decisions",
                    action="store_true", dest="force")
    ap.add_argument("--template")
    args = ap.parse_args()
    if args.template:
        F.TEMPLATE_CANDIDATES.insert(0, pathlib.Path(args.template))

    sheets, _glob = F.read_rosters()
    plants = {r["defName"]: r
              for r in json.loads(PLANT_REGISTER.read_text(encoding="utf-8"))["rows"]}
    panels = json.loads(PANELS.read_text(encoding="utf-8"))["panels"]
    items, counts = build_items(sheets, plants, panels)

    for it in items:
        if it.get("thumb") and not (HERE / it["thumb"]).is_file():
            it["thumb"] = None

    config = {
        "sheetId": "flora_assignment_register",
        "title": "Flora of Ash'karr — what grows where",
        "subtitle": f"{counts['flora']} plants in {counts['biomes']} biomes · "
                    f"{counts['ledger']} new things to create · "
                    f"{counts['cards']} question",
        "briefHtml": brief_html(counts),
        "criterion": CRITERION,
        "invented": INVENTED,
        "posture": {
            "mode": "blacklist",
            "explain": "Everything stands as recommended unless you overrule it. "
                       "Plant rows are already-landed data; a new-things row's In "
                       "commissions it, Out drops it for good.",
        },
        "options": [
            {"key": "in",    "label": "In",           "hotkey": "1", "color": "#5ac37f", "counts": "in"},
            {"key": "move",  "label": "Move",         "hotkey": "2", "color": "#6aa6e8", "counts": "in"},
            {"key": "out",   "label": "Out",          "hotkey": "3", "color": "#e06c6c", "counts": "out"},
            {"key": "later", "label": "Decide later", "hotkey": "4", "color": "#98a2b3"},
        ],
        "groupLabel": "section",
        "media": True,
        "decisionsFile": DECISIONS.name,
        "decisionsPath": NATIVE_DIR + "\\" + DECISIONS.name,
        "sheetPath": NATIVE_DIR + "\\" + SHEET.name,
    }

    SHEET.write_text(F.fill(F.load_template(), config, items), encoding="utf-8")
    print(f"wrote {SHEET.name}: {counts}")

    if args.sheet_only:
        return 0
    F.guard_decisions(DECISIONS, args.force)
    doc = {
        "sheet": "flora_assignment_register",
        "posture": "blacklist",
        "postureMeaning": "Stands as recommended unless overruled. In on a "
                          "new-things row commissions it; Out drops it for good.",
        "criterion": CRITERION,
        "generatedBy": "gen_flora_assignment_sheet.py (2026-09-09 rulings rebuild)",
        "generatedFrom": "design/Jawa/worldbuilding/biomes/rosters/*.json",
        "invented": INVENTED,
        "decisions": {
            it["id"]: {
                "decision": it["prefill"],
                "prefill": it["prefill"],
                "note": it.get("openNote") or "",
                **({"sizeBin": it["sizeBinPrefill"],
                    "sizeBinPrefill": it["sizeBinPrefill"]} if it.get("hasSize") else {}),
                **({"art": it["artPrefill"],
                    "artPrefill": it["artPrefill"]} if it.get("hasArt") else {}),
            }
            for it in items
        },
    }
    DECISIONS.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n",
                         encoding="utf-8")
    print(f"wrote {DECISIONS.name} ({len(doc['decisions'])} pre-filled rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
