using Verse;

namespace RimMandrake.StarWars.Droidworks
{
    /// <summary>
    /// DROIDWORKS_BOLT_CORE_1 shared helper. Both application routes for
    /// RSW_DW_RestrainingBolt - the surgery (Recipe_InstallRestrainingBolt) and
    /// the field clamp (JobDriver_DWClampBolt) - seed RSW_DW_BoltResentment
    /// through this one method, so the sapient gate lives in exactly one
    /// place rather than being duplicated at each call site.
    /// </summary>
    public static class DroidworksBoltUtility
    {
        /// <summary>
        /// Adds RSW_DW_BoltResentment if the pawn is sapient (Humanlike) and does
        /// not already carry it. Idempotent and safe to call from both bolt
        /// application routes unconditionally.
        /// </summary>
        public static void EnsureBoltResentment(Pawn pawn)
        {
            if (pawn?.health?.hediffSet == null) return;
            if (pawn.RaceProps == null || pawn.RaceProps.intelligence != Intelligence.Humanlike) return;
            if (pawn.health.hediffSet.HasHediff(DroidworksDefOf.RSW_DW_BoltResentment)) return;
            pawn.health.AddHediff(DroidworksDefOf.RSW_DW_BoltResentment);
        }

        /// <summary>
        /// DROID_HUTT_CAPTIVES_1 (packet C6) — a third application route, for a
        /// pawn that arrives already bolted rather than being clamped/installed
        /// in front of the player (a captive generated by
        /// <see cref="StockGenerator_DWHuttCaptives"/> or any future site-cast
        /// route). Installs the bolt if missing, then routes through
        /// <see cref="EnsureBoltResentment"/> exactly like the other two routes
        /// so the sapient gate stays in the one place — and finally raises
        /// resentment severity to at least <paramref name="severityRange"/>'s
        /// roll, representing time already held. "At least" because
        /// <see cref="HediffComp_DWBoltResentment"/>'s whole contract is that
        /// resentment never decays; this seeds a floor, it never lowers one a
        /// caller already set.
        /// </summary>
        public static void ApplyCaptiveBolt(Pawn pawn, FloatRange severityRange)
        {
            if (pawn?.health?.hediffSet == null) return;
            if (!pawn.health.hediffSet.HasHediff(DroidworksDefOf.RSW_DW_RestrainingBolt))
            {
                pawn.health.AddHediff(DroidworksDefOf.RSW_DW_RestrainingBolt);
            }
            EnsureBoltResentment(pawn);
            Hediff resentment = pawn.health.hediffSet.GetFirstHediffOfDef(DroidworksDefOf.RSW_DW_BoltResentment);
            if (resentment == null) return;
            float seed = severityRange.RandomInRange;
            if (seed > resentment.Severity)
            {
                resentment.Severity = seed;
            }
        }
    }
}
