#!/usr/bin/env python3
"""lessons.py — the lessons inbox, one file per lesson (git plan Phase 5, 2026-10-02).

    python3 src/RimMandrake/Utils/lessons.py add "<the lesson, one paragraph>" [--seat BENCH] [--slug words]
    python3 src/RimMandrake/Utils/lessons.py render          # -> infrastructure/state/LESSONS_INBOX.md (gitignored)
    python3 src/RimMandrake/Utils/lessons.py list            # count + newest paths

Each lesson is `infrastructure/state/lessons/<utc>-<seat>-<slug>.md`, holding the
lesson text only. Filing is CREATING a file, so two windows filing at once never
touch the same path and never conflict; curation (folding a lesson into its
owning skill) is DELETING the file — which a one-file inbox under `merge=union`
would have silently resurrected (git plan §2.5).

`infrastructure/state/lessons/README.md` is the inbox's standing header, not a
lesson. `LESSONS_INBOX.md` is now a rendered view: gitignored, rebuilt by
`render` on demand; never edit it — an edit there is lost on the next render.
"""
import argparse
import os
import re
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.environ.get("LESSONS_ROOT") or os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
DIR = os.path.join(ROOT, "infrastructure", "state", "lessons")
VIEW = os.path.join(ROOT, "infrastructure", "state", "LESSONS_INBOX.md")
README = "README.md"


def seat_of(explicit=None):
    for v in (explicit, os.environ.get("RIMFLOW_SEAT"), os.environ.get("AGENT_SEAT")):
        if v and re.fullmatch(r"[A-Za-z0-9_]+", v.strip()):
            return v.strip().upper()
    return "UNSEATED"


def slugify(text, n=6):
    words = re.findall(r"[a-z0-9]+", text.lower())
    words = [w for w in words if w not in ("the", "a", "an", "and", "of", "to", "is", "in", "on")]
    return "-".join(words[:n]) or "lesson"


def lesson_files():
    try:
        names = sorted(n for n in os.listdir(DIR) if n.endswith(".md") and n != README)
    except FileNotFoundError:
        return []
    return [os.path.join(DIR, n) for n in names]


def add(text, seat=None, slug=None, utc=None):
    text = text.strip()
    if not text:
        sys.exit("FAIL: empty lesson.")
    os.makedirs(DIR, exist_ok=True)
    utc = utc or time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    base = "%s-%s-%s" % (utc, seat_of(seat), slugify(slug or text))
    path = os.path.join(DIR, base + ".md")
    i = 2
    while os.path.exists(path):
        path = os.path.join(DIR, "%s-%d.md" % (base, i))
        i += 1
    # O_EXCL: never overwrite another window's lesson.
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(text + "\n")
    return path


def render():
    parts = []
    try:
        with open(os.path.join(DIR, README), encoding="utf-8") as f:
            parts.append(f.read().rstrip() + "\n")
    except FileNotFoundError:
        parts.append("# Lessons inbox\n")
    parts.append("\n<!-- GENERATED by src/RimMandrake/Utils/lessons.py render — do not edit; "
                 "file a lesson with `lessons.py add`. -->\n\n")
    files = lesson_files()
    for fp in files:
        with open(fp, encoding="utf-8") as f:
            body = f.read().strip()
        first, *rest = body.splitlines() or [""]
        parts.append("- " + first + "\n")
        for line in rest:
            parts.append("  " + line + "\n" if line.strip() else "\n")
        parts.append("  <sub>`%s`</sub>\n" % os.path.relpath(fp, ROOT))
    tmp = VIEW + ".tmp.%d" % os.getpid()
    with open(tmp, "w", encoding="utf-8") as f:
        f.write("".join(parts))
    os.replace(tmp, VIEW)
    return VIEW, len(files)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("add", help="file one lesson as its own file")
    a.add_argument("text")
    a.add_argument("--seat")
    a.add_argument("--slug", help="a few words for the filename (default: from the text)")
    sub.add_parser("render", help="rebuild the gitignored LESSONS_INBOX.md view")
    sub.add_parser("list", help="count lessons and show the newest")
    args = ap.parse_args()
    if args.cmd == "add":
        p = add(args.text, args.seat, args.slug)
        print(os.path.relpath(p, ROOT))
        print("commit it: git commit %s -m 'lesson: …'" % os.path.relpath(p, ROOT))
    elif args.cmd == "render":
        p, n = render()
        print("%s  (%d lessons)" % (p, n))
    elif args.cmd == "list":
        fs = lesson_files()
        print("%d lessons in %s" % (len(fs), os.path.relpath(DIR, ROOT)))
        for fp in fs[-10:]:
            print("  " + os.path.relpath(fp, ROOT))


if __name__ == "__main__":
    main()
