#!/usr/bin/env python3
"""Mutation proof for the LongShade fuzz: plants each defect in the kernel (RM_LongShadeKernel.cs), demands the fuzz FAILS, restores the file
byte-identical. Exit 0 only if every mutation was caught.

    python3 src/RimMandrake/Utils/mutate_longshade_fuzz.py [name-substring]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from mutate_explosivegrowth_fuzz import run_mutations  # noqa: E402

KERNEL = "src/RimMandrake/LongShade/Source/Kernel/RM_LongShadeKernel.cs"
MUTATIONS = [
    ("tend ignores the layer cap", "return layers < maxLayers && now - lastTendTick >= cooldownTicks;", "return now - lastTendTick >= cooldownTicks;"),
    ("tend cooldown exclusive", "now - lastTendTick >= cooldownTicks", "now - lastTendTick > cooldownTicks"),
    ("tend ignores the cooldown", "return layers < maxLayers && now - lastTendTick >= cooldownTicks;", "return layers < maxLayers;"),
    ("tend adds no progress", "progress += gain;\n            while", "while"),
    ("tend gives no layers", "progress -= 1f;\n                layers++;", "progress -= 1f;"),
    ("tend never spends the unit", "progress -= 1f;\n                layers++;", "layers++;"),
    ("tend goes past the cap", "while (progress >= 1f && layers < maxLayers)", "while (progress >= 1f)"),
    ("tend keeps progress on a full heap", "if (layers >= maxLayers) progress = 0f;", ""),
    ("tend needs more than a full unit", "while (progress >= 1f && layers < maxLayers)", "while (progress > 1f && layers < maxLayers)"),
    ("tend one layer per tend", "while (progress >= 1f && layers < maxLayers)", "if (progress >= 1f && layers < maxLayers)"),
    ("search rolls ignore layers", "return layers * rollsPerLayer;", "return rollsPerLayer;"),
    ("stack split overfills", "int s = Math.Min(n, limit);", "int s = Math.Min(n, limit + 1);"),
    ("stack split drops the remainder", "while (n > 0)", "while (n >= limit)"),
    ("stack split limit floor gone", "int limit = Math.Max(1, stackLimit);", "int limit = stackLimit;"),
    ("start layers unclamped above", "return startLayers < 0 ? 0 : (startLayers > maxLayers ? maxLayers : startLayers);", "return startLayers < 0 ? 0 : startLayers;"),
    ("start layers unclamped below", "return startLayers < 0 ? 0 : (startLayers > maxLayers ? maxLayers : startLayers);", "return startLayers > maxLayers ? maxLayers : startLayers;"),
    ("build with a heap in range", "return !anyHeapInRange && existingHeaps < maxHeapsPerMap;", "return existingHeaps < maxHeapsPerMap;"),
    ("build past the map cap", "return !anyHeapInRange && existingHeaps < maxHeapsPerMap;", "return !anyHeapInRange;"),
    ("build cap off by one", "existingHeaps < maxHeapsPerMap", "existingHeaps <= maxHeapsPerMap"),
    ("spacing exclusive", "return !(distanceToExisting < minSpacing);", "return distanceToExisting > minSpacing;"),
    ("spacing too lax", "return !(distanceToExisting < minSpacing);", "return !(distanceToExisting < minSpacing / 2);"),
    ("nearest tendable radius exclusive", "if (distances[i] > radius) continue;", "if (distances[i] >= radius) continue;"),
    ("nearest tendable ignores tendability", "if (!canTend[i] || distances[i] >= bestDist) continue;", "if (distances[i] >= bestDist) continue;"),
    ("nearest tendable takes the last of equals", "distances[i] >= bestDist", "distances[i] > bestDist"),
    ("nearest tendable takes the farthest", "distances[i] >= bestDist", "distances[i] <= bestDist"),
    ("in range only counts tendable heaps", "anyInRange = true;\n                if (!canTend[i]", "if (!canTend[i]) { continue; }\n                anyInRange = true;\n                if (!canTend[i]"),
    ("untended window nine days", "now - lastTendTick > ticksPerDay * 10", "now - lastTendTick > ticksPerDay * 9"),
    ("untended window inclusive", "now - lastTendTick > ticksPerDay * 10", "now - lastTendTick >= ticksPerDay * 10"),
    ("never tended is tended", "return lastTendTick < 0 || now", "return now"),
    ("rim lower bound inclusive", "return shade > MinRimShade && shade < MaxRimShade;", "return shade >= MinRimShade && shade < MaxRimShade;"),
    ("rim upper bound inclusive", "return shade > MinRimShade && shade < MaxRimShade;", "return shade > MinRimShade && shade <= MaxRimShade;"),
    ("rim band moved", "MaxRimShade = 0.85f", "MaxRimShade = 0.95f"),
    ("rim band lower moved", "MinRimShade = 0.05f", "MinRimShade = 0.0f"),
    ("rim accepts everything", "return shade > MinRimShade && shade < MaxRimShade;", "return true;"),
    ("dash cells uncapped", "return Math.Min(ringCost / (float)cardinalCost, maxDashCells);", "return ringCost / (float)cardinalCost;"),
    ("dash cells integer division", "ringCost / (float)cardinalCost", "ringCost / cardinalCost"),
    ("road spacing unclamped low", "return v < minSpacing ? minSpacing : (v > maxSpacing ? maxSpacing : v);", "return v > maxSpacing ? maxSpacing : v;"),
    ("road spacing unclamped high", "return v < minSpacing ? minSpacing : (v > maxSpacing ? maxSpacing : v);", "return v < minSpacing ? minSpacing : v;"),
    ("road spacing ignores the factor", "float v = dashCells * spacingFactor;", "float v = dashCells;"),
    ("islands ignore edges", "if (island[v] < 0)", "if (island[v] < -5)"),
    ("islands never merge", "island[s] = count;\n                stack.Push(s);", "island[s] = count;"),
    ("islands count wrong cells", "total += cellCounts[u];", "total += 1;"),
    ("islands share an index", "size.Add(total);\n                count++;", "size.Add(total);"),
    ("two biggest takes the smaller", "if (a < 0 || islandCells[i] > islandCells[a])", "if (a < 0 || islandCells[i] < islandCells[a])"),
    ("two biggest ties go to the last", "if (a < 0 || islandCells[i] > islandCells[a])", "if (a < 0 || islandCells[i] >= islandCells[a])"),
    ("two biggest forgets the old leader", "b = a;\n                    a = i;", "a = i;"),
    ("rim sample never trims", "if (all.Count <= sample) return all;", "return all;"),
    ("rim sample uneven", "picked.Add(all[(int)(i * step)]);", "picked.Add(all[i]);"),
    ("rim sample step in integers", "float step = all.Count / (float)sample;", "float step = all.Count / sample;"),
    ("closest pair takes the farthest", "if (d < best)\n                    {\n                        best = d;\n                        ca = ra[i];", "if (d > best || best == long.MaxValue)\n                    {\n                        best = d;\n                        ca = ra[i];"),
    ("closest pair ties go to the last", "if (d < best)\n                    {\n                        best = d;\n                        ca = ra[i];", "if (d <= best)\n                    {\n                        best = d;\n                        ca = ra[i];"),
    ("closest pair swaps axes", "int ax = ra[i] % width, az = ra[i] / width;", "int ax = ra[i] / width, az = ra[i] % width;"),
    ("closest pair ignores z", "long d = (long)dx * dx + (long)dz * dz;", "long d = (long)dx * dx;"),
    ("closest pair manhattan", "long d = (long)dx * dx + (long)dz * dz;", "long d = Math.Abs((long)dx) + Math.Abs((long)dz);"),
    ("road allowed when too short", "if (gap < spacing * minGapSpacings || gap > maxGapCells) return 0;", "if (gap > maxGapCells) return 0;"),
    ("road allowed when too long", "if (gap < spacing * minGapSpacings || gap > maxGapCells) return 0;", "if (gap < spacing * minGapSpacings) return 0;"),
    ("road gap cap exclusive", "gap > maxGapCells", "gap >= maxGapCells"),
    ("road segments round down", "int segments = (int)Math.Ceiling(gap / spacing);", "int segments = (int)Math.Floor(gap / spacing);"),
    ("road stride is the spacing", "stride = gap / segments;", "stride = spacing;"),
    ("road link at the origin", "for (int k = 1; k < segments; k++)", "for (int k = 0; k < segments; k++)"),
    ("road link at the destination", "for (int k = 1; k < segments; k++)", "for (int k = 1; k <= segments; k++)"),
    ("road terminus keeps its link", "if (terminus && k == segments - 1) break;", ""),
    ("road terminus drops a link early", "if (terminus && k == segments - 1) break;", "if (terminus && k == segments - 2) break;"),
    ("grave band lower edge exclusive", "lo = bareCost / 2 + 1;", "lo = bareCost / 2 + 2;"),
    ("grave band lower edge inclusive", "lo = bareCost / 2 + 1;", "lo = bareCost / 2;"),
    ("grave band upper edge", "hi = gearedCost / 2;", "hi = gearedCost / 2 + 1;"),
    ("grave band whole ring", "hi = gearedCost / 2;", "hi = gearedCost;"),
    ("grave fallback fraction ignored", "lo = (int)Math.Round(capCost * fallbackFarFraction);", "lo = 0;"),
    ("grave fallback rounds down", "lo = (int)Math.Round(capCost * fallbackFarFraction);", "lo = (int)(capCost * fallbackFarFraction);"),
    ("grave fallback cap", "hi = capCost;\n            }", "hi = capCost - 1;\n            }"),
    ("grave band takes unreached", "return dist != unreached && dist >= lo && dist <= hi;", "return dist >= lo && dist <= hi;"),
    ("grave band exclusive", "dist >= lo && dist <= hi", "dist > lo && dist < hi"),
    ("graves closer than 20", "return squaredDistance > 400f;", "return squaredDistance > 100f;"),
    ("graves distance inclusive", "return squaredDistance > 400f;", "return squaredDistance >= 400f;"),
    ("ladder opens the last passed rung (the old bug)", "if (elapsedTicks >= (int)Math.Round(afterHours[i] * ticksPerHour)) open = i + 1;\n                else break;", "if (elapsedTicks >= (int)Math.Round(afterHours[i] * ticksPerHour)) open = i + 1;"),
    ("ladder opens early", "elapsedTicks >= (int)Math.Round(afterHours[i] * ticksPerHour)", "elapsedTicks + 1 >= (int)Math.Round(afterHours[i] * ticksPerHour)"),
    ("ladder opens late", "elapsedTicks >= (int)Math.Round(afterHours[i] * ticksPerHour)", "elapsedTicks > (int)Math.Round(afterHours[i] * ticksPerHour)"),
    ("ladder hours in game minutes", "afterHours[i] * ticksPerHour", "afterHours[i] * ticksPerHour / 2"),
    ("admits ignores the race rule", "if (hasRaceRule && !raceListed) return false;", ""),
    ("admits race rule inverted", "if (hasRaceRule && !raceListed) return false;", "if (hasRaceRule && raceListed) return false;"),
    ("admits size cap off", "if (maxBodySize > 0f && bodySize > maxBodySize) return false;", ""),
    ("admits size cap inclusive", "bodySize > maxBodySize", "bodySize >= maxBodySize"),
    ("admits size cap applies at zero", "if (maxBodySize > 0f && bodySize > maxBodySize) return false;", "if (bodySize > maxBodySize) return false;"),
    ("admits ignores the herd rule", "if (herdOnly && !isHerdAnimal) return false;", ""),
    ("first admitting ignores the open count", "for (int i = 0; i < stagesOpen && i < stageCount; i++)", "for (int i = 0; i < stageCount; i++)"),
    ("first admitting takes the last", "for (int i = 0; i < stagesOpen && i < stageCount; i++)\n            {\n                if (admits(i)) return i;\n            }\n            return -1;", "int last = -1;\n            for (int i = 0; i < stagesOpen && i < stageCount; i++)\n            {\n                if (admits(i)) last = i;\n            }\n            return last;"),
    ("near substructure square not circle", "if (dx * dx + dz * dz <= r2 && inSubstructure(x + dx, z + dz)) return true;", "if (inSubstructure(x + dx, z + dz)) return true;"),
    ("near substructure exclusive", "dx * dx + dz * dz <= r2", "dx * dx + dz * dz < r2"),
    ("commons includes the substructure", "if (inSubstructure(x, z) || !standable(x, z) || shadeAt(x, z) < minShade) continue;", "if (!standable(x, z) || shadeAt(x, z) < minShade) continue;"),
    ("commons ignores standability", "if (inSubstructure(x, z) || !standable(x, z) || shadeAt(x, z) < minShade) continue;", "if (inSubstructure(x, z) || shadeAt(x, z) < minShade) continue;"),
    ("commons ignores shade", "if (inSubstructure(x, z) || !standable(x, z) || shadeAt(x, z) < minShade) continue;", "if (inSubstructure(x, z) || !standable(x, z)) continue;"),
    ("commons shade exclusive", "shadeAt(x, z) < minShade", "shadeAt(x, z) <= minShade"),
    ("commons ignores distance", "if (!NearSubstructure(x, z, radius, inSubstructure)) continue;", ""),
    ("commons scan too small", "int x0 = Math.Max(0, subMinX - radius), x1 = Math.Min(mapW - 1, subMaxX + radius);", "int x0 = Math.Max(0, subMinX - radius + 1), x1 = Math.Min(mapW - 1, subMaxX + radius - 1);"),
    ("commons leaves the map", "int x0 = Math.Max(0, subMinX - radius), x1 = Math.Min(mapW - 1, subMaxX + radius);", "int x0 = subMinX - radius, x1 = subMaxX + radius;"),
    ("cache key ignores the engine position", "return gridVersion == version && count == subCount && engineX == ex && engineZ == ez;", "return gridVersion == version && count == subCount;"),
    ("cache key ignores the grid version", "return gridVersion == version && count == subCount && engineX == ex && engineZ == ez;", "return count == subCount && engineX == ex && engineZ == ez;"),
    ("cache key ignores the size", "return gridVersion == version && count == subCount && engineX == ex && engineZ == ez;", "return gridVersion == version && engineX == ex && engineZ == ez;"),
    ("cache key never invalidates", "public void Invalidate()\n            {\n                gridVersion = -1;\n                count = -1;\n                engineX = int.MinValue;\n                engineZ = int.MinValue;\n            }", "public void Invalidate()\n            {\n            }"),
    ("cache key set forgets the version", "gridVersion = version;\n                count = subCount;", "count = subCount;"),
]

if __name__ == "__main__":
    sys.exit(run_mutations(KERNEL, "selftest_longshade_fuzz.py", MUTATIONS, sys.argv[1] if len(sys.argv) > 1 else None))
