#!/usr/bin/env python3
"""Def + structure lint for Huge Things (mandrake.rm.hugethings), no game.

    python3 src/RimMandrake/Utils/selftest_hugethings_lint.py      -> "N/N PASS", exit 0

  * kernel guard: Source/Kernel/*.cs is engine-free and compiled into BOTH the mod and the fuzz project;
  * every plant that opts in (an RM_HugePlantExtension anywhere in src/, by patch or def) carries generated data: a
    measuredSize and >= 1 variant, each variant with a texture, an opaque box inside 0..1 and contact cells, the root
    cell never among them; and the file it lives in carries the measure tool's GENERATED header;
  * no hand-tuned leftovers anywhere in src/: trunkWidth / trunkDepth / stemHeight (the pre-2026-10-07 rect footprint);
  * the blocker def keeps the ruled engine contract (impassable edifice, holdsRoof false, partial fill < 1, hit points
    off) -- GPT review #17: rooms/roofs/LOS behaviour is pinned, fill is never raised to 1 to fake solidity.
Sanity probe: the opt-in sweep must see the nine Rot giants.
"""
import glob
import os
import re
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", ".."))
MOD = os.path.join(SRC, "RimMandrake", "HugeThings")
sys.path.insert(0, HERE)
from lint_kernel_guards import kernel_guards  # noqa: E402

EXT = "RimMandrake.HugeThings.RM_HugePlantExtension"
GENERATED = "GENERATED by `python3 src/RimMandrake/HugeThings/measure_huge_plant_masks.py`"
LEFTOVERS = ("trunkWidth", "trunkDepth", "stemHeight")
PROBE = {"AB_AgariluxPrime", "AB_DribblingCap", "RM_Nogtyl", "RM_Arpeau", "AB_ArbuscularMycorrhiza",
         "AB_AgaricusDomeCap", "AB_GiantAgarilux", "RM_PaleTree", "AB_WitchesOyster"}


def xml_files():
    for p in glob.glob(os.path.join(SRC, "**", "*.xml"), recursive=True):
        if "/obj/" not in p and "/bin/" not in p:
            yield p


def opt_ins():
    """[(file, defName, li element)] for every RM_HugePlantExtension in src/ XML."""
    out = []
    for p in xml_files():
        txt = open(p, encoding="utf-8", errors="replace").read()
        if EXT not in txt:
            continue
        root = ET.parse(p).getroot()
        for el in root.iter():
            for li in el.findall("li"):
                if li.get("Class") == EXT:
                    dn = None
                    if root.tag == "Patch":
                        for op in root:
                            if li in list(op.iter()):
                                m = re.search(r'defName="([^"]+)"', op.findtext("xpath") or "")
                                dn = m.group(1) if m else None
                    else:
                        dn = el.findtext("../defName") or None
                    out.append((p, dn, li))
    return out


TESTS = []


def test(fn):
    TESTS.append(fn)
    return fn


@test
def kernel_is_engine_free_and_compiled_twice():
    errs = kernel_guards(MOD, "RM_HugeThings.csproj", "SelfTest/RimMandrakeHugeThings.SelfTest.csproj", "hugethings-kernel")
    assert not errs, errs


@test
def every_opt_in_has_generated_masks():
    ins = opt_ins()
    seen = {dn for _p, dn, _li in ins}
    assert PROBE <= seen, "sanity probe: the sweep misses %r (saw %d opt-ins)" % (sorted(PROBE - seen), len(ins))
    bad = []
    for p, dn, li in ins:
        rel = os.path.relpath(p, SRC)
        if GENERATED not in open(p, encoding="utf-8").read():
            bad.append("%s: %s lives in a file without the tool's GENERATED header" % (rel, dn))
        size = float(li.findtext("measuredSize") or 0)
        vs = li.findall("variants/li")
        if size <= 0 or not vs:
            bad.append("%s: %s has no measuredSize or no variants" % (rel, dn))
        names = [v.findtext("texture") for v in vs]
        if len(set(names)) != len(names) or not all(names):
            bad.append("%s: %s has duplicate or empty variant textures %r" % (rel, dn, names))
        for v in vs:
            mn = [float(x) for x in (v.findtext("opaqueMin") or "(nan,nan)").strip("()").split(",")]
            mx = [float(x) for x in (v.findtext("opaqueMax") or "(nan,nan)").strip("()").split(",")]
            if not (0 <= mn[0] < mx[0] <= 1 and 0 <= mn[1] < mx[1] <= 1):
                bad.append("%s: %s/%s opaque box %r..%r is not inside 0..1" % (rel, dn, v.findtext("texture"), mn, mx))
            if any(c.text.replace(" ", "") == "(0,0)" for c in v.findall("contact/li")):
                bad.append("%s: %s/%s blocks the root cell" % (rel, dn, v.findtext("texture")))
    assert not bad, bad


@test
def no_hand_tuned_leftovers():
    hits = []
    for p in list(xml_files()) + glob.glob(os.path.join(SRC, "**", "*.cs"), recursive=True):
        if "/obj/" in p:
            continue
        txt = open(p, encoding="utf-8", errors="replace").read()
        for w in LEFTOVERS:
            if re.search(r"\b%s\b" % w, txt):
                hits.append("%s: %s" % (os.path.relpath(p, SRC), w))
    assert not hits, hits


@test
def blocker_def_keeps_the_engine_contract():
    el = ET.parse(os.path.join(MOD, "Defs", "ThingDefs", "RM_HugeTrunkBlocker.xml")).getroot().find("ThingDef")
    assert el is not None and el.findtext("defName") == "RM_HugeTrunkBlocker"
    assert el.findtext("passability") == "Impassable"
    assert el.findtext("building/isEdifice") == "true"
    assert el.findtext("holdsRoof") == "false", "a canopy holds no roof (GPT #17)"
    fill = float(el.findtext("fillPercent"))
    assert 0 < fill < 1, "fillPercent %s: never 1 (would change rooms, sight and cover, GPT #17)" % fill
    assert el.findtext("useHitPoints") == "false", "damage goes to the plant, not the cell"


def main():
    ok = 0
    for fn in TESTS:
        try:
            fn()
            ok += 1
        except AssertionError as e:
            print("FAIL %s: %s" % (fn.__name__, e))
    print("%d/%d PASS" % (ok, len(TESTS)))
    return 0 if ok == len(TESTS) else 1


if __name__ == "__main__":
    sys.exit(main())
