#!/usr/bin/env python3
"""Render canon_gap_census.md from canon_gap_census.json + the per-batch visual verdicts (argv: verdict jsonl files)."""
import json, sys
from collections import Counter, defaultdict
from pathlib import Path
HERE = Path(__file__).parent
R = json.load(open(HERE / "canon_gap_census.json"))
V = {}
for f in sys.argv[1:]:
    for l in open(f):
        if l.strip():
            v = json.loads(l)
            V[v["row"]] = v
LIB = "2026-09-15"
CLS = {"NEVER_REGENERATED": "never regenerated (in-game bytes are donor art; no artpipe render installed)",
       "OVERRIDE_UNTRACED": "our *ArtOverride art, bytes trace to no ledger render (halo pass 09-20 rewrote them)",
       "REGEN_NOT_CANON_BRIEFED": "regenerated, but the installed render's job carried no canon brief",
       "CANON_REGEN": "canon-briefed regen installed"}
for r in R:
    v = V.get(r["row"])
    r["visual"] = v["verdict"] if v else ("n/a (donor art, gap by provenance)" if r["class"] == "NEVER_REGENERATED" else "UNMEASURED")
    r["gap"] = (r["class"] in ("NEVER_REGENERATED", "REGEN_NOT_CANON_BRIEFED", "OVERRIDE_UNTRACED")
                or (v and v["verdict"] != "PASS"))
    if r["class"] == "OVERRIDE_UNTRACED" and v and v["verdict"] == "PASS":
        r["gap"] = False
gaps = [r for r in R if r["gap"]]
uniq = {r["row"] for r in gaps}
L = ["# Canon art gap census — every biome sheet (2026-10-07)", "",
     "Generated by `canon_gap_census.py` (provenance, mechanical) + `canon_gap_census_md.py` (merges a sonnet "
     "visual Must-show check of every row whose in-game art is OURS). Not queued — census only.", "",
     "**Method.** Newest sheet snapshot per biome (`infrastructure/state/art/sheets/`), each row resolved to a "
     "canon-library entry with `art/subject.py resolve_canon`. The IN-GAME column's sha256 is looked up in the art "
     "ledger's `artpipe` events (`infrastructure/state/art/events/*.jsonl`) to find the job that made it, and that "
     "job's done JSON says whether it carried a canon brief (`canon`/`target_canon`/`canon_reference`). "
     f"The canon library dates from {LIB}; override art committed before then cannot have been canon-briefed.", "",
     "## Headline", "",
     f"- **{len(R)} canon rows** across **{len({r['biome'] for r in R})} biome sheets** ({len({r['row'] for r in R})} distinct defs).",
     f"- **{len(gaps)} rows / {len(uniq)} distinct defs are gaps** (never canon-regenerated, or the installed art fails Must show).",
     "- By provenance: " + ", ".join(f"{k} **{v}**" for k, v in Counter(r['class'] for r in R).most_common()),
     "- Visual check of our own installed art (unique defs): " + ", ".join(
         f"{k} **{v}**" for k, v in Counter(x['verdict'] for x in V.values()).most_common()) if V else "- Visual check: UNMEASURED",
     f"- Canon-briefed render already exists but is NOT the in-game art: **{sum(1 for r in R if r['canon_render_not_in_game'])} rows** (listed per row).",
     "", "Classes: " + "; ".join(f"`{k}` = {v}" for k, v in CLS.items()), ""]
byb = defaultdict(list)
for r in R:
    byb[r["biome"]].append(r)
for b in sorted(byb):
    rs = byb[b]
    g = [r for r in rs if r["gap"]]
    L += [f"## {b} — {len(g)} gap(s) of {len(rs)} canon rows ({rs[0]['sheet']})", "",
          "| row | canon entry | in-game art | provenance | Must show (visual) | evidence |", "|---|---|---|---|---|---|"]
    for r in sorted(rs, key=lambda x: (not x["gap"], x["row"])):
        v = V.get(r["row"])
        ev = []
        if r["ingame_jobs"]:
            ev.append("job " + ", ".join(f"`{j['job']}`" + (" (canon brief)" if j["canon_briefed"] else " (no canon brief)") for j in r["ingame_jobs"]))
        if r.get("override_last_commit"):
            ev.append("override last commit " + r["override_last_commit"][:22])
        if v:
            ev.append(v.get("evidence", "")[:200])
            if v.get("failed_lines"):
                ev.append("fails: " + " / ".join(x.strip("- []") [:80] for x in v["failed_lines"][:3]))
        if r["canon_render_not_in_game"]:
            ev.append("canon render on sheet, not installed: " + ", ".join(r["canon_render_not_in_game"]))
        if r["owner"]:
            ev.append(f"owner: {r['owner']['decision']}" + (f" — \"{r['owner']['note'][:120]}\"" if r['owner'].get('note') else ""))
        lab = (r["ingame_label"] or "none").replace("|", "/")
        L.append(f"| {'**' + r['row'] + '**' if r['gap'] else r['row']} | `{r['canon']}` | {lab} | {r['class']} | {r['visual']} | {'; '.join(ev).replace('|', '/')} |")
    L.append("")
(HERE / "canon_gap_census.md").write_text("\n".join(L) + "\n")
print("gaps", len(gaps), "distinct", len(uniq), "visual", Counter(x['verdict'] for x in V.values()))
