#!/usr/bin/env python3
"""Writes MORNING_SHEETS.md: per ruled sheet -> URL, new-render counts, pending jobs. Read-only apart from that file."""
import re, sys, urllib.request
from pathlib import Path
HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "biome_ffar"
Q = Path("/mnt/d/Luke/dev/_artpipe")
SHEETS = [  # label, sheet base, job prefixes (own-biome regen jobs)
    ("RM_Miasma", "miasma_sheet_2026-10-05", ["miasma_"]),
    ("RM_FeverWood", "feverwood_sheet_2026-10-05", ["regen_fw"]),
    ("RM_Greentide", "greentide_sheet_2026-10-05", ["regen_gt"]),
    ("RM_LongShade", "desert_sheet_2026-10-04", ["regen_ls_"]),
    ("RM_LeaningScrub", "leaningscrub_sheet_2026-10-05", ["regen_ls2_", "0vv_"]),
    ("RM_Webwork", "webwork_sheet_2026-10-05", ["webwork_"]),
]
def cnt(d, pre): return sum(1 for p in (Q / d).glob("*.json") if any(p.name.startswith(x) for x in pre))
def url(base):
    log = OUT / f"{base}.serve.log"
    m = re.search(r"http://localhost:\d+/\?t=[A-Za-z0-9_-]+", log.read_text(errors="replace")) if log.is_file() else None
    u = m.group(0) if m else None
    try:
        with urllib.request.urlopen(u, timeout=5) as r: return u, r.status
    except Exception: return u, "DOWN"
rows, tp = [], 0
for label, base, pre in SHEETS:
    h = (OUT / f"{base}.html").read_text(errors="replace")
    flagged = h.count("awaiting your ruling: NEW ART")
    u, st = url(base)
    p, a, d, f = (cnt(x, pre) for x in ("pending", "active", "done", "failed"))
    tp += p + a
    rows.append(f"| {label} | {u} ({st}) | {flagged} | {p + a} ({a} running) | {d} | {f} |")
x = [cnt("pending", ["phfix_"]), cnt("active", ["phfix_"]), cnt("pending", ["wsfix_"]), cnt("active", ["wsfix_"])]
tp += sum(x)
doc = f"""# Morning sheets - ruled biomes with redraws

Generated by `{HERE}/refresh_ruled_sheets.sh` (rerun it at dawn; it is idempotent and keeps ports). Sheet files: `D:\\Luke\\dev\\RimMandrake\\Transient\\biome_ffar\\`.

Each sheet shows new renders as extra columns beside the in-game art; a row whose set landed after your ruling carries the flag **"NEW — awaiting your ruling: NEW ART since your <date> ruling"**. Your saved decisions are untouched (remap check: all letters unchanged, 0 orphaned). Placeholders are unselectable (the guard marks them NEEDS ART).

| sheet | URL | rows flagged NEW | jobs still pending | jobs done (all-time) | failed |
|---|---|---|---|---|---|
{chr(10).join(rows)}

Cross-sheet placeholder fixes (`phfix_*`, rows from many biomes): {x[0] + x[1]} pending/running. Wrong-subject fixes (`wsfix_*`): {x[2] + x[3]} pending/running.
**Total pending/running for these sheets: {tp}.**

Notes: a sheet shows 0 flagged rows until its redraws land (FeverWood and Greentide queues had not started when written); rerun the script as renders arrive. Failed jobs are listed in `D:\\Luke\\dev\\_artpipe\\failed`.
"""
(HERE / "MORNING_SHEETS.md").write_text(doc)
print(doc)
